		Primary = {
			{	Type = "Arm Cannons",
				Classes = { "Arm Cannon" },
				Triggers = {
					{	Name = "Auto",
						{ "Auto" },
						Weapons = { "Bubonico", "Shedu" },
					},
				},
			},
			{	Type = "Assault Rifles",
				Classes = { "Rifle" },
				Triggers = {
					{	Name = "Active",
						{ "Active" },
						Weapons = { "Simulor", "Synoid Simulor" },
					},
					{	Name = "Auto",
						{ "Auto" },
						Weapons = { "Acceltra", "Basmu", "Baza", "Baza Prime", "Boltor", "Boltor Prime", "Telos Boltor" },
					},
					{	Name = "Auto-Burst",
						{ "Auto Burst" },
						Weapons = { "Battacor" },
					},
					{	Name = "Auto-Spool",
						{ "Auto-Spool" },
						Weapons = { "Gorgon", "Prisma Gorgon", "Gorgon Wraith", "Soma", "Soma Prime", "Supra", "Supra Vandal" },
					},
					{	Name = "Burst",
						{ "Burst" },
						Weapons = { "Burston", "Burston Prime", "Harpak", "Hema" },
					},
					{	Name = "Charge",
						{ "Charge" },
						Weapons = { "Miter", "Opticor", "Opticor Vandal" },
					}
				},
			},
