return {
---------------------------------Emplacements-----------------------------------
	Rampart = {
		Attack1 = {
			AttackName = "Normal Attack",
			Damage = {
				Impact = 66.7,
				Puncture = 66.7,
				Slash = 66.6,
			},
			FireRate = 13.3,
			IsSilent = false,
			Multishot = 1,
			PunchThrough = 0,
			Range = 300,
			ShotType = "Hit-Scan",
		},
		Class = "Unique",
		Conclave = false,
		Image = "Rampart.png",
		Introduced = "17.0",
		Link = "Rampart",
		Magazine = 200,
		MaxAmmo = math.huge,
		Name = "Rampart",
		Reload = 4,
		ReloadDelay = 0,
		ReloadRate = 50,
		ReloadStyle = "Regenerate",
		Slot = "Emplacement",
		Traits = {
			"Grineer",
		},
		Trigger = "Auto",
		Users = {
			"Lancer",
			"Elite Lancer",
			"Trooper",
			"Seeker",
		},
	},

-------------------------------------Gear---------------------------------------
	["Ebisu Spear"] = {
		Attack1 = {
			AttackName = "Normal Attack",
			CritMultiplier = 2,
			Damage = {
				Puncture = 10,
			},
			IsSilent = true,
			Multishot = 1,
			PunchThrough = 0,
			StatusChance = 0,
		},
		Class = "Unique",
		Conclave = false,
		Family = "Fishing Spear",
		Image = "EbisuSpear.png",
		InternalName = "/Lotus/Types/Restoratives/Consumable/InfestedFishingSpearB",
		Introduced = "29",
		Link = "Ebisu Spear",
		Name = "Ebisu Spear",
		Range = 20,
		Slot = "Gear",
		Traits = {
			"Cambion Drift",
		},
		Trigger = "Semi-Auto",
	},
	["Lanzo Fishing Spear"] = {
		Attack1 = {
			AttackName = "Normal Attack",
			CritMultiplier = 2,
			Damage = {
				Impact = 10,
			},
			IsSilent = false,
			Multishot = 1,
			PunchThrough = 0,
			StatusChance = 0,
		},
		Class = "Unique",
		Conclave = false,
		Family = "Fishing Spear",
		Image = "IconFishingSpear1.png",
		InternalName = "/Lotus/Types/Restoratives/Consumable/SpearFishingSpear",
		Introduced = "22.0",
		Link = "Lanzo",
		Name = "Lanzo Fishing Spear",
		Range = 20,
		Slot = "Gear",
		Traits = {
			"Cetus",
		},
		Trigger = "Semi-Auto",
	},
	["Peram Fishing Spear"] = {
		Attack1 = {
			AttackName = "Normal Attack",
			CritMultiplier = 2,
			Damage = {
				Slash = 10,
			},
			IsSilent = false,
			Multishot = 1,
			PunchThrough = 0,
			StatusChance = 0,
		},
		Class = "Unique",
		Conclave = false,
		Family = "Fishing Spear",
		Image = "FishingSpearT3Peram.png",
		InternalName = "/Lotus/Types/Restoratives/Consumable/SpearFishingSpearC",
		Introduced = "22.0",
		Link = "Peram",
		Name = "Peram Fishing Spear",
		Range = 20,
		Slot = "Gear",
		Traits = {
			"Cetus",
		},
		Trigger = "Semi-Auto",
	},
	["Shockprod Fishing Spear"] = {
		Attack1 = {
			AttackName = "Normal Attack",
			CritMultiplier = 2,
			Damage = {
				Impact = 10,
			},
			IsSilent = false,
			Multishot = 1,
			PunchThrough = 0,
			StatusChance = 0,
		},
		Class = "Unique",
		Conclave = false,
		Family = "Fishing Spear",
		Image = "Shockprod.png",
		InternalName = "/Lotus/Types/Restoratives/Consumable/RobofishSpearB",
		Introduced = "24.0",
		Link = "Shockprod",
		Name = "Shockprod Fishing Spear",
		Range = 20,
		Slot = "Gear",
		Traits = {
			"Orb Vallis",
		},
		Trigger = "Semi-Auto",
	},
	["Spari Spear"] = {
		Attack1 = {
			AttackName = "Normal Attack",
			CritMultiplier = 2,
			Damage = {
				Puncture = 10,
			},
			IsSilent = true,
			Multishot = 1,
			PunchThrough = 0,
			StatusChance = 0,
		},
		Class = "Unique",
		Conclave = false,
		Family = "Fishing Spear",
		Image = "SpariSpear.png",
		InternalName = "/Lotus/Types/Restoratives/Consumable/InfestedFishingSpearA",
		Introduced = "29",
		Link = "Spari Spear",
		Name = "Spari Spear",
		Range = 20,
		Slot = "Gear",
		Traits = {
			"Cambion Drift",
		},
		Trigger = "Semi-Auto",
	},
	["Stunna Fishing Spear"] = {
		Attack1 = {
			AttackName = "Normal Attack",
			CritMultiplier = 2,
			Damage = {
				Impact = 10,
			},
			IsSilent = false,
			Multishot = 1,
			PunchThrough = 0,
			StatusChance = 0,
		},
		Class = "Unique",
		Conclave = false,
		Family = "Fishing Spear",
		Image = "Stunna.png",
		InternalName = "/Lotus/Types/Restoratives/Consumable/RobofishSpearC",
		Introduced = "24.0",
		Link = "Stunna",
		Name = "Stunna Fishing Spear",
		Range = 20,
		Slot = "Gear",
		Traits = {
			"Orb Vallis",
		},
		Trigger = "Semi-Auto",
	},
	["Tulok Fishing Spear"] = {
		Attack1 = {
			AttackName = "Normal Attack",
			CritMultiplier = 2,
			Damage = {
				Puncture = 10,
			},
			IsSilent = false,
			Multishot = 1,
			PunchThrough = 0,
			StatusChance = 0,
		},
		Class = "Unique",
		Conclave = false,
		Family = "Fishing Spear",
		Image = "IconFishingSpear2.png",
		InternalName = "/Lotus/Types/Restoratives/Consumable/SpearFishingSpearB",
		Introduced = "22.0",
		Link = "Tulok",
		Name = "Tulok Fishing Spear",
		Range = 20,
		Slot = "Gear",
		Traits = {
			"Cetus",
		},
		Trigger = "Semi-Auto",
	},

-----------------------------------Nech-Melee-----------------------------------
	Pugil = {
		Attack1 = {
			AttackName = "Normal Attack",
			CritChance = 0.5,
			CritMultiplier = 2,
			Damage = {
				Impact = 83.3,
				Puncture = 83.3,
				Slash = 83.3,
			},
			FireRate = 1,
			ForcedProcs = {
				"Ragdoll",
			},
			IsSilent = true,
			StatusChance = 0,
		},
		BlockAngle = 60,
		Class = "Unique",
		ComboDur = 5,
		Conclave = false,
		FollowThrough = 0.9,
		HeavyAttack = 250,
		HeavyRadialDmg = 1000,
		HeavySlamAttack = 1000,
		HeavySlamRadius = 9,
		Image = "Pugil.png",
		Introduced = "29.0",
		Link = "Necramech",
		Mastery = 0,
		MeleeRange = 1,
		Name = "Pugil",
		SlamAttack = 500,
		SlamRadialDmg = 500,
		SlamRadialElement = "Blast",
		SlamRadialProcs = {
			"Blast",
		},
		SlamRadius = 8,
		SlideAttack = 500,
		Slot = "Nech-Melee",
		Traits = {
			"Tenno",
		},
		WindUp = 0,
	},

------------------------------------Unique--------------------------------------
	Parazon = {
		Attack1 = {
			AttackName = "Mercy Finisher",
			CritChance = 0,
			CritMultiplier = 1,
			Damage = {
				True = 1,
			},
			FireRate = 1,
			IsSilent = false,
			Multishot = 1,
			PunchThrough = 0,
			StatusChance = 0,
		},
		Class = "Parazon",
		Conclave = false,
		Image = "Parazon.png",
		InternalName = "/Lotus/Weapons/Tenno/HackingDevices/TnHackingDevice/TnHackingDeviceWeapon",
		Introduced = "26",
		Link = "Parazon",
		Name = "Parazon",
		Slot = "Unique",
		Traits = {
			"Tenno",
		},
	},
	Razorflies = {
		Attack1 = {
			AttackName = "Normal Attack",
			CritChance = 0.25,
			CritMultiplier = 2,
			Damage = {
				Slash = 80,
			},
			FireRate = 2,
			IsSilent = false,
			Multishot = 1,
			PunchThrough = 0,
			StatusChance = 0,
		},
		Class = "Unique",
		Conclave = false,
		Image = "Panel.png",
		InternalName = "/Lotus/Powersuits/Fairy/FlightAgentGun",
		Introduced = "The Silver Grove",
		Link = "Razorwing",
		Name = "Razorflies",
		Slot = "Unique",
		Traits = {
			"Tenno",
		},
		Users = {
			"Titania",
			"Titania Prime",
		},
	},
	Soaktron = {
		AmmoType = "Water",
		Attack1 = {
			AttackName = "Normal Attack",
			CritChance = 0.25,
			CritMultiplier = 2,
			Damage = {
				Impact = 45,
			},
			FireRate = 2,
			IsSilent = false,
			Multishot = 1,
			PunchThrough = 0,
			ShotSpeed = 10,
			ShotType = "Projectile",
			StatusChance = 0.25,
		},
		Class = "Unique",
		Conclave = false,
		Image = "SoakTron.png",
		Introduced = "25.5.1",
		Link = "Soaktron",
		Magazine = 100,
		MaxAmmo = math.huge,
		Name = "Soaktron",
		Reload = 0,
		Slot = "Unique",
		Trigger = "Auto",
	},
	Unarmed = {
		Attack1 = {
			AttackName = "Normal Attack",
			CritChance = 0.2,
			CritMultiplier = 2,
			Damage = {
				Impact = 24.5,
				Puncture = 5.3,
				Slash = 5.2,
			},
			FireRate = 0.917,
			IsSilent = false,
			Multishot = 1,
			PunchThrough = 0,
			StatusChance = 0.1,
		},
		BlockAngle = 50,
		Class = "Unique",
		ComboDur = 5,
		Conclave = false,
		FollowThrough = 0.5,
		HeavyAttack = 0,
		HeavyRadialDmg = 0,
		HeavySlamAttack = 0,
		HeavySlamRadius = 0,
		Image = "Blank.png",
		Introduced = "11",
		Link = "Unarmed",
		MeleeRange = 0.5,
		Name = "Unarmed",
		SlamAttack = 70,
		SlamRadialDmg = 0,
		SlamRadius = 7,
		SlideAttack = 140,
		Slot = "Unique",
		WindUp = 0,
	},

---------------------------------Vehicles---------------------------------------
	Dargyn = {
		Attack1 = {
			AttackName = "Normal Attack",
			Damage = {
				Impact = 150,
				Puncture = 150,
				Slash = 150,
			},
			FireRate = 9.03,
			IsSilent = false,
			Multishot = 1,
			PunchThrough = 0,
			ShotSpeed = 300,
			ShotType = "Projectile",
		},
		Class = "Unique",
		Conclave = false,
		Image = "GrnSkiffMissile.png",
		Introduced = "22.12",
		Link = "Dargyn",
		Magazine = 75,
		MaxAmmo = math.huge,
		Name = "Dargyn",
		Reload = 1.8,
		ReloadDelay = 0,
		ReloadRate = 41.7,
		ReloadStyle = "Regenerate",
		Slot = "Vehicle",
		Traits = {
			"Grineer",
		},
		Trigger = "Auto",
		Users = {
			"Dargyn Pilot",
		},
	},
}
