return {
	["Anarch Arcus"] = {
		General = {
			CodexSecret = true,
			Description = "A member of the separatist Dax Anarch faction. It was not uncommon to witness Dax rangers supporting Tenno as they first leanrt to control their Warframes, filling in offensive gaps with precise aim.",
			Faction = "Anarchs",
			Image = "AnarchArcus.png",
			InternalName = "/Lotus/Types/Enemies/Tau/Dax/TauDaxArcher/AnarchTauDaxArcherAgent",
			Introduced = "41",
			Link = "Anarch Arcus",
			Name = "Anarch Arcus",
			Planets = { "Perita" },
			Missions = { "The Perita Rebellion" },
			TileSets = { "Perita" },
			Scans = 20,
			Type = "Ranged",
			Weapons = { "Tau Dax Rifle" },
		},
		Stats = {
			Health = 100,
			Armor = 35,
			Affinity = -1,
			BaseLevel = 1,
			Multis = { "Head: 3.0x" },
		}
	},
	["Anarch Capsarii"] = {
		General = {
			CodexSecret = true,
			Description = "A member of the separatist Dax Anarch dfaction. With shield above and staff in hand, Dax medics are as adept at healing as their brethren are at cutting down the opposition.",
			Faction = "Anarchs",
			Image = "AnarchCapsarii.png",
			InternalName = "/Lotus/Types/Enemies/Tau/Dax/TauDaxMedic/AnarchTauDaxMedicAgent",
			Introduced = "41",
			Link = "Anarch Capsarii",
			Name = "Anarch Capsarii",
			Planets = { "Perita" },
			Missions = { "The Perita Rebellion" },
			TileSets = { "Perita" },
			Scans = 15,
			Type = "Ranged",
			Weapons = { "Tau Dax Staff" },
		},
		Stats = {
			Health = 75,
			Armor = 20,
			Affinity = -1,
			BaseLevel = 1,
			Multis = { "Head: 3.0x" },
		}
	},
	["Anarch Gladius"] = {
		General = {
			CodexSecret = true,
			Description = "A member of the separatist Dax Anarch dfaction. Within the minds of those dedicated to the blade lies a singular focus; to annihilate their enemy in the most effective manner possible.",
			Faction = "Anarchs",
			Image = "AnarchGladius.png",
			InternalName = "/Lotus/Types/Enemies/Tau/Dax/TauDaxSwordsman/AnarchTauDaxSwordsmanAgent",
			Introduced = "41",
			Link = "Anarch Gladius",
			Name = "Anarch Gladius",
			Planets = { "Perita" },
			Missions = { "The Perita Rebellion" },
			TileSets = { "Perita" },
			Scans = 20,
			Type = "Melee",
			Weapons = { "Tau Dax Nikana" },
		},
		Stats = {
			Health = 175,
			Armor = 125,
			Affinity = -1,
			BaseLevel = 1,
			Multis = { "Head: 3.0x" },
		}
	},
	["Anarch Grineer Lancer"] = {
		General = {
			CodexSecret = true,
			Description = "A cloned soldier in top fighting form. Lancers formed the front line of the Orokin legions, advancing relentlessly to carry the full might of the army deep into enemy territory. Lancers were chosen for sheer-minded determination, the ones who found it hard to let go of an idea.",
			Faction = "Anarchs",
			Image = "AnarchGrineerLancer.png",
			InternalName = "/Lotus/Types/Enemies/Tau/Grineer/TauGrineerLancer/AnarchTauGrineerLancerAgent",
			Introduced = "41",
			Link = "Anarch Grineer Lancer",
			Name = "Anarch Grineer Lancer",
			Planets = { "Perita" },
			Missions = { "The Perita Rebellion" },
			TileSets = { "Perita" },
			Scans = 20,
			Type = "Ranged",
			Weapons = { "Gotva Prime" },
		},
		Stats = {
			Health = 125,
			Armor = 100,
			Affinity = -1,
			BaseLevel = 1,
			Multis = { "Head: 3.0x" },
		}
	},
	["Anarch Grineer Trapper"] = {
		General = {
			CodexSecret = true,
			Description = "Only the most cunning of clone stock are chosen to become trappers. These are given training in the operation of Trapper Drones by Archimedea; many do not make it through the training. Trappers are frequently ostracized from their squads due to mishaps while they are learning to aim.",
			Faction = "Anarchs",
			Image = "AnarchGrineerTrapper.png",
			InternalName = "/Lotus/Types/Enemies/Tau/Grineer/TauGrineerTrapper/AnarchTauGrineerTrapperAgent",
			Introduced = "41",
			Link = "Anarch Grineer Trapper",
			Name = "Anarch Grineer Trapper",
			Planets = { "Perita" },
			Missions = { "The Perita Rebellion" },
			TileSets = { "Perita" },
			Scans = 15,
			Type = "Melee",
			Weapons = { "Galariak Prime" },
		},
		Stats = {
			Health = 100,
			Armor = 100,
			Affinity = -1,
			BaseLevel = 1,
			Multis = { "Head: 3.0x" },
		}
	},
	["Anarch Libritor"] = {
		General = {
			CodexSecret = true,
			Description = "A member of the separatist Dax Anarch faction. Across many operations, the thunderous salvo of a Libritor Archgun served as a signal for hidden Dax forced to emerge from the shadows and fall upon their enemies like a guillotine's blade.",
			Faction = "Anarchs",
			Image = "AnarchLibritor.png",
			InternalName = "/Lotus/Types/Enemies/Tau/Dax/TauDaxHeavyArch/AnarchTauDaxHeavyArchgunAgent",
			Introduced = "41",
			Link = "Anarch Libritor",
			Name = "Anarch Libritor",
			Planets = { "Perita" },
			Missions = { "The Perita Rebellion" },
			TileSets = { "Perita" },
			Scans = 5,
			Type = "Heavy",
			Weapons = { "Libritor" },
		},
		Stats = {
			Health = 325,
			Armor = 150,
			Affinity = -1,
			BaseLevel = 1,
			Multis = { "Head: 3.0x" },
		}
	},
	["Anarch Tenebra"] = {
		General = {
			CodexSecret = true,
			Description = "A member of the separatist Dax Anarch faction. While their ability and disappearing techniques allowed these Dax to quell revolts before they had formed in earnest, their experiences allowed for their own rebellion to to flourish where all others have failed.",
			Faction = "Anarchs",
			Image = "AnarchTenebra.png",
			InternalName = "/Lotus/Types/Enemies/Tau/Dax/TauDaxNinja/AnarchTauDaxNinjaAgent",
			Introduced = "41",
			Link = "Anarch Tenebra",
			Name = "Anarch Tenebra",
			Planets = { "Perita" },
			Missions = { "The Perita Rebellion" },
			TileSets = { "Perita" },
			Scans = 15,
			Type = "Ranged",
			Weapons = { "Tau Dax Thrown Weapon" },
		},
		Stats = {
			Health = 100,
			Armor = 50,
			Affinity = -1,
			BaseLevel = 1,
			Multis = { "Head: 3.0x" },
		}
	},
	["Commandeered Ash Prime"] = {
		General = {
			Abilities = { "Smoke Screen", "Teleport", "Blade Storm" },
			Description = "",
			Faction = "Anarchs",
			Image = "AshPrime_Thumb.png",
			InternalName = "/Lotus/Types/Enemies/Tau/Primes/Ash/AshPrimeBossAgent",
			Introduced = "41",
			Link = "Commandeered Ash Prime",
			Missions = { "The Perita Rebellion" },
			Name = "Commandeered Ash Prime",
			Planets = { "Perita" },
			Scans = 1,
			TileSets = { "Perita" },
			Type = "Boss",
			Weapons = { "Hikou Prime", "Nikana Prime" },
		},
		Stats = {
			Health = 15000,
			SteelPathHealthBonus = 10000,
			Armor = 50,
			Shield = 1750,
			SteelPathShieldBonus = 10000,
			Affinity = 5000,
			BaseLevel = 1,
			SpawnLevel = 70,
			Multis = { "Head: 3.0x" },
		}
	},
	["Commandeered Ash Prime (Field Boss)"] = {
		General = {
			Abilities = { "" },
			Description = "",
			Faction = "Anarchs",
			Image = "AshPrime_Thumb.png",
			InternalName = "/Lotus/Types/Enemies/Tau/Primes/Ash/AshPrimeTMWAgent",
			Introduced = "41",
			Link = "Commandeered Prime#Ash Prime (Field Boss)",
			Missions = { "The Perita Rebellion" },
			Name = "Commandeered Ash Prime (Field Boss)",
			Planets = { "Perita" },
			Scans = 1,
			TileSets = { "Perita" },
			Type = "Field Boss",
			Weapons = { "Hikou Prime", "Nikana Prime" },
		},
		Stats = {
			Health = 15000,
			Armor = 50,
			Shield = 1750,
			Affinity = 5000,
			BaseLevel = 1,
			SpawnLevel = 65,
			Multis = { "Head: 3.0x" },
		}
	},
	["Commandeered Ash Prime (The Guilty)"] = {
		General = {
			Abilities = { "Smoke Screen", "Teleport", "Blade Storm" },
			Description = "",
			EmpoweredDefault = true,
			Faction = "Anarchs",
			Image = "AshPrime_Thumb.png",
			InternalName = "/Lotus/Types/Enemies/Tau/Primes/Ash/AshPrimeBossHardModeAgent",
			Introduced = "42",
			Link = "Commandeered Prime#Ash Prime (The Guilty)",
			Missions = { "The Guilty" },
			Name = "Commandeered Ash Prime (The Guilty)",
			Planets = { "Perita" },
			Scans = 1,
			TileSets = { "Perita" },
			Type = "Boss",
			Weapons = { "Hikou Prime", "Nikana Prime" },
		},
		Stats = {
			Health = 15000,
			Armor = 50,
			Shield = 10750,
			Affinity = 5000,
			BaseLevel = 1,
			SpawnLevel = 270,
			Multis = { "Head: 3.0x" },
		}
	},
	["Commandeered Caliban Prime"] = {
		General = {
			Abilities = { "" },
			Description = "",
			Faction = "Anarchs",
			Image = "CalibanPrime_Thumb.png",
			InternalName = "/Lotus/Types/Enemies/Tau/Primes/Caliban/CalibanPrimeBossAgent",
			Introduced = "41",
			Link = "Commandeered Caliban Prime",
			Missions = { "The Perita Rebellion" },
			Name = "Commandeered Caliban Prime",
			Planets = { "Perita" },
			Scans = 1,
			TileSets = { "Perita" },
			Type = "Boss",
			Weapons = { "Vadarya Prime", "Venato Prime" },
		},
		Stats = {
			Health = 15000,
			SteelPathHealthBonus = 10000,
			Armor = 50,
			Shield = 1750,
			SteelPathShieldBonus = 10000,
			Affinity = 5000,
			BaseLevel = 1,
			SpawnLevel = 70,
			Multis = { "Head: 3.0x" },
		}
	},
	["Commandeered Caliban Prime (Field Boss)"] = {
		General = {
			Abilities = { "" },
			Description = "",
			Faction = "Anarchs",
			Image = "CalibanPrime_Thumb.png",
			InternalName = "/Lotus/Types/Enemies/Tau/Primes/Caliban/CalibanPrimeTMWAgent",
			Introduced = "41",
			Link = "Commandeered Prime#Caliban Prime (Field Boss)",
			Missions = { "The Perita Rebellion" },
			Name = "Commandeered Caliban Prime (Field Boss)",
			Planets = { "Perita" },
			Scans = 1,
			TileSets = { "Perita" },
			Type = "Field Boss",
			Weapons = { "Vadarya Prime", "Venato Prime" },
		},
		Stats = {
			Health = 15000,
			Armor = 50,
			Shield = 1750,
			Affinity = 5000,
			BaseLevel = 1,
			SpawnLevel = 65,
			Multis = { "Head: 3.0x" },
		}
	},
	["Commandeered Caliban Prime (The Guilty)"] = {
		General = {
			Abilities = { "Razor Gyre", "Sentient Stomp", "Lethal Progney", "Fusion Strike" },
			Description = "",
			EmpoweredDefault = true,
			Faction = "Anarchs",
			Image = "CalibanPrime_Thumb.png",
			InternalName = "/Lotus/Types/Enemies/Tau/Primes/Caliban/CalibanPrimeBossHardModeAgent",
			Introduced = "42",
			Link = "Commandeered Prime#Caliban Prime (The Guilty)",
			Missions = { "The Guilty" },
			Name = "Commandeered Caliban Prime (The Guilty)",
			Planets = { "Perita" },
			Scans = 1,
			TileSets = { "Perita" },
			Type = "Boss",
			Weapons = { "Vadarya Prime", "Venato Prime" },
		},
		Stats = {
			Health = 15000,
			Armor = 50,
			Shield = 10750,
			Affinity = 5000,
			BaseLevel = 1,
			SpawnLevel = 270,
			Multis = { "Head: 3.0x" },
		}
	},
	["Commandeered Ember Prime"] = {
		General = {
			Abilities = { "" },
			Description = "",
			Faction = "Anarchs",
			Image = "EmberPrime_Thumb.png",
			InternalName = "/Lotus/Types/Enemies/Tau/Primes/Ember/EmberPrimeBossAgent",
			Introduced = "41",
			Link = "Commandeered Ember Prime",
			Missions = { "The Perita Rebellion" },
			Name = "Commandeered Ember Prime",
			Planets = { "Perita" },
			Scans = 1,
			TileSets = { "Perita" },
			Type = "Boss",
			Weapons = { "Sicarus Prime", "Glaive Prime" },
		},
		Stats = {
			Health = 15000,
			SteelPathHealthBonus = 10000,
			Armor = 50,
			Shield = 1750,
			SteelPathShieldBonus = 10000,
			Affinity = 5000,
			BaseLevel = 1,
			SpawnLevel = 70,
			Multis = { "Head: 3.0x" },
		}
	},
	["Commandeered Ember Prime (Field Boss)"] = {
		General = {
			Abilities = { "" },
			Description = "",
			Faction = "Anarchs",
			Image = "EmberPrime_Thumb.png",
			InternalName = "/Lotus/Types/Enemies/Tau/Primes/Ember/EmberPrimeTMWAgent",
			Introduced = "41",
			Link = "Commandeered Prime#Ember Prime (Field Boss)",
			Missions = { "The Perita Rebellion" },
			Name = "Commandeered Ember Prime (Field Boss)",
			Planets = { "Perita" },
			Scans = 1,
			TileSets = { "Perita" },
			Type = "Field Boss",
			Weapons = { "Sicarus Prime", "Glaive Prime" },
		},
		Stats = {
			Health = 15000,
			Armor = 50,
			Shield = 1750,
			Affinity = 5000,
			BaseLevel = 1,
			SpawnLevel = 65,
			Multis = { "Head: 3.0x" },
		}
	},
	["Commandeered Ember Prime (The Guilty)"] = {
		General = {
			Abilities = { "" },
			Description = "",
			EmpoweredDefault = true,
			Faction = "Anarchs",
			Image = "EmberPrime_Thumb.png",
			InternalName = "/Lotus/Types/Enemies/Tau/Primes/Ember/EmberPrimeBossHardModeAgent",
			Introduced = "42",
			Link = "Commandeered Prime#Ember Prime (The Guilty)",
			Missions = { "The Guilty" },
			Name = "Commandeered Ember Prime (The Guilty)",
			Planets = { "Perita" },
			Scans = 1,
			TileSets = { "Perita" },
			Type = "Boss",
			Weapons = { "Sicarus Prime", "Glaive Prime" },
		},
		Stats = {
			Health = 15000,
			Armor = 50,
			Shield = 10750,
			Affinity = 5000,
			BaseLevel = 1,
			SpawnLevel = 270,
			Multis = { "Head: 3.0x" },
		}
	},
	["Commandeered Mesa Prime"] = {
		General = {
			Abilities = { "" },
			Description = "",
			Faction = "Anarchs",
			Image = "MesaPrime_Thumb.png",
			InternalName = "/Lotus/Types/Enemies/Tau/Primes/Mesa/MesaPrimeBossAgent",
			Introduced = "41",
			Link = "Commandeered Mesa Prime",
			Missions = { "The Perita Rebellion" },
			Name = "Commandeered Mesa Prime",
			Planets = { "Perita" },
			Scans = 1,
			TileSets = { "Perita" },
			Type = "Boss",
			Weapons = { "Akjagara Prime", "Redeemer Prime" },
		},
		Stats = {
			Health = 15000,
			SteelPathHealthBonus = 10000,
			Armor = 50,
			Shield = 1750,
			SteelPathShieldBonus = 10000,
			Affinity = 5000,
			BaseLevel = 1,
			SpawnLevel = 70,
			Multis = { "Head: 3.0x" },
		}
	},
	["Commandeered Mesa Prime (Field Boss)"] = {
		General = {
			Abilities = { "" },
			Description = "",
			Faction = "Anarchs",
			Image = "MesaPrime_Thumb.png",
			InternalName = "/Lotus/Types/Enemies/Tau/Primes/Mesa/MesaPrimeTMWAgent",
			Introduced = "41",
			Link = "Commandeered Prime#Mesa Prime (Field Boss)",
			Missions = { "The Perita Rebellion" },
			Name = "Commandeered Mesa Prime (Field Boss)",
			Planets = { "Perita" },
			Scans = 1,
			TileSets = { "Perita" },
			Type = "Field Boss",
			Weapons = { "Akjagara Prime", "Redeemer Prime" },
		},
		Stats = {
			Health = 15000,
			Armor = 50,
			Shield = 1750,
			Affinity = 5000,
			BaseLevel = 1,
			SpawnLevel = 65,
			Multis = { "Head: 3.0x" },
		}
	},
	["Commandeered Mesa Prime (The Guilty)"] = {
		General = {
			Abilities = { "" },
			Description = "",
			EmpoweredDefault = true,
			Faction = "Anarchs",
			Image = "MesaPrime_Thumb.png",
			InternalName = "/Lotus/Types/Enemies/Tau/Primes/Mesa/MesaPrimeBossHardModeAgent",
			Introduced = "42",
			Link = "Commandeered Prime#Mesa Prime (The Guilty)",
			Missions = { "The Guilty" },
			Name = "Commandeered Mesa Prime (The Guilty)",
			Planets = { "Perita" },
			Scans = 1,
			TileSets = { "Perita" },
			Type = "Boss",
			Weapons = { "Akjagara Prime", "Redeemer Prime" },
		},
		Stats = {
			Health = 15000,
			Armor = 50,
			Shield = 10750,
			Affinity = 5000,
			BaseLevel = 1,
			SpawnLevel = 270,
			Multis = { "Head: 3.0x" },
		}
	},
	["Commandeered Protea Prime"] = {
		General = {
			Abilities = { "" },
			Description = "",
			Faction = "Anarchs",
			Image = "ProteaPrime_Thumb.png",
			InternalName = "/Lotus/Types/Enemies/Tau/Primes/Protea/ProteaPrimeBossAgent",
			Introduced = "41",
			Link = "Commandeered Protea Prime",
			Missions = { "The Perita Rebellion" },
			Name = "Commandeered Protea Prime",
			Planets = { "Perita" },
			Scans = 1,
			TileSets = { "Perita" },
			Type = "Boss",
			Weapons = { "Velox Prime", "Okina Prime" },
		},
		Stats = {
			Health = 15000,
			SteelPathHealthBonus = 10000,
			Armor = 50,
			Shield = 1750,
			SteelPathShieldBonus = 10000,
			Affinity = 5000,
			BaseLevel = 1,
			SpawnLevel = 70,
			Multis = { "Head: 3.0x" },
		}
	},
	["Commandeered Protea Prime (Field Boss)"] = {
		General = {
			Abilities = { "" },
			Description = "",
			Faction = "Anarchs",
			Image = "ProteaPrime_Thumb.png",
			InternalName = "/Lotus/Types/Enemies/Tau/Primes/Protea/ProteaPrimeTMWAgent",
			Introduced = "41",
			Link = "Commandeered Prime#Protea Prime (Field Boss)",
			Missions = { "The Perita Rebellion" },
			Name = "Commandeered Protea Prime (Field Boss)",
			Planets = { "Perita" },
			Scans = 1,
			TileSets = { "Perita" },
			Type = "Field Boss",
			Weapons = { "Velox Prime", "Okina Prime" },
		},
		Stats = {
			Health = 15000,
			Armor = 50,
			Shield = 1750,
			Affinity = 5000,
			BaseLevel = 1,
			SpawnLevel = 65,
			Multis = { "Head: 3.0x" },
		}
	},
	["Commandeered Protea Prime (The Guilty)"] = {
		General = {
			Abilities = { "" },
			Description = "",
			EmpoweredDefault = true,
			Faction = "Anarchs",
			Image = "ProteaPrime_Thumb.png",
			InternalName = "/Lotus/Types/Enemies/Tau/Primes/Protea/ProteaPrimeBossHardModeAgent",
			Introduced = "42",
			Link = "Commandeered Prime#Protea Prime (The Guilty)",
			Missions = { "The Guilty" },
			Name = "Commandeered Protea Prime (The Guilty)",
			Planets = { "Perita" },
			Scans = 1,
			TileSets = { "Perita" },
			Type = "Boss",
			Weapons = { "Velox Prime", "Okina Prime" },
		},
		Stats = {
			Health = 15000,
			Armor = 50,
			Shield = 10750,
			Affinity = 5000,
			BaseLevel = 1,
			SpawnLevel = 270,
			Multis = { "Head: 3.0x" },
		}
	},
	["Commandeered Trinity Prime"] = {
		General = {
			Abilities = { "" },
			Description = "",
			EmpoweredDefault = true,
			Faction = "Anarchs",
			Image = "TrinityPrime_Thumb.png",
			InternalName = "/Lotus/Types/Enemies/Tau/Primes/Trinity/TrinityPrimeBossAgent",
			Introduced = "42",
			Link = "Commandeered Trinity Prime",
			Missions = { "The Guilty" },
			Name = "Commandeered Trinity Prime",
			Planets = { "Perita" },
			Scans = 1,
			TileSets = { "Perita" },
			Type = "Boss",
			Weapons = { "Lex Prime", "Dual Kamas Prime" },
		},
		Stats = {
			Health = 8500,
			Armor = 5,
			Shield = 150,
			Affinity = 5000,
			BaseLevel = 1,
			SpawnLevel = 270,
			Multis = { "Head: 3.0x" },
		}
	},
	["Commandeered Volt Prime"] = {
		General = {
			Abilities = { "" },
			Description = "",
			Faction = "Anarchs",
			Image = "VoltPrime_Thumb.png",
			InternalName = "/Lotus/Types/Enemies/Tau/Primes/Volt/VoltPrimeBossAgent",
			Introduced = "41",
			Link = "Commandeered Volt Prime",
			Missions = { "The Perita Rebellion" },
			Name = "Commandeered Volt Prime",
			Planets = { "Perita" },
			Scans = 1,
			TileSets = { "Perita" },
			Type = "Boss",
			Weapons = { "Corvas Prime", "Dual Keres Prime" },
		},
		Stats = {
			Health = 15000,
			SteelPathHealthBonus = 10000,
			Armor = 50,
			Shield = 1750,
			SteelPathShieldBonus = 10000,
			Affinity = 5000,
			BaseLevel = 1,
			SpawnLevel = 70,
			Multis = { "Head: 3.0x" },
		}
	},
	["Commandeered Volt Prime (Field Boss)"] = {
		General = {
			Abilities = { "" },
			Description = "",
			Faction = "Anarchs",
			Image = "VoltPrime_Thumb.png",
			InternalName = "/Lotus/Types/Enemies/Tau/Primes/Volt/VoltPrimeTMWAgent",
			Introduced = "41",
			Link = "Commandeered Prime#Volt Prime (Field Boss)",
			Missions = { "The Perita Rebellion" },
			Name = "Commandeered Volt Prime (Field Boss)",
			Planets = { "Perita" },
			Scans = 1,
			TileSets = { "Perita" },
			Type = "Field Boss",
			Weapons = { "Corvas Prime", "Dual Keres Prime" },
		},
		Stats = {
			Health = 15000,
			Armor = 50,
			Shield = 1750,
			Affinity = 5000,
			BaseLevel = 1,
			SpawnLevel = 65,
			Multis = { "Head: 3.0x" },
		}
	},
	["Commandeered Volt Prime (The Guilty)"] = {
		General = {
			Abilities = { "" },
			Description = "",
			EmpoweredDefault = true,
			Faction = "Anarchs",
			Image = "VoltPrime_Thumb.png",
			InternalName = "/Lotus/Types/Enemies/Tau/Primes/Volt/VoltPrimeBossHardModeAgent",
			Introduced = "42",
			Link = "Commandeered Prime#Volt Prime (The Guilty)",
			Missions = { "The Guilty" },
			Name = "Commandeered Volt Prime (The Guilty)",
			Planets = { "Perita" },
			Scans = 1,
			TileSets = { "Perita" },
			Type = "Boss",
			Weapons = { "Corvas Prime", "Dual Keres Prime" },
		},
		Stats = {
			Health = 15000,
			Armor = 50,
			Shield = 10750,
			Affinity = 5000,
			BaseLevel = 1,
			SpawnLevel = 270,
			Multis = { "Head: 3.0x" },
		}
	}
}
