	["Ability Name"] = {
		CardImage = "CardImageName.png",
		Cost = 100,
		CostType = "Mutation",
		Description = "In-game ability description",
		Icon = "AbilityIcon.png",
  		InternalName = "/Lotus/Powersuits/PowersuitAbilities/",
		Introduced = "29",
		Key = 4,
		Link = "Page Name",
		Name = "Ability Name",
		Powersuit = "Warframe/Necramech/Archwing Name",
		Preview = "AbilityPreview.webm",
		PreviewFallback = "AbilityPreview.jpg",
		Subsumable = false,
	},
