return {
	Map = {
		options = {
			mode = 'invocation',
			nowiki = true,
			preprocess = true,
		},
		tests = {
			{
				'Duviri Joy Spiral|Yao Shrub',
				'<div data-icon-anchor="bottom-center" data-enable-search="true" data-enable-collected-all-notification="false" data-disabled-categories="["settings"]" data-enable-sidebar="false" data-map-controls="[[],["zoom","fullscreen"],["edit"],[]]" data-category-groups="[{"children":["scholars_landing","we_are_not","watchers_island","lake_veruna","galleria","doll_mausoleum","caves_of_academe","manipura_island","island_of_lorn","bleeding_earth"],"collapsed":"true","label":"Fragments"},{"children":["connla_sprout","dracroot","eevani","kovnik","saggen_pearl","silphsela","yao_shrub"],"collapsed":"true","label":"Resources"},{"children":["puzzle","puzzle_coop"],"collapsed":"true","label":"Puzzles"},{"children":["fishing","herding","game","shawzin"],"collapsed":"true","label":"Activities"}]" data-sort-markers="category" data-hidden-categories="["blinkpad","shop","cave","fishing","game","puzzle","puzzle_coop","shawzin","herding","connla_sprout","dracroot","eevani","kovnik","saggen_pearl","silphsela","scholars_landing","we_are_not","watchers_island","lake_veruna","galleria","doll_mausoleum","caves_of_academe","manipura_island","island_of_lorn","bleeding_earth","settings"]" data-collectible-expiry-time="-1" data-use-custom-popups="true" data-minimal-layout="true" data-collectible-categories="["scholars_landing","we_are_not","watchers_island","lake_veruna","galleria","doll_mausoleum","caves_of_academe","manipura_island","island_of_lorn","bleeding_earth"]" data-fullscreen-mode="window" data-enable-tooltips="true" data-enable-fullscreen="true">{{Map:Duviri Joy Spiral}}</div>'
			},
			{
				'Duviri Joy Spiral|Yao Shrub|Saggen Pearl',
				'<div data-icon-anchor="bottom-center" data-enable-search="true" data-enable-collected-all-notification="false" data-disabled-categories="["settings"]" data-enable-sidebar="false" data-map-controls="[[],["zoom","fullscreen"],["edit"],[]]" data-category-groups="[{"children":["scholars_landing","we_are_not","watchers_island","lake_veruna","galleria","doll_mausoleum","caves_of_academe","manipura_island","island_of_lorn","bleeding_earth"],"collapsed":"true","label":"Fragments"},{"children":["connla_sprout","dracroot","eevani","kovnik","saggen_pearl","silphsela","yao_shrub"],"collapsed":"true","label":"Resources"},{"children":["puzzle","puzzle_coop"],"collapsed":"true","label":"Puzzles"},{"children":["fishing","herding","game","shawzin"],"collapsed":"true","label":"Activities"}]" data-sort-markers="category" data-hidden-categories="["blinkpad","shop","cave","fishing","game","puzzle","puzzle_coop","shawzin","herding","connla_sprout","dracroot","eevani","kovnik","silphsela","scholars_landing","we_are_not","watchers_island","lake_veruna","galleria","doll_mausoleum","caves_of_academe","manipura_island","island_of_lorn","bleeding_earth","settings"]" data-collectible-expiry-time="-1" data-use-custom-popups="true" data-minimal-layout="true" data-collectible-categories="["scholars_landing","we_are_not","watchers_island","lake_veruna","galleria","doll_mausoleum","caves_of_academe","manipura_island","island_of_lorn","bleeding_earth"]" data-fullscreen-mode="window" data-enable-tooltips="true" data-enable-fullscreen="true">{{Map:Duviri Joy Spiral}}</div>'
			},
			{
				'Duviri Joy Spiral|Fragments',
				'<div data-icon-anchor="bottom-center" data-enable-search="true" data-enable-collected-all-notification="false" data-disabled-categories="["settings"]" data-enable-sidebar="false" data-map-controls="[[],["zoom","fullscreen"],["edit"],[]]" data-category-groups="[{"children":["scholars_landing","we_are_not","watchers_island","lake_veruna","galleria","doll_mausoleum","caves_of_academe","manipura_island","island_of_lorn","bleeding_earth"],"collapsed":"true","label":"Fragments"},{"children":["connla_sprout","dracroot","eevani","kovnik","saggen_pearl","silphsela","yao_shrub"],"collapsed":"true","label":"Resources"},{"children":["puzzle","puzzle_coop"],"collapsed":"true","label":"Puzzles"},{"children":["fishing","herding","game","shawzin"],"collapsed":"true","label":"Activities"}]" data-sort-markers="category" data-hidden-categories="["blinkpad","shop","cave","fishing","game","puzzle","puzzle_coop","shawzin","herding","connla_sprout","dracroot","eevani","kovnik","saggen_pearl","silphsela","yao_shrub","settings"]" data-collectible-expiry-time="-1" data-use-custom-popups="true" data-minimal-layout="true" data-collectible-categories="["scholars_landing","we_are_not","watchers_island","lake_veruna","galleria","doll_mausoleum","caves_of_academe","manipura_island","island_of_lorn","bleeding_earth"]" data-fullscreen-mode="window" data-enable-tooltips="true" data-enable-fullscreen="true">{{Map:Duviri Joy Spiral}}</div>'
			},
			{
				'Duviri Joy Spiral|Fragments|Yao Shrub',
				'<div data-icon-anchor="bottom-center" data-enable-search="true" data-enable-collected-all-notification="false" data-disabled-categories="["settings"]" data-enable-sidebar="false" data-map-controls="[[],["zoom","fullscreen"],["edit"],[]]" data-category-groups="[{"children":["scholars_landing","we_are_not","watchers_island","lake_veruna","galleria","doll_mausoleum","caves_of_academe","manipura_island","island_of_lorn","bleeding_earth"],"collapsed":"true","label":"Fragments"},{"children":["connla_sprout","dracroot","eevani","kovnik","saggen_pearl","silphsela","yao_shrub"],"collapsed":"true","label":"Resources"},{"children":["puzzle","puzzle_coop"],"collapsed":"true","label":"Puzzles"},{"children":["fishing","herding","game","shawzin"],"collapsed":"true","label":"Activities"}]" data-sort-markers="category" data-hidden-categories="["blinkpad","shop","cave","fishing","game","puzzle","puzzle_coop","shawzin","herding","connla_sprout","dracroot","eevani","kovnik","saggen_pearl","silphsela","settings"]" data-collectible-expiry-time="-1" data-use-custom-popups="true" data-minimal-layout="true" data-collectible-categories="["scholars_landing","we_are_not","watchers_island","lake_veruna","galleria","doll_mausoleum","caves_of_academe","manipura_island","island_of_lorn","bleeding_earth"]" data-fullscreen-mode="window" data-enable-tooltips="true" data-enable-fullscreen="true">{{Map:Duviri Joy Spiral}}</div>'
			},
			{
				'Duviri Joy Spiral|Fragments|Puzzles',
				'<div data-icon-anchor="bottom-center" data-enable-search="true" data-enable-collected-all-notification="false" data-disabled-categories="["settings"]" data-enable-sidebar="false" data-map-controls="[[],["zoom","fullscreen"],["edit"],[]]" data-category-groups="[{"children":["scholars_landing","we_are_not","watchers_island","lake_veruna","galleria","doll_mausoleum","caves_of_academe","manipura_island","island_of_lorn","bleeding_earth"],"collapsed":"true","label":"Fragments"},{"children":["connla_sprout","dracroot","eevani","kovnik","saggen_pearl","silphsela","yao_shrub"],"collapsed":"true","label":"Resources"},{"children":["puzzle","puzzle_coop"],"collapsed":"true","label":"Puzzles"},{"children":["fishing","herding","game","shawzin"],"collapsed":"true","label":"Activities"}]" data-sort-markers="category" data-hidden-categories="["blinkpad","shop","cave","fishing","game","shawzin","herding","connla_sprout","dracroot","eevani","kovnik","saggen_pearl","silphsela","yao_shrub","settings"]" data-collectible-expiry-time="-1" data-use-custom-popups="true" data-minimal-layout="true" data-collectible-categories="["scholars_landing","we_are_not","watchers_island","lake_veruna","galleria","doll_mausoleum","caves_of_academe","manipura_island","island_of_lorn","bleeding_earth"]" data-fullscreen-mode="window" data-enable-tooltips="true" data-enable-fullscreen="true">{{Map:Duviri Joy Spiral}}</div>'
			},
			{
				'Duviri Joy Spiral',
				'<div data-icon-anchor="bottom-center" data-enable-search="true" data-enable-collected-all-notification="false" data-disabled-categories="["settings"]" data-enable-sidebar="false" data-map-controls="[[],["zoom","fullscreen"],["edit"],[]]" data-category-groups="[{"children":["scholars_landing","we_are_not","watchers_island","lake_veruna","galleria","doll_mausoleum","caves_of_academe","manipura_island","island_of_lorn","bleeding_earth"],"collapsed":"true","label":"Fragments"},{"children":["connla_sprout","dracroot","eevani","kovnik","saggen_pearl","silphsela","yao_shrub"],"collapsed":"true","label":"Resources"},{"children":["puzzle","puzzle_coop"],"collapsed":"true","label":"Puzzles"},{"children":["fishing","herding","game","shawzin"],"collapsed":"true","label":"Activities"}]" data-sort-markers="category" data-hidden-categories="[""]" data-collectible-expiry-time="-1" data-use-custom-popups="true" data-minimal-layout="true" data-collectible-categories="["scholars_landing","we_are_not","watchers_island","lake_veruna","galleria","doll_mausoleum","caves_of_academe","manipura_island","island_of_lorn","bleeding_earth"]" data-fullscreen-mode="window" data-enable-tooltips="true" data-enable-fullscreen="true">{{Map:Duviri Joy Spiral}}</div>'
			},
			{
				'Duviri Joy Spiral|Non-existant Category',
				'<div data-icon-anchor="bottom-center" data-enable-search="true" data-enable-collected-all-notification="false" data-disabled-categories="["settings"]" data-enable-sidebar="false" data-map-controls="[[],["zoom","fullscreen"],["edit"],[]]" data-category-groups="[{"children":["scholars_landing","we_are_not","watchers_island","lake_veruna","galleria","doll_mausoleum","caves_of_academe","manipura_island","island_of_lorn","bleeding_earth"],"collapsed":"true","label":"Fragments"},{"children":["connla_sprout","dracroot","eevani","kovnik","saggen_pearl","silphsela","yao_shrub"],"collapsed":"true","label":"Resources"},{"children":["puzzle","puzzle_coop"],"collapsed":"true","label":"Puzzles"},{"children":["fishing","herding","game","shawzin"],"collapsed":"true","label":"Activities"}]" data-sort-markers="category" data-hidden-categories="[""]" data-collectible-expiry-time="-1" data-use-custom-popups="true" data-minimal-layout="true" data-collectible-categories="["scholars_landing","we_are_not","watchers_island","lake_veruna","galleria","doll_mausoleum","caves_of_academe","manipura_island","island_of_lorn","bleeding_earth"]" data-fullscreen-mode="window" data-enable-tooltips="true" data-enable-fullscreen="true">{{Map:Duviri Joy Spiral}}</div>'
			},
			{
				'Duviri Joy Spiral|Non-existant Category|Yao Shrub',
				'<div data-icon-anchor="bottom-center" data-enable-search="true" data-enable-collected-all-notification="false" data-disabled-categories="["settings"]" data-enable-sidebar="false" data-map-controls="[[],["zoom","fullscreen"],["edit"],[]]" data-category-groups="[{"children":["scholars_landing","we_are_not","watchers_island","lake_veruna","galleria","doll_mausoleum","caves_of_academe","manipura_island","island_of_lorn","bleeding_earth"],"collapsed":"true","label":"Fragments"},{"children":["connla_sprout","dracroot","eevani","kovnik","saggen_pearl","silphsela","yao_shrub"],"collapsed":"true","label":"Resources"},{"children":["puzzle","puzzle_coop"],"collapsed":"true","label":"Puzzles"},{"children":["fishing","herding","game","shawzin"],"collapsed":"true","label":"Activities"}]" data-sort-markers="category" data-hidden-categories="["blinkpad","shop","cave","fishing","game","puzzle","puzzle_coop","shawzin","herding","connla_sprout","dracroot","eevani","kovnik","saggen_pearl","silphsela","scholars_landing","we_are_not","watchers_island","lake_veruna","galleria","doll_mausoleum","caves_of_academe","manipura_island","island_of_lorn","bleeding_earth","settings"]" data-collectible-expiry-time="-1" data-use-custom-popups="true" data-minimal-layout="true" data-collectible-categories="["scholars_landing","we_are_not","watchers_island","lake_veruna","galleria","doll_mausoleum","caves_of_academe","manipura_island","island_of_lorn","bleeding_earth"]" data-fullscreen-mode="window" data-enable-tooltips="true" data-enable-fullscreen="true">{{Map:Duviri Joy Spiral}}</div>'
			},
			{
				'Duviri Joy Spiral|None',
				'<div data-icon-anchor="bottom-center" data-enable-search="true" data-enable-collected-all-notification="false" data-disabled-categories="["settings"]" data-enable-sidebar="false" data-map-controls="[[],["zoom","fullscreen"],["edit"],[]]" data-category-groups="[{"children":["scholars_landing","we_are_not","watchers_island","lake_veruna","galleria","doll_mausoleum","caves_of_academe","manipura_island","island_of_lorn","bleeding_earth"],"collapsed":"true","label":"Fragments"},{"children":["connla_sprout","dracroot","eevani","kovnik","saggen_pearl","silphsela","yao_shrub"],"collapsed":"true","label":"Resources"},{"children":["puzzle","puzzle_coop"],"collapsed":"true","label":"Puzzles"},{"children":["fishing","herding","game","shawzin"],"collapsed":"true","label":"Activities"}]" data-sort-markers="category" data-hidden-categories="["blinkpad","shop","cave","fishing","game","puzzle","puzzle_coop","shawzin","herding","connla_sprout","dracroot","eevani","kovnik","saggen_pearl","silphsela","yao_shrub","scholars_landing","we_are_not","watchers_island","lake_veruna","galleria","doll_mausoleum","caves_of_academe","manipura_island","island_of_lorn","bleeding_earth","settings"]" data-collectible-expiry-time="-1" data-use-custom-popups="true" data-minimal-layout="true" data-collectible-categories="["scholars_landing","we_are_not","watchers_island","lake_veruna","galleria","doll_mausoleum","caves_of_academe","manipura_island","island_of_lorn","bleeding_earth"]" data-fullscreen-mode="window" data-enable-tooltips="true" data-enable-fullscreen="true">{{Map:Duviri Joy Spiral}}</div>'
			},
			{
				'Duviri Joy Spiral|None|Yao Shrub',
				'<div data-icon-anchor="bottom-center" data-enable-search="true" data-enable-collected-all-notification="false" data-disabled-categories="["settings"]" data-enable-sidebar="false" data-map-controls="[[],["zoom","fullscreen"],["edit"],[]]" data-category-groups="[{"children":["scholars_landing","we_are_not","watchers_island","lake_veruna","galleria","doll_mausoleum","caves_of_academe","manipura_island","island_of_lorn","bleeding_earth"],"collapsed":"true","label":"Fragments"},{"children":["connla_sprout","dracroot","eevani","kovnik","saggen_pearl","silphsela","yao_shrub"],"collapsed":"true","label":"Resources"},{"children":["puzzle","puzzle_coop"],"collapsed":"true","label":"Puzzles"},{"children":["fishing","herding","game","shawzin"],"collapsed":"true","label":"Activities"}]" data-sort-markers="category" data-hidden-categories="["blinkpad","shop","cave","fishing","game","puzzle","puzzle_coop","shawzin","herding","connla_sprout","dracroot","eevani","kovnik","saggen_pearl","silphsela","yao_shrub","scholars_landing","we_are_not","watchers_island","lake_veruna","galleria","doll_mausoleum","caves_of_academe","manipura_island","island_of_lorn","bleeding_earth","settings"]" data-collectible-expiry-time="-1" data-use-custom-popups="true" data-minimal-layout="true" data-collectible-categories="["scholars_landing","we_are_not","watchers_island","lake_veruna","galleria","doll_mausoleum","caves_of_academe","manipura_island","island_of_lorn","bleeding_earth"]" data-fullscreen-mode="window" data-enable-tooltips="true" data-enable-fullscreen="true">{{Map:Duviri Joy Spiral}}</div>'
			},
			{
				'Duviri Joy Spiral|Yao Shrub|None',
				'<div data-icon-anchor="bottom-center" data-enable-search="true" data-enable-collected-all-notification="false" data-disabled-categories="["settings"]" data-enable-sidebar="false" data-map-controls="[[],["zoom","fullscreen"],["edit"],[]]" data-category-groups="[{"children":["scholars_landing","we_are_not","watchers_island","lake_veruna","galleria","doll_mausoleum","caves_of_academe","manipura_island","island_of_lorn","bleeding_earth"],"collapsed":"true","label":"Fragments"},{"children":["connla_sprout","dracroot","eevani","kovnik","saggen_pearl","silphsela","yao_shrub"],"collapsed":"true","label":"Resources"},{"children":["puzzle","puzzle_coop"],"collapsed":"true","label":"Puzzles"},{"children":["fishing","herding","game","shawzin"],"collapsed":"true","label":"Activities"}]" data-sort-markers="category" data-hidden-categories="["blinkpad","shop","cave","fishing","game","puzzle","puzzle_coop","shawzin","herding","connla_sprout","dracroot","eevani","kovnik","saggen_pearl","silphsela","yao_shrub","scholars_landing","we_are_not","watchers_island","lake_veruna","galleria","doll_mausoleum","caves_of_academe","manipura_island","island_of_lorn","bleeding_earth","settings"]" data-collectible-expiry-time="-1" data-use-custom-popups="true" data-minimal-layout="true" data-collectible-categories="["scholars_landing","we_are_not","watchers_island","lake_veruna","galleria","doll_mausoleum","caves_of_academe","manipura_island","island_of_lorn","bleeding_earth"]" data-fullscreen-mode="window" data-enable-tooltips="true" data-enable-fullscreen="true">{{Map:Duviri Joy Spiral}}</div>'
			}
		}
	}
}
