return {
	Animals = {
		["Alpine Monitor Sawgaw"] = {
			Call = "SawgawCall.ogg",
			Codex = "Soar Gore' as the Solaris call it, this crimson-faced bird of prey circles and stalks the cliffs and fungal groves of Venus, searching for rodent prey.",
			CodexScans = 20,
			Faction = "Predator",
			Family = "Sawgaw",
			Armor = 50,
			Health = 6,
			FullImg = "SnowBirdUncommon.png",
			Image = "SnowBirdUncommon.png",
			Intro = "Sawgaws are a flying species, making them difficult to capture until they land somewhere. They usually prefer to perch on top of the giant mushrooms. ",
			Introduced = "24.2",
			MaxAge = { Month = 3, Year = 12 },
			MaxWeight = 5.4,
			MinAge = { Month = 3, Year = 0 },
			MinWeight = 1.1,
			Notes = "A rare Sawgaw subspecies. Tougher and stronger, Alpine Monitor Sawgaws will often assume the role of alphas over the other subspecies in the wild. They are highly valued as exotic 'pets' by [[Corpus]] nobility, though 'prisoners' may be a more appropriate term.",
			Origin = "Orb Vallis",
			Rarity = "Uncommon",
			Reward = "Solaris United Standing",
			Standing = 600,
			TranqsNeeded = 1 
		},
		["Amethyst Nexifera"] = {
			Call = "NexiferaPlayerLureCall.ogg",
			Codex = "A distinctly Deimosian grotesquerie that attacks it opponents from above.",
			CodexScans = 20,
			Faction = "Prey",
			Family = "Nexifera",
			Armor = 50,
			Health = 1000,
			FullImg = "AmethystNexifera.png",
			Image = "AmethystNexifera.png",
			Intro = "Nexifera can't be lured out via the normal Track and Tranq process.<br>They only spawn naturally in big caves near the Catabolic Gutter hanging from the ceiling.<br>Their hard lower exterior block all Tranq-Shots.<br>Additionally, They are 75% resistant to all Warframe abilities. Meaning all Duration gets quartered. Their resistance can accumulate, causing consecutive use of the same ability to have even less duration, eventually becoming outright immune.",
			Introduced = "29.5",
			MaxAge = { Month = 2, Year = 1 },
			MaxWeight = 0.44,
			MinAge = { Month = 9, Year = 0 },
			MinWeight = 0.17,
			Notes = "Nexifera spawn yellow-green goo below themselves. If anything steps on it they dive down and deal damage with the resulting shockwave.",
			Origin = "Cambion Drift",
			Rarity = "Common",
			Reward = "",
			Standing = 0,
			TranqsNeeded = 1 
		},
		["Ashen Kuaka"] = {
			Call = "ForestRodentPlayerLureCall.ogg",
			Codex = "A timid rodent that is easily frightened.",
			CodexScans = 20,
			Faction = "Prey",
			Family = "Kuaka",
			Armor = 50,
			Health = 1,
			FullImg = "KuakaUncommon.png",
			Image = "KuakaUncommon.png",
			Intro = "Kuaka notably appear in groups of three.",
			Introduced = "22.0",
			MaxAge = { Month = 0, Year = 0 },
			MaxWeight = 0,
			MinAge = { Month = 0, Year = 0 },
			MinWeight = 0,
			Notes = "A rare Kuaka subspecies. They dislike light and have adapted to living underground.",
			Origin = "Plains of Eidolon",
			Rarity = "Uncommon",
			Reward = "Ostron Standing",
			Standing = 300,
			TranqsNeeded = 1 
		},
		["Bau Vasca Kavat"] = {
			Call = "KavatVascaPlayerLureCall.ogg",
			Codex = "The Vasca strain is a symbiotic blood-borne virus transmitted via the saliva of infected kavats. Existing solely to propagate itself the virus makes the host increasingly dependent upon the ingestion of blood, thereby spreading itself further and faster through the population. Vasca-infected kavats, over time, lose all sense of themselves becoming increasingly cunning, violent and ravenous.",
			CodexScans = 20,
			Faction = "Predator",
			Family = "Vasca Kavat",
			Armor = 175,
			Health = 300,
			FullImg = "VascaKavatUncommon.png",
			Image = "VascaKavatUncommon.png",
			Intro = "Vasca Kavats only appear during nighttime in the Plains of Eidolon. <br><br>When roaming, Vasca Kavats will appear in groups of three, but when called from a calling point only one will spawn.",
			Introduced = "26.0",
			MaxAge = { Month = 0, Year = 0 },
			MaxWeight = 0,
			MinAge = { Month = 0, Year = 0 },
			MinWeight = 0,
			Notes = "A rare Vasca Kavat subspecies.",
			Origin = "Plains of Eidolon",
			Rarity = "Uncommon",
			Reward = "Ostron Standing",
			Standing = 500,
			TranqsNeeded = 1 
		},
		["Black-Banded Bolarola"] = {
			Call = "BolarolaCall.ogg",
			Codex = "Favoring thunder, lightning and cratered-out areas Bolarolas are all about defense. Their armored plates protect them from most predators, tucking-and-rolling to make good their escape.",
			CodexScans = 20,
			Faction = "Neutral",
			Family = "Bolarola",
			Armor = 50,
			Health = 6,
			FullImg = "BolarolaUncommon.png",
			Image = "BolarolaUncommon.png",
			Intro = "Bolarolas are covered in an armored plating that neutralizes tranquilizing shots. Only their underbellies are vulnerable, and they will occasionally lean back to expose this weakness. Should they sense danger they will curl up to shield themselves, and when fleeing they will roll away. ",
			Introduced = "24.0",
			MaxAge = { Month = 5, Year = 8 },
			MaxWeight = 19.7,
			MinAge = { Month = 5, Year = 0 },
			MinWeight = 7.5,
			Notes = "A rare Bolarola subspecies. Their black plates are said to be used in Grineer formal wear.",
			Origin = "Orb Vallis",
			Rarity = "Uncommon",
			Reward = "Solaris United Standing",
			Standing = 750,
			TranqsNeeded = 1 
		},
		["Brindle Kubrodon"] = {
			Call = "KubrodonCall.ogg",
			Codex = "The apex predator of the Venusian plains. These massively framed beasts travel in groups and mark the territory surrounding Orokin cooling towers as their own. Kubrodons are a danger best avoided.",
			CodexScans = 20,
			Faction = "Neutral",
			Family = "Kubrodon",
			Armor = 50,
			Health = 1000,
			FullImg = "KubrodonCommon.png",
			Image = "KubrodonCommon.png",
			Intro = "True to its status as the apex predator, the Kubrodon's more acute sense of smell allows them to locate their pursuers, and will use a ramming attack to make good their escape. Must be shot twice with the Tranq Rifle to be brought down. <br><br>Additionally, Kubrodons are 75% resistant to all Warframe abilities. For example, when using {{WF|Ivara}}’s [[Quiver|Sleep Arrow]] to put a Kubrodon to sleep, the [[Ability Duration]] will be a quarter (1/4) of its full duration (Ivara’s Sleep Arrow with Maximized Ability Duration: 30.6 seconds ÷ 4 = 7.65 seconds). Their resistance can accumulate, causing consecutive use of the same ability to have even less duration, eventually becoming outright immune.<br><br>Despite being mentioned to travel in groups, only one Kubrodon will respond to the lure's call.",
			Introduced = "24.0",
			MaxAge = { Month = 0, Year = 0 },
			MaxWeight = 0,
			MinAge = { Month = 0, Year = 0 },
			MinWeight = 0,
			Notes = "A common Kubrodon subspecies.",
			Origin = "Orb Vallis",
			Rarity = "Common",
			Reward = "Solaris United Standing",
			Standing = 1000,
			TranqsNeeded = 2 
		},
		["Burrowing Cryptilex"] = {
			Call = "CryptilexPlayerLureCall.ogg",
			Codex = "The most abundant variety of Cryptilex, this aggressive insect will slash anything it deems a threat.",
			CodexScans = 20,
			Faction = "Prey",
			Family = "Cryptilex",
			Armor = 50,
			Health = 1,
			FullImg = "BurrowingCryptilex.png",
			Image = "BurrowingCryptilex.png",
			Introduced = "29.0",
			MaxAge = { Month = 3, Year = 1 },
			MaxWeight = 0.09,
			MinAge = { Month = 10, Year = 0 },
			MinWeight = 0.02,
			Notes = "A common Cryptilex subspecies.",
			Origin = "Cambion Drift",
			Rarity = "Common",
			Reward = "",
			Standing = 0,
			TranqsNeeded = 1 
		},
		["Caustic Cryptilex"] = {
			Call = "CryptilexPlayerLureCall.ogg",
			Codex = "The most dangerous Cryptilex. They have glands in their abdomens that can emit an acidic spray.",
			CodexScans = 20,
			Faction = "Prey",
			Family = "Cryptilex",
			Armor = 50,
			Health = 1,
			FullImg = "CausticCryptilex.png",
			Image = "CausticCryptilex.png",
			Introduced = "29.0",
			MaxAge = { Month = 2, Year = 1 },
			MaxWeight = 0.08,
			MinAge = { Month = 9, Year = 0 },
			MinWeight = 0.02,
			Notes = "A very rare Cryptilex subspecies.",
			Origin = "Cambion Drift",
			Rarity = "Rare",
			Reward = "",
			Standing = 0,
			TranqsNeeded = 1 
		},
		["Coastal Mergoo"] = {
			Call = "OstronSeaBirdPlayerLureCall.ogg",
			Codex = "An avian of ridiculous appearance found along coastal regions and around large bodies of water. Mergoo circle and squawk at the sight of marine predators. Many an Ostron fisher owes their lives to these odd little birds. Killing one is considered very bad luck.",
			CodexScans = 20,
			Faction = "Prey",
			Family = "Mergoo",
			Armor = 50,
			Health = 1,
			FullImg = "MergooCommon.png",
			Image = "MergooCommon.png",
			Intro = "Like Condrocs, Mergoo are a flying species, making them difficult to capture until they land at the calling point.",
			Introduced = "24.6",
			MaxAge = { Month = 0, Year = 0 },
			MaxWeight = 0,
			MinAge = { Month = 0, Year = 0 },
			MinWeight = 0,
			Notes = "A common Mergoo subspecies.",
			Origin = "Plains of Eidolon",
			Rarity = "Common",
			Reward = "Ostron Standing",
			Standing = 600,
			TranqsNeeded = 1 
		},
		["Common Avichaea"] = {
			Call = "AvichaeaPlayerLureCall.ogg",
			Codex = "A prehistoric bird-like creature that often congregates in small groups.",
			CodexScans = 20,
			Faction = "Prey",
			Family = "Avichaea",
			Armor = 50,
			Health = 1,
			FullImg = "CommonAvichaea.png",
			Image = "CommonAvichaea.png",
			Intro = "A common Avichaea subspecies.",
			Introduced = "29.0",
			MaxAge = { Month = 3, Year = 1 },
			MaxWeight = 5.1,
			MinAge = { Month = 11, Year = 0 },
			MinWeight = 1.2,
			Origin = "Cambion Drift",
			Rarity = "Common",
			Reward = "",
			Standing = 0,
			TranqsNeeded = 1 
		},
		["Common Condroc"] = {
			Call = "BirdOfPreyPlayerLureCall.ogg",
			Codex = "A carrion-eater and opportunistic bird-of-prey. Condrocs gather, feed upon carrion, and occasionally, hunt in groups known as 'committees'. Several committees will be led by an Emperor.",
			CodexScans = 20,
			Faction = "Predator",
			Family = "Condroc",
			Armor = 50,
			Health = 6,
			FullImg = "CondrocCommon.png",
			Image = "CondrocCommon.png",
			Intro = "When roaming, Condrocs will appear in groups of two or three and are already stationed on the ground, but when called from a calling point only one will spawn. <br><br>Condrocs are a flying species, making them difficult to capture until they land at the calling point.",
			Introduced = "22.0",
			MaxAge = { Month = 0, Year = 0 },
			MaxWeight = 0,
			MinAge = { Month = 0, Year = 0 },
			MinWeight = 0,
			Notes = "A common Condroc subspecies.",
			Origin = "Plains of Eidolon",
			Rarity = "Common",
			Reward = "Ostron Standing",
			Standing = 400,
			TranqsNeeded = 1 
		},
		["Crescent Vulpaphyla"] = {
			Call = "VulpaphylaPlayerLureCall.ogg",
			Codex = "The Crescent is the most pugnacious subspecies of Vulpaphyla, they will rush anything they perceive as a threat.",
			CodexScans = 20,
			Faction = "Predator",
			Family = "Vulpaphyla",
			Armor = 100,
			Health = 100,
			FullImg = "CrescentVulpaphyla.png",
			Image = "CrescentVulpaphyla.png",
			Intro = "A rare Vulpaphyla subspecies that prefers  [[Vome (Deimos)|Vome]] appearing almost exclusively during its phase.<br>[[Vulpaphyla (Conservation)|Vulpaphylas]] can be attacked by the Infested before or after sedating, causing them to become ''Weakened''. Capturing a Vulpaphyla in this state allows them to be used as a modular [[Companion]] through a process called Revivification with [[Son]].",
			Introduced = "29.0",
			MaxAge = { Month = 2, Year = 1 },
			MaxWeight = 14.5,
			MinAge = { Month = 2, Year = 1 },
			MinWeight = 14.5,
			Notes = "Vulpaphyla Scat marks the track alongside their footprints.",
			Origin = "Cambion Drift",
			Rarity = "Uncommon",
			Reward = "",
			Standing = 0,
			TranqsNeeded = 1 
		},
		["Dappled Horrasque"] = {
			Call = "HorrasqueCall.ogg",
			Codex = "This hideous creature is terrible to behold but will not attack unless provoked. When it does, its roar will shake the bowels of even the most steadfast tracker.",
			CodexScans = 20,
			Faction = "Predator",
			Family = "Horrasque",
			Armor = 50,
			Health = 22,
			FullImg = "HorrasqueCommon.png",
			Image = "HorrasqueCommon.png",
			Intro = "Between the starting point and the calling point, a trail of {{D|Toxin}} damaging scat will line next to their footprints. <br><br>Horrasques will crawl underground, periodically exposing their heads. If they reach the calling point they will surface and expose their whole body, making perfect captures much easier. Must be shot '''two times''' with the Tranq Rifle to be brought down.",
			Introduced = "24.2",
			MaxAge = { Month = 0, Year = 0 },
			MaxWeight = 0,
			MinAge = { Month = 0, Year = 0 },
			MinWeight = 0,
			Notes = "A very rare Bolarola subspecies. Their spines have evolved into thorn-like barbs that give them an even greater defense.",
			Origin = "Orb Vallis",
			Rarity = "Common",
			Reward = "Solaris United Standing",
			Standing = 600,
			TranqsNeeded = 2 
		},
		["Delicate Pobber"] = {
			Call = "PobberCall.ogg",
			Codex = "Native to the fungal forests of Venus, the Pobber is a skittish rodent possessed of an objectionable odor. Always found in groups they flee at the slightest hint of trouble. They are a primary food source of [[Virmink]] and [[Sawgaw]].",
			CodexScans = 20,
			Faction = "Prey",
			Family = "Pobber",
			Armor = 50,
			Health = 2,
			FullImg = "PobberUncommon.png",
			Image = "PobberUncommon.png",
			Intro = "Pobbers notably appear in groups of three.",
			Introduced = "24.0",
			MaxAge = { Month = 10, Year = 1 },
			MaxWeight = 0.07,
			MinAge = { Month = 3, Year = 0 },
			MinWeight = 0.02,
			Notes = "A rare Pobber subspecies. Due to being directly descended from domesticated pets, Delicate Pobbers are weaker and, incidentally, not encountered as much as other pobbers. They also lack their species signature repulsive smell, making them potentially good pets.",
			Origin = "Orb Vallis",
			Rarity = "Uncommon",
			Reward = "Solaris United Standing",
			Standing = 300,
			TranqsNeeded = 1 
		},
		["Dusky-Headed Virmink"] = {
			Call = "VirminkCall.ogg",
			Codex = "Sleek and silky, the adorable appearance of the Venusian Virmink belies its aggressive demeanor. Favoring rocky landscapes Virmink packs nose the air, scenting for Pobbers - their primary food source.",
			CodexScans = 20,
			Faction = "Predator",
			Family = "Virmink",
			Armor = 50,
			Health = 6,
			FullImg = "VirminkUncommon.png",
			Image = "VirminkUncommon.png",
			Introduced = "24.0",
			MaxAge = { Month = 4, Year = 7 },
			MaxWeight = 19,
			MinAge = { Month = 2, Year = 0 },
			MinWeight = 9.3,
			Notes = "A rare Virmink subspecies. Their pelts are favored by the [[Corpus]].",
			Origin = "Orb Vallis",
			Rarity = "Uncommon",
			Reward = "Solaris United Standing",
			Standing = 400,
			TranqsNeeded = 1 
		},
		["Emperor Condroc"] = {
			Call = "BirdOfPreyPlayerLureCall.ogg",
			Codex = "A carrion-eater and opportunistic bird-of-prey. Condrocs gather, feed upon carrion, and occasionally, hunt in groups known as 'committees'. Several committees will be led by an Emperor.",
			CodexScans = 20,
			Faction = "Predator",
			Family = "Condroc",
			Armor = 50,
			Health = 6,
			FullImg = "CondrocRare.png",
			Image = "CondrocRare.png",
			Intro = "When roaming, Condrocs will appear in groups of two or three and are already stationed on the ground, but when called from a calling point only one will spawn. <br><br>Condrocs are a flying species, making them difficult to capture until they land at the calling point.",
			Introduced = "22.0",
			MaxAge = { Month = 0, Year = 0 },
			MaxWeight = 0,
			MinAge = { Month = 0, Year = 0 },
			MinWeight = 0,
			Notes = "A very rare Condroc subspecies. Commands a number of Condroc committees.",
			Origin = "Plains of Eidolon",
			Rarity = "Rare",
			Reward = "Ostron Standing",
			Standing = 900,
			TranqsNeeded = 1 
		},
		["Fire-Veined Stover"] = {
			Call = "StoverCall.ogg",
			Codex = "The Stover is a kind of proto-Kubrow that resurrected when Venus thawed. When grouped in a pack, Stovers are relentless opponents.",
			CodexScans = 20,
			Faction = "Predator",
			Family = "Stover",
			Armor = 50,
			Health = 200,
			FullImg = "StoverRare.png",
			Image = "StoverRare.png",
			Intro = "Stovers make their appearances within caves, whose narrow passageways make confrontation almost unavoidable. Instead of immediately fleeing, they will viciously attack their pursuers. Must be shot '''Two times''' with the Tranq Rifle to be brought down.",
			Introduced = "24.2",
			MaxAge = { Month = 0, Year = 0 },
			MaxWeight = 0,
			MinAge = { Month = 0, Year = 0 },
			MinWeight = 0,
			Notes = "A very rare Stover subspecies. Often being referred to as 'majestic'.",
			Origin = "Orb Vallis",
			Rarity = "Rare",
			Reward = "Solaris United Standing",
			Standing = 3200,
			TranqsNeeded = 2 
		},
		["Flossy Sawgaw"] = {
			Call = "SawgawCall.ogg",
			Codex = "Soar Gore' as the Solaris call it, this crimson-faced bird of prey circles and stalks the cliffs and fungal groves of Venus, searching for rodent prey.",
			CodexScans = 20,
			Faction = "Predator",
			Family = "Sawgaw",
			Armor = 50,
			Health = 6,
			FullImg = "SnowBirdCommon.png",
			Image = "SnowBirdCommon.png",
			Intro = "Sawgaws are a flying species, making them difficult to capture until they land somewhere. They usually prefer to perch on top of the giant mushrooms. ",
			Introduced = "24.2",
			MaxAge = { Month = 6, Year = 9 },
			MaxWeight = 4.8,
			MinAge = { Month = 3, Year = 0 },
			MinWeight = 1.3,
			Notes = "A common Sawgaw subspecies. Possessing vibrant white feathers, the Flossy Sawgaw is perfectly suited to life on the snowy planets. Their feathers are also allegedly far softer than the other subspecies' and are at times hunted for them, but not to the point of extinction.",
			Origin = "Orb Vallis",
			Rarity = "Common",
			Reward = "Solaris United Standing",
			Standing = 400,
			TranqsNeeded = 1 
		},
		["Frogmouthed Sawgaw"] = {
			Call = "SawgawCall.ogg",
			Codex = "Soar Gore' as the Solaris call it, this crimson-faced bird of prey circles and stalks the cliffs and fungal groves of Venus, searching for rodent prey.",
			CodexScans = 20,
			Faction = "Predator",
			Family = "Sawgaw",
			Armor = 50,
			Health = 6,
			FullImg = "SnowBirdRare.png",
			Image = "SnowBirdRare.png",
			Intro = "Sawgaws are a flying species, making them difficult to capture until they land somewhere. They usually prefer to perch on top of the giant mushrooms. ",
			Introduced = "24.2",
			MaxAge = { Month = 7, Year = 11 },
			MaxWeight = 5.5,
			MinAge = { Month = 3, Year = 0 },
			MinWeight = 1.2,
			Notes = "A very rare Sawgaw subspecies. Whilst the Frogmouthed Sawgaw is largely thought to have been extinct for hundreds of years, some do still exist in the wilds across the system, if barely. This rarity has only caused the short-sighted Corpus to hunt them for trophies.",
			Origin = "Orb Vallis",
			Rarity = "Rare",
			Reward = "Solaris United Standing",
			Standing = 900,
			TranqsNeeded = 1 
		},
		["Fuming Dax Stover"] = {
			Call = "StoverCall.ogg",
			Codex = "The Stover is a kind of proto-Kubrow that resurrected when Venus thawed. When grouped in a pack, Stovers are relentless opponents.",
			CodexScans = 20,
			Faction = "Predator",
			Family = "Stover",
			Armor = 50,
			Health = 200,
			FullImg = "StoverUncommon.png",
			Image = "StoverUncommon.png",
			Intro = "Stovers make their appearances within caves, whose narrow passageways make confrontation almost unavoidable. Instead of immediately fleeing, they will viciously attack their pursuers. Must be shot '''Two times''' with the Tranq Rifle to be brought down.",
			Introduced = "24.2",
			MaxAge = { Month = 0, Year = 0 },
			MaxWeight = 0,
			MinAge = { Month = 0, Year = 0 },
			MinWeight = 0,
			Notes = "A rare Stover subspecies. Often intimidates any other Stovers due to bossy behavior.",
			Origin = "Orb Vallis",
			Rarity = "Uncommon",
			Reward = "Solaris United Standing",
			Standing = 1600,
			TranqsNeeded = 2 
		},
		["Ghost Kuaka"] = {
			Call = "ForestRodentPlayerLureCall.ogg",
			Codex = "A timid rodent that is easily frightened.",
			CodexScans = 20,
			Faction = "Prey",
			Family = "Kuaka",
			Armor = 50,
			Health = 1,
			FullImg = "KuakaRare.png",
			Image = "KuakaRare.png",
			Intro = "Kuaka notably appear in groups of three.",
			Introduced = "22.0",
			MaxAge = { Month = 0, Year = 0 },
			MaxWeight = 0,
			MinAge = { Month = 0, Year = 0 },
			MinWeight = 0,
			Notes = "A very rare Kuaka subspecies. Named for their rarity and preponderance for disappearing, and almost never visit the surface.",
			Origin = "Plains of Eidolon",
			Rarity = "Rare",
			Reward = "Ostron Standing",
			Standing = 600,
			TranqsNeeded = 1 
		},
		["Green Velocipod"] = {
			Call = "VelocipodCall.ogg",
			Codex = "This large arthropod is generally found flying around Deimos' several grottos.",
			CodexScans = 20,
			Faction = "Prey",
			Family = "Velocipod",
			Armor = 125,
			Health = 300,
			FullImg = "GreenVelocipodK-DriveSkin.png",
			Image = "GreenVelocipodK-DriveSkin.png",
			Intro = "Found in the ''Swamp'', meaning in the center of [[Cambion Drift]]",
			Introduced = "29.0",
			MaxAge = { Month = 1, Year = 1 },
			MaxWeight = 0.01,
			MinAge = { Month = 10, Year = 0 },
			MinWeight = 0.01,
			Notes = "A common, green Velocipod subspecies.<br>Green Velocipods appear to spawn more likely in the south-west.",
			Origin = "Cambion Drift",
			Rarity = "Uncommon",
			Reward = "",
			Standing = 0,
			TranqsNeeded = 1 
		},
		["Horrasque Stormer"] = {
			Call = "HorrasqueCall.ogg",
			Codex = "This hideous creature is terrible to behold but will not attack unless provoked. When it does, its roar will shake the bowels of even the most steadfast tracker.",
			CodexScans = 20,
			Faction = "Predator",
			Family = "Horrasque",
			Armor = 50,
			Health = 22,
			FullImg = "HorrasqueRare.png",
			Image = "HorrasqueRare.png",
			Intro = "Between the starting point and the calling point, a trail of {{D|Toxin}} damaging scat will line next to their footprints. <br><br>Horrasques will crawl underground, periodically exposing their heads. If they reach the calling point they will surface and expose their whole body, making perfect captures much easier. Must be shot '''two times''' with the Tranq Rifle to be brought down.",
			Introduced = "24.2",
			MaxAge = { Month = 0, Year = 0 },
			MaxWeight = 0,
			MinAge = { Month = 0, Year = 0 },
			MinWeight = 0,
			Notes = "A very rare Horrasque subspecies. Hunted to near extinction due to the insulating properties of their hide.",
			Origin = "Orb Vallis",
			Rarity = "Rare",
			Reward = "Solaris United Standing",
			Standing = 1800,
			TranqsNeeded = 2 
		},
		["Howler Undazoa"] = {
			Call = "UndazoaPlayerLureCall.ogg",
			Codex = "The Howler is easily startled. Its penetrating scream will cause other, more dangerous animals to investigate.",
			CodexScans = 20,
			Faction = "Prey",
			Family = "Undazoa",
			Armor = 50,
			Health = 22,
			FullImg = "HowlerUndazoa.png",
			Image = "HowlerUndazoa.png",
			Intro = "A rare Undazoa subspecies that prefers [[Vome (Deimos)|Vome]] appearing almost exclusively during its phase.<br>Undazoa approach the Call-Point in the Exocrine, [[Cambion Drift|Cambion Drifts]] river-like formations.",
			Introduced = "29.5",
			MaxAge = { Month = 8, Year = 44 },
			MaxWeight = 59.7,
			MinAge = { Month = 0, Year = 14 },
			MinWeight = 54.7,
			Notes = "Undazoa Scat marks the track alongside their footprints.",
			Origin = "Cambion Drift",
			Rarity = "Rare",
			Reward = "",
			Standing = 0,
			TranqsNeeded = 2 
		},
		["Kubrodon Incarnadine"] = {
			Call = "KubrodonCall.ogg",
			Codex = "The apex predator of the Venusian plains. These massively framed beasts travel in groups and mark the territory surrounding Orokin cooling towers as their own. Kubrodons are a danger best avoided.",
			CodexScans = 20,
			Faction = "Neutral",
			Family = "Kubrodon",
			Armor = 50,
			Health = 1000,
			FullImg = "KubrodonRare.png",
			Image = "KubrodonRare.png",
			Intro = "True to its status as the apex predator, the Kubrodon's more acute sense of smell allows them to locate their pursuers, and will use a ramming attack to make good their escape. Must be shot twice with the Tranq Rifle to be brought down. <br><br>Additionally, Kubrodons are 75% resistant to all Warframe abilities. For example, when using {{WF|Ivara}}’s [[Quiver|Sleep Arrow]] to put a Kubrodon to sleep, the [[Ability Duration]] will be a quarter (1/4) of its full duration (Ivara’s Sleep Arrow with Maximized Ability Duration: 30.6 seconds ÷ 4 = 7.65 seconds). Their resistance can accumulate, causing consecutive use of the same ability to have even less duration, eventually becoming outright immune.<br><br>Despite being mentioned to travel in groups, only one Kubrodon will respond to the lure's call.",
			Introduced = "24.0",
			MaxAge = { Month = 0, Year = 0 },
			MaxWeight = 0,
			MinAge = { Month = 0, Year = 0 },
			MinWeight = 0,
			Notes = "A very rare Kubrodon subspecies. Feared across the Orb Vallis, they are possessed of a particular malevolence, a dark intelligence, and kill not for survival, but solely for the sake of pleasure.",
			Origin = "Orb Vallis",
			Rarity = "Rare",
			Reward = "Solaris United Standing",
			Standing = 4000,
			TranqsNeeded = 2 
		},
		["Medjay Predasite"] = {
			Call = "PredasitePlayerLureCall.ogg",
			Codex = "Not quite as flighty as its subspecies cousins, it will charge if it feels threatened. Active only while Vome watches over the Cambion Drift.",
			CodexScans = 20,
			Faction = "Predator",
			Family = "Predasite",
			Armor = 50,
			Health = 500,
			FullImg = "MedjayPredasite.png",
			Image = "MedjayPredasite.png",
			Intro = "Predasites can be attacked by the Infested before or after sedating, causing them to become ''Weakened''. Capturing a Predasite in this state allows them to be used as a modular [[Companion]] through a process called Revivification with [[Son]]<br>A rare Predasite subspecies that prefers [[Vome (Deimos)|Vome]] appearing almost exclusively during its phase.",
			Introduced = "29.0",
			MaxAge = { Month = 3, Year = 1 },
			MaxWeight = 0.01,
			MinAge = { Month = 9, Year = 0 },
			MinWeight = 0.01,
			Notes = "Predasite Scat marks the track alongside their footprints. The Scat marks are accompanied by greenish smoke.",
			Origin = "Cambion Drift",
			Rarity = "Rare",
			Reward = "",
			Standing = 0,
			TranqsNeeded = 2 
		},
		["Nephil Vasca Kavat"] = {
			Call = "KavatVascaPlayerLureCall.ogg",
			Codex = "The Vasca strain is a symbiotic blood-borne virus transmitted via the saliva of infected kavats. Existing solely to propagate itself the virus makes the host increasingly dependent upon the ingestion of blood, thereby spreading itself further and faster through the population. Vasca-infected kavats, over time, lose all sense of themselves becoming increasingly cunning, violent and ravenous.",
			CodexScans = 20,
			Faction = "Predator",
			Family = "Vasca Kavat",
			Armor = 175,
			Health = 300,
			FullImg = "VascaKavatRare.png",
			Image = "VascaKavatRare.png",
			Intro = "Vasca Kavats only appear during nighttime in the Plains of Eidolon. <br><br>When roaming, Vasca Kavats will appear in groups of three, but when called from a calling point only one will spawn.",
			Introduced = "26.0",
			MaxAge = { Month = 0, Year = 0 },
			MaxWeight = 0,
			MinAge = { Month = 0, Year = 0 },
			MinWeight = 0,
			Notes = "A very rare Vasca Kavat subspecies.",
			Origin = "Plains of Eidolon",
			Rarity = "Rare",
			Reward = "Ostron Standing",
			Standing = 750,
			TranqsNeeded = 1 
		},
		["Ostia Vasca Kavat"] = {
			Call = "KavatVascaPlayerLureCall.ogg",
			Codex = "The Vasca strain is a symbiotic blood-borne virus transmitted via the saliva of infected kavats. Existing solely to propagate itself the virus makes the host increasingly dependent upon the ingestion of blood, thereby spreading itself further and faster through the population. Vasca-infected kavats, over time, lose all sense of themselves becoming increasingly cunning, violent and ravenous.",
			CodexScans = 20,
			Faction = "Predator",
			Family = "Vasca Kavat",
			Armor = 175,
			Health = 300,
			FullImg = "VascaKavatCommon.png",
			Image = "VascaKavatCommon.png",
			Intro = "Vasca Kavats only appear during nighttime in the Plains of Eidolon. <br><br>When roaming, Vasca Kavats will appear in groups of three, but when called from a calling point only one will spawn.",
			Introduced = "26.0",
			MaxAge = { Month = 0, Year = 0 },
			MaxWeight = 0,
			MinAge = { Month = 0, Year = 0 },
			MinWeight = 0,
			Notes = "A common Vasca Kavat subspecies.",
			Origin = "Plains of Eidolon",
			Rarity = "Common",
			Reward = "Ostron Standing",
			Standing = 250,
			TranqsNeeded = 1 
		},
		["Panzer Vulpaphyla"] = {
			Call = "VulpaphylaPlayerLureCall.ogg",
			Codex = "This hardy creature has a collagenous dermis that acts as a thick, protective armor.",
			CodexScans = 20,
			Faction = "Predator",
			Family = "Vulpaphyla",
			Armor = 100,
			Health = 100,
			FullImg = "PanzerVulpaphyla.png",
			Image = "PanzerVulpaphyla.png",
			Intro = "A rare Vulpaphyla subspecies that prefers [[Fass (Deimos)|Fass]] appearing almost exclusively during its phase.<br>[[Vulpaphyla (Conservation)|Vulpaphylas]] can be attacked by the Infested before or after sedating, causing them to become ''Weakened''. Capturing a Vulpaphyla in this state allows them to be used as a modular [[Companion]] through a process called Revivification with [[Son]].",
			Introduced = "29.0",
			MaxAge = { Month = 2, Year = 1 },
			MaxWeight = 15,
			MinAge = { Month = 9, Year = 0 },
			MinWeight = 11.1,
			Notes = "Vulpaphyla Scat marks the track alongside their footprints.",
			Origin = "Cambion Drift",
			Rarity = "Rare",
			Reward = "",
			Standing = 0,
			TranqsNeeded = 3 
		},
		["Pharaoh Predasite"] = {
			Call = "PredasitePlayerLureCall.ogg",
			Codex = "Easily frightened, this Predasite flees in the sight of danger, but not before hissing a geyser of parasitic sputum. Active only while Fass watches over the Cambion Drift.",
			CodexScans = 20,
			Faction = "Predator",
			Family = "Predasite",
			Armor = 50,
			Health = 500,
			FullImg = "PharaohPredasite.png",
			Image = "PharaohPredasite.png",
			Intro = "Predasites can be attacked by the Infested before or after sedating, causing them to become ''Weakened''. Capturing a Predasite in this state allows them to be used as a modular [[Companion]] through a process called Revivification with [[Son]]<br>A rare Predasite subspecies that prefers [[Fass (Deimos)|Fass]] appearing almost exclusively during its phase.",
			Introduced = "29.0",
			MaxAge = { Month = 2, Year = 1 },
			MaxWeight = 0.01,
			MinAge = { Month = 9, Year = 0 },
			MinWeight = 0.01,
			Notes = "Predasite Scat marks the track alongside their footprints. The Scat marks are accompanied by greenish smoke.",
			Origin = "Cambion Drift",
			Rarity = "Uncommon",
			Reward = "",
			Standing = 0,
			TranqsNeeded = 2 
		},
		["Plains Kuaka"] = {
			Call = "ForestRodentPlayerLureCall.ogg",
			Codex = "A timid rodent that is easily frightened.",
			CodexScans = 20,
			Faction = "Prey",
			Family = "Kuaka",
			Armor = 50,
			Health = 1,
			FullImg = "KuakaCommon.png",
			Image = "KuakaCommon.png",
			Intro = "Kuaka notably appear in groups of three.",
			Introduced = "22.0",
			MaxAge = { Month = 0, Year = 0 },
			MaxWeight = 0,
			MinAge = { Month = 0, Year = 0 },
			MinWeight = 0,
			Notes = "A common Kuaka subspecies.",
			Origin = "Plains of Eidolon",
			Rarity = "Common",
			Reward = "Ostron Standing",
			Standing = 200,
			TranqsNeeded = 1 
		},
		["Purple Velocipod"] = {
			Call = "VelocipodCall.ogg",
			Codex = "A sluggish highlands insect that's capable of bursts of speed when threatened.",
			CodexScans = 20,
			Faction = "Prey",
			Family = "Velocipod",
			Armor = 125,
			Health = 300,
			FullImg = "PurpleVelocipodK-DriveSkin.png",
			Image = "PurpleVelocipodK-DriveSkin.png",
			Intro = "Found in the ''Swamp'', meaning in the center of [[Cambion Drift]]",
			Introduced = "29.0",
			MaxAge = { Month = 2, Year = 1 },
			MaxWeight = 0.01,
			MinAge = { Month = 8, Year = 0 },
			MinWeight = 0.01,
			Notes = "A rare, purple Velocipod subspecies.<br>Purple Velocipods appear to spawn more likely in the north-east.",
			Origin = "Cambion Drift",
			Rarity = "Common",
			Reward = "",
			Standing = 0,
			TranqsNeeded = 1 
		},
		["Red-Crested Virmink"] = {
			Call = "VirminkCall.ogg",
			Codex = "Sleek and silky, the adorable appearance of the Venusian Virmink belies its aggressive demeanor. Favoring rocky landscapes Virmink packs nose the air, scenting for Pobbers - their primary food source.",
			CodexScans = 20,
			Faction = "Predator",
			Family = "Virmink",
			Armor = 50,
			Health = 6,
			FullImg = "VirminkRare.png",
			Image = "VirminkRare.png",
			Introduced = "24.0",
			MaxAge = { Month = 8, Year = 6 },
			MaxWeight = 18.6,
			MinAge = { Month = 5, Year = 0 },
			MinWeight = 8.3,
			Notes = "A very rare Virmink subspecies. An original [[Orokin]] strain thought to be extinct during the Orokin Era, and for millennia thereafter, they have been preserved and revived alongside the Orb Vallis.",
			Origin = "Orb Vallis",
			Rarity = "Rare",
			Reward = "Solaris United Standing",
			Standing = 500,
			TranqsNeeded = 1 
		},
		["Rogue Condroc"] = {
			Call = "BirdOfPreyPlayerLureCall.ogg",
			Codex = "A carrion-eater and opportunistic bird-of-prey. Condrocs gather, feed upon carrion, and occasionally, hunt in groups known as 'committees'. Several committees will be led by an Emperor.",
			CodexScans = 20,
			Faction = "Predator",
			Family = "Condroc",
			Armor = 50,
			Health = 6,
			FullImg = "CondrocUncommon.png",
			Image = "CondrocUncommon.png",
			Intro = "When roaming, Condrocs will appear in groups of two or three and are already stationed on the ground, but when called from a calling point only one will spawn. <br><br>Condrocs are a flying species, making them difficult to capture until they land at the calling point.",
			Introduced = "22.0",
			MaxAge = { Month = 0, Year = 0 },
			MaxWeight = 0,
			MinAge = { Month = 0, Year = 0 },
			MinWeight = 0,
			Notes = "A rare Condroc subspecies. Prefers to hunt alone.",
			Origin = "Plains of Eidolon",
			Rarity = "Uncommon",
			Reward = "Ostron Standing",
			Standing = 600,
			TranqsNeeded = 1 
		},
		["Scarlet Nexifera"] = {
			Call = "NexiferaPlayerLureCall.ogg",
			Codex = "Due to its remarkable strength, this Nexifera can cause seismic shocks when hitting the ground.",
			CodexScans = 20,
			Faction = "Prey",
			Family = "Nexifera",
			Armor = 50,
			Health = 1000,
			FullImg = "ScarletNexifera.png",
			Image = "ScarletNexifera.png",
			Intro = "Nexifera can't be lured out via the normal Track and Tranq process.<br>They only spawn naturally in big caves near the Catabolic Gutter hanging from the ceiling.<br>Their hard lower exterior block all Tranq-Shots.<br>Additionally, They are 75% resistant to all Warframe abilities. Meaning all Duration gets quartered. Their resistance can accumulate, causing consecutive use of the same ability to have even less duration, eventually becoming outright immune.",
			Introduced = "29.5",
			MaxAge = { Month = 3, Year = 1 },
			MaxWeight = 0.35,
			MinAge = { Month = 11, Year = 0 },
			MinWeight = 0.25,
			Notes = "Nexifera spawn yellow-green goo below themselves. If anything steps on it they dive down and deal damage with the resulting shockwave.",
			Origin = "Cambion Drift",
			Rarity = "Rare",
			Reward = "",
			Standing = 0,
			TranqsNeeded = 1 
		},
		["Sentinel Stover"] = {
			Call = "StoverCall.ogg",
			Codex = "The Stover is a kind of proto-Kubrow that resurrected when Venus thawed. When grouped in a pack, Stovers are relentless opponents.",
			CodexScans = 20,
			Faction = "Predator",
			Family = "Stover",
			Armor = 50,
			Health = 200,
			FullImg = "StoverCommon.png",
			Image = "StoverCommon.png",
			Intro = "Stovers make their appearances within caves, whose narrow passageways make confrontation almost unavoidable. Instead of immediately fleeing, they will viciously attack their pursuers. Must be shot '''Two times''' with the Tranq Rifle to be brought down.",
			Introduced = "24.2",
			MaxAge = { Month = 0, Year = 0 },
			MaxWeight = 0,
			MinAge = { Month = 0, Year = 0 },
			MinWeight = 0,
			Notes = "A common Stover subspecies.",
			Origin = "Orb Vallis",
			Rarity = "Common",
			Reward = "Solaris United Standing",
			Standing = 800,
			TranqsNeeded = 2 
		},
		["Septic Cryptilex"] = {
			Call = "CryptilexPlayerLureCall.ogg",
			Codex = "This infectious insect is capable of hazardous viral attacks when alerted.",
			CodexScans = 20,
			Faction = "Prey",
			Family = "Cryptilex",
			Armor = 50,
			Health = 1,
			FullImg = "SepticCryptilex.png",
			Image = "SepticCryptilex.png",
			Introduced = "29.0",
			MaxAge = { Month = 3, Year = 1 },
			MaxWeight = 0.09,
			MinAge = { Month = 9, Year = 0 },
			MinWeight = 0.02,
			Notes = "A rare Cryptilex Subspecies. Its attacks deal and can proc {{D|Viral}}.",
			Origin = "Cambion Drift",
			Rarity = "Uncommon",
			Reward = "",
			Standing = 0,
			TranqsNeeded = 1 
		},
		["Sly Vulpaphyla"] = {
			Call = "VulpaphylaPlayerLureCall.ogg",
			Codex = "The most common Vulpaphyla, they travel in packs and are generally non-aggressive.",
			CodexScans = 20,
			Faction = "Predator",
			Family = "Vulpaphyla",
			Armor = 100,
			Health = 100,
			FullImg = "SlyVulpaphyla.png",
			Image = "SlyVulpaphyla.png",
			Intro = "[[Vulpaphyla (Conservation)|Vulpaphylas]] can be attacked by the Infested before or after sedating, causing them to become ''Weakened''. Capturing a Vulpaphyla in this state allows them to be used as a modular [[Companion]] through a process called Revivification with [[Son]].",
			Introduced = "29.0",
			MaxAge = { Month = 1, Year = 1 },
			MaxWeight = 14.5,
			MinAge = { Month = 10, Year = 0 },
			MinWeight = 12.3,
			Notes = "A common Vulpaphyla subspecies.<br>Vulpaphyla Scat marks the track alongside their footprints.",
			Origin = "Cambion Drift",
			Rarity = "Common",
			Reward = "",
			Standing = 0,
			TranqsNeeded = 1 
		},
		["Splendid Mergoo"] = {
			Call = "OstronSeaBirdPlayerLureCall.ogg",
			Codex = "An avian of ridiculous appearance found along coastal regions and around large bodies of water. Mergoo circle and squawk at the sight of marine predators. Many an Ostron fisher owes their lives to these odd little birds. Killing one is considered very bad luck.",
			CodexScans = 20,
			Faction = "Prey",
			Family = "Mergoo",
			Armor = 50,
			Health = 1,
			FullImg = "MergooRare.png",
			Image = "MergooRare.png",
			Intro = "Like Condrocs, Mergoo are a flying species, making them difficult to capture until they land at the calling point.",
			Introduced = "24.6",
			MaxAge = { Month = 0, Year = 0 },
			MaxWeight = 0,
			MinAge = { Month = 0, Year = 0 },
			MinWeight = 0,
			Notes = "A very rare Mergoo subspecies. A highly social specimen.",
			Origin = "Plains of Eidolon",
			Rarity = "Rare",
			Reward = "Ostron Standing",
			Standing = 1800,
			TranqsNeeded = 1 
		},
		["Sporule Avichaea"] = {
			Call = "AvichaeaPlayerLureCall.ogg",
			Codex = "This capricious avian unleashes swarms of infested spores as its primary defense mechanism. Active only while Vome watches over the Cambion Drift.",
			CodexScans = 20,
			Faction = "Prey",
			Family = "Avichaea",
			Armor = 50,
			Health = 1,
			FullImg = "SporuleAvichaea.png",
			Image = "SporuleAvichaea.png",
			Intro = "A rare Avichaea subspecies that prefers [[Vome (Deimos)|Vome]] appearing almost exclusively during its phase.",
			Introduced = "29.0",
			MaxAge = { Month = 0, Year = 1 },
			MaxWeight = 4.6,
			MinAge = { Month = 11, Year = 0 },
			MinWeight = 2.9,
			Origin = "Cambion Drift",
			Rarity = "Uncommon",
			Reward = "",
			Standing = 0,
			TranqsNeeded = 1 
		},
		["Spotted Bolarola"] = {
			Call = "BolarolaCall.ogg",
			Codex = "Favoring thunder, lightning and cratered-out areas Bolarolas are all about defense. Their armored plates protect them from most predators, tucking-and-rolling to make good their escape.",
			CodexScans = 20,
			Faction = "Neutral",
			Family = "Bolarola",
			Armor = 50,
			Health = 6,
			FullImg = "BolarolaCommon.png",
			Image = "BolarolaCommon.png",
			Intro = "Bolarolas are covered in an armored plating that neutralizes tranquilizing shots. Only their underbellies are vulnerable, and they will occasionally lean back to expose this weakness. Should they sense danger they will curl up to shield themselves, and when fleeing they will roll away. ",
			Introduced = "24.0",
			MaxAge = { Month = 4, Year = 5 },
			MaxWeight = 17.1,
			MinAge = { Month = 2, Year = 0 },
			MinWeight = 6.6,
			Notes = "A common Bolarola subspecies.",
			Origin = "Orb Vallis",
			Rarity = "Common",
			Reward = "Solaris United Standing",
			Standing = 500,
			TranqsNeeded = 1 
		},
		["Subterranean Pobber"] = {
			Call = "PobberCall.ogg",
			Codex = "Native to the fungal forests of Venus, the Pobber is a skittish rodent possessed of an objectionable odor. Always found in groups they flee at the slightest hint of trouble. They are a primary food source of [[Virmink]] and [[Sawgaw]].",
			CodexScans = 20,
			Faction = "Prey",
			Family = "Pobber",
			Armor = 50,
			Health = 2,
			FullImg = "PobberRare.png",
			Image = "PobberRare.png",
			Intro = "Pobbers notably appear in groups of three.",
			Introduced = "24.0",
			MaxAge = { Month = 11, Year = 1 },
			MaxWeight = 0.09,
			MinAge = { Month = 2, Year = 0 },
			MinWeight = 0.01,
			Notes = "A very rare Pobber subspecies. Having evolved to survive solely underground, Subterranean Pobbers almost never visit the surface and, consequently, their general population is unknown. Thought it is not definite, they are likely an adaptation unique to the [[Orb Vallis]].",
			Origin = "Orb Vallis",
			Rarity = "Rare",
			Reward = "Solaris United Standing",
			Standing = 400,
			TranqsNeeded = 1 
		},
		["Sunny Pobber"] = {
			Call = "PobberCall.ogg",
			Codex = "Native to the fungal forests of Venus, the Pobber is a skittish rodent possessed of an objectionable odor. Always found in groups they flee at the slightest hint of trouble. They are a primary food source of [[Virmink]] and [[Sawgaw]].",
			CodexScans = 20,
			Faction = "Prey",
			Family = "Pobber",
			Armor = 50,
			Health = 2,
			FullImg = "PobberCommon.png",
			Image = "PobberCommon.png",
			Intro = "Pobbers notably appear in groups of three.",
			Introduced = "24.0",
			MaxAge = { Month = 0, Year = 2 },
			MaxWeight = 0.09,
			MinAge = { Month = 4, Year = 0 },
			MinWeight = 0.01,
			Notes = "A common Pobber subspecies. Whilst also visually appealing, the Sunny Pobber's coats help them blend in with their fungal surroundings quite well. Like their more common cousins they also possess a poor odor, possibly in an attempt to stave off potential predators.",
			Origin = "Orb Vallis",
			Rarity = "Common",
			Reward = "Solaris United Standing",
			Standing = 200,
			TranqsNeeded = 1 
		},
		["Swimmer Horrasque"] = {
			Call = "HorrasqueCall.ogg",
			Codex = "This hideous creature is terrible to behold but will not attack unless provoked. When it does, its roar will shake the bowels of even the most steadfast tracker.",
			CodexScans = 20,
			Faction = "Predator",
			Family = "Horrasque",
			Armor = 50,
			Health = 22,
			FullImg = "HorrasqueUncommon.png",
			Image = "HorrasqueUncommon.png",
			Intro = "Between the starting point and the calling point, a trail of {{D|Toxin}} damaging scat will line next to their footprints. <br><br>Horrasques will crawl underground, periodically exposing their heads. If they reach the calling point they will surface and expose their whole body, making perfect captures much easier. Must be shot '''two times''' with the Tranq Rifle to be brought down.",
			Introduced = "24.2",
			MaxAge = { Month = 0, Year = 0 },
			MaxWeight = 0,
			MinAge = { Month = 0, Year = 0 },
			MinWeight = 0,
			Notes = "A rare Horrasque subspecies. Horrasques are not known to be the most graceful of swimmers, but this species persists.",
			Origin = "Orb Vallis",
			Rarity = "Uncommon",
			Reward = "Solaris United Standing",
			Standing = 1200,
			TranqsNeeded = 2 
		},
		["Thorny Bolarola"] = {
			Call = "BolarolaCall.ogg",
			Codex = "Favoring thunder, lightning and cratered-out areas Bolarolas are all about defense. Their armored plates protect them from most predators, tucking-and-rolling to make good their escape.",
			CodexScans = 20,
			Faction = "Neutral",
			Family = "Bolarola",
			Armor = 50,
			Health = 6,
			FullImg = "BolarolaRare.png",
			Image = "BolarolaRare.png",
			Intro = "Bolarolas are covered in an armored plating that neutralizes tranquilizing shots. Only their underbellies are vulnerable, and they will occasionally lean back to expose this weakness. Should they sense danger they will curl up to shield themselves, and when fleeing they will roll away. ",
			Introduced = "24.0",
			MaxAge = { Month = 11, Year = 0 },
			MaxWeight = 9.5,
			MinAge = { Month = 3, Year = 0 },
			MinWeight = 5.7,
			Notes = "A very rare Bolarola subspecies. Their spines have evolved into thorn-like barbs that give them an even greater defense.",
			Origin = "Orb Vallis",
			Rarity = "Rare",
			Reward = "Solaris United Standing",
			Standing = 1250,
			TranqsNeeded = 1 
		},
		["Umber Undazoa"] = {
			Call = "UndazoaPlayerLureCall.ogg",
			Codex = "A shy, bizarre-looking, semi-aquatic creature that seldom attacks unless provoked.",
			CodexScans = 20,
			Faction = "Prey",
			Family = "Undazoa",
			Armor = 50,
			Health = 22,
			FullImg = "UmberUndazoa.png",
			Image = "UmberUndazoa.png",
			Intro = "Undazoa approach the Call-Point in the Exocrine, [[Cambion Drift|Cambion Drifts]] river-like formations.",
			Introduced = "29.5",
			MaxAge = { Month = 3, Year = 50 },
			MaxWeight = 63.5,
			MinAge = { Month = 6, Year = 5 },
			MinWeight = 52.5,
			Notes = "Undazoa Scat marks the track alongside their footprints.",
			Origin = "Cambion Drift",
			Rarity = "Common",
			Reward = "",
			Standing = 0,
			TranqsNeeded = 2 
		},
		["Vallis Kubrodon"] = {
			Call = "KubrodonCall.ogg",
			Codex = "The apex predator of the Venusian plains. These massively framed beasts travel in groups and mark the territory surrounding Orokin cooling towers as their own. Kubrodons are a danger best avoided.",
			CodexScans = 20,
			Faction = "Neutral",
			Family = "Kubrodon",
			Armor = 50,
			Health = 1000,
			FullImg = "KubrodonUncommon.png",
			Image = "KubrodonUncommon.png",
			Intro = "True to its status as the apex predator, the Kubrodon's more acute sense of smell allows them to locate their pursuers, and will use a ramming attack to make good their escape. Must be shot twice with the Tranq Rifle to be brought down. <br><br>Additionally, Kubrodons are 75% resistant to all Warframe abilities. For example, when using {{WF|Ivara}}’s [[Quiver|Sleep Arrow]] to put a Kubrodon to sleep, the [[Ability Duration]] will be a quarter (1/4) of its full duration (Ivara’s Sleep Arrow with Maximized Ability Duration: 30.6 seconds ÷ 4 = 7.65 seconds). Their resistance can accumulate, causing consecutive use of the same ability to have even less duration, eventually becoming outright immune.<br><br>Despite being mentioned to travel in groups, only one Kubrodon will respond to the lure's call.",
			Introduced = "24.0",
			MaxAge = { Month = 0, Year = 0 },
			MaxWeight = 0,
			MinAge = { Month = 0, Year = 0 },
			MinWeight = 0,
			Notes = "A rare Kubdrodon subspecies. Unimaginatively named due to not being found anywhere outside Orb Vallis.",
			Origin = "Orb Vallis",
			Rarity = "Uncommon",
			Reward = "Solaris United Standing",
			Standing = 2000,
			TranqsNeeded = 2 
		},
		["Vaporous Undazoa"] = {
			Call = "UndazoaPlayerLureCall.ogg",
			Codex = "The Vaporous Undazoa gets its name from the noxious gas it belches out when alerted.",
			CodexScans = 20,
			Faction = "Prey",
			Family = "Undazoa",
			Armor = 50,
			Health = 22,
			FullImg = "VaporousUndazoa.png",
			Image = "VaporousUndazoa.png",
			Intro = "A rare Undazoa subspecies that prefers [[Fass (Deimos)|Fass]] appearing almost exclusively during its phase.<br>Undazoa approach the Call-Point in the Exocrine, [[Cambion Drift|Cambion Drifts]] river-like formations.",
			Introduced = "29.5",
			MaxAge = { Month = 6, Year = 40 },
			MaxWeight = 61.1,
			MinAge = { Month = 5, Year = 11 },
			MinWeight = 45.8,
			Notes = "Undazoa Scat marks the track alongside their footprints.",
			Origin = "Cambion Drift",
			Rarity = "Uncommon",
			Reward = "",
			Standing = 0,
			TranqsNeeded = 2 
		},
		["Viridian Nexifera"] = {
			Call = "NexiferaPlayerLureCall.ogg",
			Codex = "The Viridian Nexifera can produce a cloud of poisonous gas that's always best avoided.",
			CodexScans = 20,
			Faction = "Prey",
			Family = "Nexifera",
			Armor = 50,
			Health = 1000,
			FullImg = "ViridianNexifera.png",
			Image = "ViridianNexifera.png",
			Intro = "Nexifera can't be lured out via the normal Track and Tranq process.<br>They only spawn naturally in big caves near the Catabolic Gutter hanging from the ceiling.<br>Their hard lower exterior block all Tranq-Shots.<br>Additionally, They are 75% resistant to all Warframe abilities. Meaning all Duration gets quartered. Their resistance can accumulate, causing consecutive use of the same ability to have even less duration, eventually becoming outright immune.",
			Introduced = "29.5",
			MaxAge = { Month = 3, Year = 1 },
			MaxWeight = 0.35,
			MinAge = { Month = 10, Year = 0 },
			MinWeight = 0.28,
			Notes = "Nexifera spawn yellow-green goo below themselves. If anything steps on it they dive down and deal damage with the resulting shockwave.",
			Origin = "Cambion Drift",
			Rarity = "Uncommon",
			Reward = "",
			Standing = 0,
			TranqsNeeded = 1 
		},
		["Viscid Avichaea"] = {
			Call = "AvichaeaPlayerLureCall.ogg",
			Codex = "The rarest of Avichaeas, the Viscid produces a thick, tar-like mucus that it discharges when imperiled. Active only while Fass watches over the Cambion Drift.",
			CodexScans = 20,
			Faction = "Prey",
			Family = "Avichaea",
			Armor = 50,
			Health = 1,
			FullImg = "ViscidAvichaea.png",
			Image = "ViscidAvichaea.png",
			Intro = "A rare Avichaea subspecies that prefers [[Fass (Deimos)|Fass]] appearing almost exclusively during its phase.",
			Introduced = "29.0",
			MaxAge = { Month = 1, Year = 1 },
			MaxWeight = 4.3,
			MinAge = { Month = 11, Year = 0 },
			MinWeight = 1.8,
			Origin = "Cambion Drift",
			Rarity = "Rare",
			Reward = "",
			Standing = 0,
			TranqsNeeded = 1 
		},
		["Vizier Predasite"] = {
			Call = "PredasitePlayerLureCall.ogg",
			Codex = "A skittish creature, the Vizier Predasite will unleash a spume of acid before scurrying away.",
			CodexScans = 20,
			Faction = "Predator",
			Family = "Predasite",
			Armor = 50,
			Health = 500,
			FullImg = "VizierPredasite.png",
			Image = "VizierPredasite.png",
			Intro = "Predasites can be attacked by the Infested before or after sedating, causing them to become ''Weakened''. Capturing a Predasite in this state allows them to be used as a modular [[Companion]] through a process called Revivification with [[Son]]",
			Introduced = "29.0",
			MaxAge = { Month = 4, Year = 12 },
			MaxWeight = 31.7,
			MinAge = { Month = 4, Year = 1 },
			MinWeight = 26.3,
			Notes = "Predasite Scat marks the track alongside their footprints. The Scat marks are accompanied by greenish smoke.",
			Origin = "Cambion Drift",
			Rarity = "Common",
			Reward = "",
			Standing = 0,
			TranqsNeeded = 2 
		},
		["White Velocipod"] = {
			Call = "VelocipodCall.ogg",
			Codex = "The fastest variety of Velocipod, it tends to favor the swamplands.",
			CodexScans = 20,
			Faction = "Prey",
			Family = "Velocipod",
			Armor = 125,
			Health = 300,
			FullImg = "WhiteVelocipodK-DriveSkin.png",
			Image = "WhiteVelocipodK-DriveSkin.png",
			Intro = "Found in the ''Swamp'', meaning in the center of [[Cambion Drift]]",
			Introduced = "29.0",
			MaxAge = { Month = 11, Year = 0 },
			MaxWeight = 0,
			MinAge = { Month = 11, Year = 0 },
			MinWeight = 0,
			Notes = "A very rare, white Velocipod subspecies.<br>White Velocipods appear to spawn more likely north of Infested Seraglio.",
			Origin = "Cambion Drift",
			Rarity = "Rare",
			Reward = "",
			Standing = 0,
			TranqsNeeded = 1 
		},
		["White-Breasted Virmink"] = {
			Call = "VirminkCall.ogg",
			Codex = "Sleek and silky, the adorable appearance of the Venusian Virmink belies its aggressive demeanor. Favoring rocky landscapes Virmink packs nose the air, scenting for [[Pobber|Pobbers]] - their primary food source.",
			CodexScans = 20,
			Faction = "Predator",
			Family = "Virmink",
			Armor = 50,
			Health = 6,
			FullImg = "VirminkCommon.png",
			Image = "VirminkCommon.png",
			Introduced = "24.0",
			MaxAge = { Month = 6, Year = 8 },
			MaxWeight = 19.2,
			MinAge = { Month = 2, Year = 0 },
			MinWeight = 10.6,
			Notes = "A common Virmink subspecies.",
			Origin = "Orb Vallis",
			Rarity = "Common",
			Reward = "Solaris United Standing",
			Standing = 300,
			TranqsNeeded = 1 
		},
		["Woodland Mergoo"] = {
			Call = "OstronSeaBirdPlayerLureCall.ogg",
			Codex = "An avian of ridiculous appearance found along coastal regions and around large bodies of water. Mergoo circle and squawk at the sight of marine predators. Many an Ostron fisher owes their lives to these odd little birds. Killing one is considered very bad luck.",
			CodexScans = 20,
			Faction = "Prey",
			Family = "Mergoo",
			Armor = 50,
			Health = 1,
			FullImg = "MergooUncommon.png",
			Image = "MergooUncommon.png",
			Intro = "Like Condrocs, Mergoo are a flying species, making them difficult to capture until they land at the calling point.",
			Introduced = "24.6",
			MaxAge = { Month = 0, Year = 0 },
			MaxWeight = 0,
			MinAge = { Month = 0, Year = 0 },
			MinWeight = 0,
			Notes = "A rare Mergoo subspecies. Their plumage makes them difficult for hunters to spot them among foliage.",
			Origin = "Plains of Eidolon",
			Rarity = "Uncommon",
			Reward = "Ostron Standing",
			Standing = 1200,
			TranqsNeeded = 1 
		} 
	} 
}
