--- Synthesis targets table for [[Synthesis]] targets.
-- @module Synthesis/data
-- 

local synthesisData = {
	["Ancient Disruptor"] = {
		_IgnoreEntry = false,
		Locations = { "Tikal", "Terminus", "Isos" },
		IsImprint = false,
		Size = "Big",
		ScanPoints = 4,
		Standing = 2538,
	},
	["Ancient Healer"] = {
		_IgnoreEntry = false,
		Locations = { "Hepit" },
		IsImprint = false,
		Size = "Big",
		ScanPoints = 4, -- unsure
		Standing = 2538, -- unsure
	},
	["Anti MOA"] = {
		_IgnoreEntry = false,
		Locations = { "Valefor", "Baal", "Zeipel" },
		IsImprint = true,
		Size = "Big",
		ScanPoints = 3,
		Standing = 2550,
	},
	["Arid Eviscerator"] = {
		_IgnoreEntry = false,
		Locations = { "Ara" },
		IsImprint = true,
		Size = "Big", -- unsure
		ScanPoints = 3, -- unsure
		Standing = -1, -- unsure
	},
	["Ballista"] = {
		_IgnoreEntry = false,
		Locations = { "Mantle", "Lex" },
		IsImprint = false,
		Size = "Big",
		ScanPoints = 4,
		Standing = 2538,
	},
	["Boiler"] = {
		_IgnoreEntry = false,
		Locations = { "Cholistan", "Isos", "Horend" },
		IsImprint = false,
		Size = "Big",
		ScanPoints = 4,
		Standing = 2538,
	},
	["Bombard"] = {
		_IgnoreEntry = false,
		Locations = { "Lex", "Nuovo", "Ker", "Exta", "Bode" },
		IsImprint = false,
		Size = "Big",
		ScanPoints = 4,
		Standing = 2625,
	},
	["Brood Mother"] = {
		_IgnoreEntry = false,
		Locations = { "Tikal", "Gabii", "Assur", "Isos" },
		IsImprint = false,
		Size = "Big",
		ScanPoints = 4,
		Standing = 2538,
	},
	["Butcher"] = {
		_IgnoreEntry = false,
		Locations = { "Caloris", "Elion", "Rusalka", "Mantle" },
		IsImprint = false,
		Size = "Small",
		ScanPoints = 4,
		Standing = 2513,
	},
	["Charger"] = {
		_IgnoreEntry = false,
		Locations = { "Terminus", "M Prime", "Isos" },
		IsImprint = false,
		Size = "Small",
		ScanPoints = 4,
		Standing = 2513,
	},
	["Commander"] = {
		_IgnoreEntry = false,
		Locations = { "Telesto" },
		IsImprint = false,
		Size = "Big", -- unsure 
		ScanPoints = 4, -- unsure 
		Standing = -1
		,
	},
	["Corrupted Ancient"] = {
		_IgnoreEntry = false,
		Locations = { "Hepit", "Stribog", "Ani" },
		IsImprint = false,
		Size = "Big", 
		ScanPoints = 4,
		Standing = 2538,
	},
	["Corrupted Bombard"] = {
		_IgnoreEntry = false,
		Locations = { "Oxomoco", "Marduk", "Aten" },
		IsImprint = false,
		Size = "Big",
		ScanPoints = 4,
		Standing = 2625,
	},
	["Corrupted Butcher"] = {
		_IgnoreEntry = false,
		Locations = { "Hepit", "Teshub" },
		IsImprint = false,
		Size = "Small",
		ScanPoints = 3, -- unsure
		Standing = 2513,
	},
	["Corrupted Crewman"] = {
		_IgnoreEntry = false,
		Locations = { "Hepit", "Teshub" },
		IsImprint = false,
		Size = "Small",
		ScanPoints = 4,
		Standing = 2513,
	},
	["Corrupted Heavy Gunner"] = {
		_IgnoreEntry = false,
		Locations = { "Hepit", "Teshub", "Ukko" },
		IsImprint = false,
		Size = "Big",
		ScanPoints = 4,
		Standing = 2625,
	},
	["Corrupted Lancer"] = {
		_IgnoreEntry = false,
		Locations = { "Hepit", "Ukko" },
		IsImprint = false,
		Size = "Small",
		ScanPoints = 4,
		Standing = 2513,
	},
	["Corrupted Nullifier"] = {
		_IgnoreEntry = false,
		Locations = { "Oxomoco", "Marduk" },
		IsImprint = false,
		Size = "Big",
		ScanPoints = 4,
		Standing = -1,
	},
	["Crawler"] = {
		_IgnoreEntry = false,
		Locations = { "Isos", "Tikal", "Armaros", "Brugia" },
		IsImprint = false,
		Size = "Small",
		ScanPoints = 3,
		Standing = 2509,
	},
	["Crewman"] = {
		_IgnoreEntry = false,
		Locations = { "Copernicus" },
		IsImprint = true,
		Size = "Big", -- unsure 
		ScanPoints = 4, -- unsure
		Standing = -1,
	},
	["Drahk Master"] = {
		_IgnoreEntry = false,
		Locations = { "Cassini", "Anthe" },
		IsImprint = false,
		Size = "Big",
		ScanPoints = 4,
		Standing = 2538,
	},
	["Elite Crewman"] = {
		_IgnoreEntry = false,
		Locations = { "Copernicus", "Zeipel" },
		IsImprint = false,
		Size = "Big",
		ScanPoints = 4,
		Standing = 2538,
	},
	["Eviscerator"] = {
		_IgnoreEntry = false,
		Locations = { "Ara", "Lex", "Ker" },
		IsImprint = false,
		Size = "Big",
		ScanPoints = 4,
		Standing = 2538,
	},
	["Fusion MOA"] = {
		_IgnoreEntry = false,
		Locations = { "Unda", "Kokabiel", "Abaddon", "Galatea" },
		IsImprint = false,
		Size = "Big",
		ScanPoints = 3,
		Standing = 2563,
	},
	["Guardsman"] = {
		_IgnoreEntry = false,
		Locations = { "Lex", "Nuovo", "Ludi" },
		IsImprint = true,
		Size = "Small",
		ScanPoints = 4,
		Standing = 2525,
	},
	["Heavy Gunner"] = {
		_IgnoreEntry = false,
		Locations = { "Elion", "Caloris", "Lex", "Rusalka" },
		IsImprint = false,
		Size = "Big",
		ScanPoints = 4,
		Standing = 2625,
	},
	["Hellion"] = {
		_IgnoreEntry = false,
		Locations = { "Ara", "Lex", "Rusalka" },
		IsImprint = false,
		Size = "Big",
		ScanPoints = 4,
		Standing = 2563,
	},
	["Lancer"] = {
		_IgnoreEntry = false,
		Locations = { "Cambria", "Caloris", "Pantheon", "Elion", "Cassini", "Kappa" },
		IsImprint = true,
		Size = "Small",
		ScanPoints = 4,
		Standing = 2513,
	},
	["Leaper"] = {
		_IgnoreEntry = false,
		Locations = { "Isos", "Tikal" },
		IsImprint = false,
		Size = "Small",
		ScanPoints = 4,
		Standing = 2509,
	},
	["MOA"] = {
		_IgnoreEntry = false,
		Locations = { "Venera", "Linea", "E Gate" },
		IsImprint = false,
		Size = "Small",
		ScanPoints = 3,
		Standing = 2513,
	},
	["Napalm"] = {
		_IgnoreEntry = false,
		Locations = { "Cassini", "Selkie", "Naga" },
		IsImprint = false,
		Size = "Big",
		ScanPoints = 4,
		Standing = 2625,
	},
	["Nullifier Crewman"] = {
		_IgnoreEntry = false,
		Locations = { "Abaddon", "Orias", "Regna" },
		IsImprint = false,
		Size = "Big",
		ScanPoints = 4,
		Standing = 2538,
	},
	["Runner"] = {
		_IgnoreEntry = false,
		Locations = { "Saxis", "Phlegyas" },
		IsImprint = true,
		Size = "Small", -- unsure
		ScanPoints = 3, -- unsure
		Standing = -1,
	},
	["Scorch"] = {
		_IgnoreEntry = false,
		Locations = { "Cassini", "Dione", "Numa", "Anthe" },
		IsImprint = false,
		Size = "Big",
		ScanPoints = 4,
		Standing = 2625,
	},
	["Scorpion"] = {
		_IgnoreEntry = false,
		Locations = { "Lex", "Cassini", "Numa", "Plato" },
		IsImprint = false,
		Size = "Small",
		ScanPoints = 4,
		Standing = 2525,
	},
	["Seeker"] = {
		_IgnoreEntry = false,
		Locations = { "E Prime", "Lex", "Nuovo", "Kelpie" },
		IsImprint = false,
		Size = "Big",
		ScanPoints = 4,
		Standing = 2538,
	},
	["Frontier Seeker"] = {
		_IgnoreEntry = false,
		Locations = { "E Prime", "Lex", "Nuovo", "Kelpie" },
		IsImprint = false,
		Size = "Big",
		ScanPoints = 4,
		Standing = 2538,
	},
	["Shield Lancer"] = {
		_IgnoreEntry = false,
		Locations = { "Pantheon", "Caloris", "Elion", "Cassini" },
		IsImprint = false,
		Size = "Small",
		ScanPoints = 4,
		Standing = 2513,
	},
	["Swarm Mutalist MOA"] = {
		_IgnoreEntry = false,
		Locations = { "Armaros", "Isos", "Brugia" },
		IsImprint = false,
		Size = "Big",
		ScanPoints = 3,
		Standing = 2538,
	},
	["Trooper"] = {
		_IgnoreEntry = false,
		Locations = { "Mantle", "E Prime", "Numa", "Cassini" },
		IsImprint = false,
		Size = "Small",
		ScanPoints = 4,
		Standing = 2525,
	},
}

return synthesisData
