			{	Type = 'Bows',
				Classes = { 'Bow', 'Crossbow', 'Exalted Weapon' },
				Triggers = {
					{	Name = 'Auto',
						{'Auto'},
						Weapons = {},
					},
					{	Name = 'Charge',
						{'Charge'},
						Weapons = {},
					},
					{	Name = 'Hybrid',
						{'Semi / Burst'},
						Weapons = {},
					},
				},
			},
