{
	CreditsReward = 0,
	DropTableAlias = "Drop table entry key in Module:DropTables/data",
	Enemy = "Enemy faction",
	InternalName = "SolNode0",
	Introduced = "Vanilla",
	Link = "Node article name",
	MaxLevel = 11,
	MinLevel = 6,
	Name = "Node name",
	NextNodes = { "" },
	Planet = "Planet name",
	PreviousNodes = { "" },
	Quotes = "Quotes article name",
	Tileset = "Tileset name",
	Type = "Mission type",
},
