	["Arcane Name"] = {
		CodexSecret = true,
		Description = "Description",
		Dissolution = 20,
		Icon = "ArcaneIcon.png",
		Image = "ArcaneImage.png",
		Introduced = "29",
		IsRefreshable = true,
		Link = "Page Name",
		MaxRank = 5,
		Name = "Arcane Name",
		Rarity = "Rare",
		Type = "Primary",
	},
