return {
	["/Lotus/Weapons/Tenno/Pistols/PrimePandero/PanderoPrimeWeapon"] = {
		Animator = "",
		ConceptArtist = "Andrew Yu",
		Modeller = "Malaya Yu",
		SoundDesigner = "",
		SourceLink = "https://www.artstation.com/artwork/3dDJlm",
		SourceArchive = "",
	},
	["/Lotus/Weapons/Tenno/Archwing/Primary/ThanoTechGrenadeLaunch/ThanoTechGrenadeLauncher"] = {
		Animator = "",
		ConceptArtist = "Lucas Hug",
		Modeller = "Malaya Yu",
		SoundDesigner = "",
		SourceLink = "https://www.artstation.com/artwork/L39KLA",
		SourceArchive = "",
	},
	["/Lotus/Weapons/ClanTech/Chemical/FlameThrower"] = {
		ConceptArtist = "Lucas Hug",
		Modeller = "Lucas Hug",
		SourceLink = "https://www.artstation.com/artwork/XXm5a",
		SourceArchive = "",
	},
	["/Lotus/Weapons/Grineer/Pistols/GrnKohmPistol/GrnKohmPistol"] = {
		ConceptArtist = "Lucas Hug",
		Modeller = "Lucas Hug",
		SourceLink = "https://www.artstation.com/artwork/XXm5a",
		SourceArchive = "",
	},
	["/Lotus/Weapons/Grineer/Melee/GrnDualFireAxe/GrnDualFireAxe"] = {
		ConceptArtist = "Lucas Hug",
		Modeller = "Lucas Hug",
		SourceLink = "https://www.artstation.com/artwork/XXm5a",
		SourceArchive = "",
	},
	["/Lotus/Weapons/ClanTech/Chemical/RocketLauncher"] = {
		ConceptArtist = "Lucas Hug",
		Modeller = "Lucas Hug",
		SourceLink = "https://www.artstation.com/artwork/XXm5a",
		SourceArchive = "",
	},
	["/Lotus/Weapons/ClanTech/Bio/BioWeapon"] = {
		ConceptArtist = "Lucas Hug",
		Modeller = "Lucas Hug",
		SourceLink = "https://www.artstation.com/artwork/XXm5a",
		SourceArchive = "",
	},
	["/Lotus/Weapons/Grineer/Melee/GrineerTylAxeAndBoar/RegorAxeShield"] = {
		ConceptArtist = "Lucas Hug",
		Modeller = "Lucas Hug",
		SourceLink = "https://www.artstation.com/artwork/XXm5a",
		SourceArchive = "",
	},
	["/Lotus/Weapons/Grineer/Melee/GrineerWhip/GrineerWhip"] = {
		ConceptArtist = "Lucas Hug",
		Modeller = "Lucas Hug",
		SourceLink = "https://www.artstation.com/artwork/XXm5a",
		SourceArchive = "",
	},
	["/Lotus/Weapons/Infested/Melee/TipedoStaff/InfTipedoStaff"] = {
		ConceptArtist = "Lucas Hug",
		Modeller = "",
		SourceLink = "https://www.artstation.com/artwork/XXm5a",
		SourceArchive = "",
	},
	["/Lotus/Weapons/Infested/LongGuns/QuantaFullyInfested/InfQuantaRifle"] = {
		ConceptArtist = "Lucas Hug",
		Modeller = "Lucas Hug",
		SourceLink = "https://www.artstation.com/artwork/XXm5a",
		SourceArchive = "",
	},
	["/Lotus/Weapons/Tenno/Pistols/PrimeVasto/PrimeVastoPistol"] = {
		ConceptArtist = "",
		Modeller = "Lucas Hug",
		SourceLink = "https://www.artstation.com/artwork/XXm5a",
		SourceArchive = "",
	},
	["/Lotus/Weapons/Tenno/Pistols/PrimeVasto/AkPrimeVasto/AkPrimeVastoPistol"] = {
		ConceptArtist = "",
		Modeller = "Lucas Hug",
		SourceLink = "https://www.artstation.com/artwork/XXm5a",
		SourceArchive = "",
	},
	["/Lotus/Weapons/Tenno/LongGuns/RepeatingCrossbow/RepeatingCrossbow"] = {
		ConceptArtist = "",
		Modeller = "Lucas Hug",
		SourceLink = "https://www.artstation.com/artwork/XXm5a",
		SourceArchive = "",
	},
	["/Lotus/Weapons/Tenno/Archwing/Primary/ArchBurstGun/ArchBurstGun"] = {
		ConceptArtist = "Lucas Hug",
		Modeller = "Lucas Hug",
		SourceLink = "https://www.artstation.com/artwork/XXm5a",
		SourceArchive = "",
	},
}
