			General = {
				Abilities = { "Seismic Shockwave" },
				Actor = "",
				CodexSecret = false,
				Description = "Codex description of enemy",
				Faction = "Grineer",
				Missions = {},
				Image = "EnemyImage.png",
				InternalName = "",
				Introduced = "29",
				Link = "Page Name",
				Name = "Enemy Name",
 				Planets = {},
				Scans = 3,
				Type = "Ranged",
 				Weapons = { "Gorgon", "Sheev" },
			},