	["Companion Name"] = {
		Armor = 100,
		Description = "Description",
		Health = 100,
		Image = "CompanionName.png",
		InternalName = "",
		Introduced = "29",
		Link = "Page Name",
		MaxRank = 30,
		Name = "Companion Name",
		Polarities = { "Penjaga", "Penjaga", "Penjaga", "Penjaga" },
		SellPrice = 5000,
		Shield = 100,
		SquadPortrait = "CompanionNameLargePortrait.png",
		Type = "Kubrow",
	},
