return {
------------------------------------Amps----------------------------------------
	["Cantic Prism (Gilded)"] = {
		Accuracy = 32,
		AmmoType = "Energy",
		Attack1 = {
			AmmoCost = 3,
			AttackName = "Normal Attack",
			BurstCount = 3,
			CritChance = 0.34,
			CritMultiplier = 2.2,
			Damage = {
				Void = 1460,
			},
			FireRate = 4.88,
			IsSilent = false,
			Multishot = 1,
			PunchThrough = 0,
			Range = 100,
			ShotType = "Hit-Scan",
			StatusChance = 0.1,
		},
		Class = "Amp",
		Conclave = false,
		Image = "CanticPrism.png",
		Introduced = "24.2",
		Link = "Cantic Prism",
		Magazine = 100,
		Mastery = 0,
		MaxAmmo = math.huge,
		Name = "Cantic Prism (Gilded)",
		Polarities = {
		},
		Reload = 5.33,
		ReloadDelay = 2,
		ReloadRate = 30,
		ReloadStyle = "Regenerate",
		Slot = "Amp",
		Traits = {
			"Sentient",
		},
		Trigger = "Burst",
	},
	["Cantic Prism"] = {
		Accuracy = 32,
		AmmoType = "Energy",
		Attack1 = {
			AmmoCost = 3,
			AttackName = "Normal Attack",
			BurstCount = 3,
			CritChance = 0.17,
			CritMultiplier = 1.5,
			Damage = {
				Void = 1460,
			},
			FireRate = 4.88,
			IsSilent = false,
			Multishot = 1,
			PunchThrough = 0,
			Range = 100,
			ShotType = "Hit-Scan",
			StatusChance = 0.05,
		},
		Class = "Amp",
		Conclave = false,
		Image = "CanticPrism.png",
		InternalName = "/Lotus/Weapons/Corpus/OperatorAmplifiers/Set1/Barrel/CorpAmpSet1BarrelPartA",
		Introduced = "24.2",
		Link = "Cantic Prism",
		Magazine = 100,
		Mastery = 0,
		MaxAmmo = math.huge,
		Name = "Cantic Prism",
		Polarities = {
		},
		Reload = 5.33,
		ReloadDelay = 2,
		ReloadRate = 30,
		ReloadStyle = "Regenerate",
		Slot = "Amp",
		Traits = {
			"Sentient",
		},
		Trigger = "Burst",
	},
	["Dissic Scaffold (Gilded)"] = {
		Accuracy = 100,
		AmmoType = "Energy",
		Attack1 = {
			AmmoCost = 50,
			AttackName = "Direct Hit",
			CritChance = 0.03,
			CritMultiplier = 1.5,
			Damage = {
				Impact = 15,
			},
			FireRate = 1,
			IsSilent = false,
			Multishot = 1,
			PunchThrough = 0,
			ShotType = "Projectile",
			StatusChance = 0.37,
		},
		Attack2 = {
			AttackName = "Explosion",
			CritChance = 0.03,
			CritMultiplier = 1.5,
			Damage = {
				Void = 6600,
			},
			Falloff = {
				EndRange = 12,
				Reduction = 0.6,
				StartRange = 0,
			},
			FireRate = 1,
			IsSilent = false,
			Multishot = 1,
			PunchThrough = 0,
			Range = 12,
			ShotType = "AoE",
			StatusChance = 0.37,
		},
		Attack3 = {
			AttackName = "Explosive Fragments",
			CritChance = 0.03,
			CritMultiplier = 1.5,
			Damage = {
				Void = 300,
			},
			FireRate = 1,
			IsSilent = false,
			Multishot = 10,
			PunchThrough = 0,
			StatusChance = 0.37,
		},
		Class = "Amp",
		Conclave = false,
		Image = "DissicScaffold.png",
		Introduced = "24.2",
		Link = "Dissic Scaffold",
		Magazine = 100,
		Mastery = 0,
		MaxAmmo = math.huge,
		Name = "Dissic Scaffold (Gilded)",
		Polarities = {
		},
		Reload = 5.33,
		ReloadDelay = 2,
		ReloadRate = 30,
		ReloadStyle = "Regenerate",
		Slot = "Amp",
		Traits = {
			"Sentient",
		},
		Trigger = "Semi-Auto",
		_TooltipAttackDisplay = "Attack2",
	},
	["Dissic Scaffold"] = {
		Accuracy = 100,
		AmmoType = "Energy",
		Attack1 = {
			AmmoCost = 50,
			AttackName = "Direct Hit",
			CritChance = 0,
			CritMultiplier = 0,
			Damage = {
				Impact = 15,
			},
			FireRate = 1,
			IsSilent = false,
			Multishot = 1,
			PunchThrough = 0,
			ShotType = "Projectile",
			StatusChance = 0.2,
		},
		Attack2 = {
			AttackName = "Explosion",
			CritChance = 0,
			CritMultiplier = 0,
			Damage = {
				Void = 6600,
			},
			Falloff = {
				EndRange = 12,
				Reduction = 0.6,
				StartRange = 0,
			},
			FireRate = 1,
			IsSilent = false,
			Multishot = 1,
			PunchThrough = 0,
			Range = 12,
			ShotType = "AoE",
			StatusChance = 0.2,
		},
		Attack3 = {
			AttackName = "Explosive Fragments",
			CritChance = 0,
			CritMultiplier = 0,
			Damage = {
				Void = 300,
			},
			FireRate = 1,
			IsSilent = false,
			Multishot = 10,
			PunchThrough = 0,
			StatusChance = 0.2,
		},
		Class = "Amp",
		Conclave = false,
		Image = "DissicScaffold.png",
		InternalName = "/Lotus/Weapons/Corpus/OperatorAmplifiers/Set1/Chassis/CorpAmpSet1ChassisPartB",
		Introduced = "24.2",
		Link = "Dissic Scaffold",
		Magazine = 100,
		Mastery = 0,
		MaxAmmo = math.huge,
		Name = "Dissic Scaffold",
		Polarities = {
		},
		Reload = 5.33,
		ReloadDelay = 2,
		ReloadRate = 30,
		ReloadStyle = "Regenerate",
		Slot = "Amp",
		Traits = {
			"Sentient",
		},
		Trigger = "Semi-Auto",
		_TooltipAttackDisplay = "Attack2",
	},
	["Exard Scaffold (Gilded)"] = {
		Accuracy = 10,
		AmmoType = "Energy",
		Attack1 = {
			AmmoCost = 20,
			AttackName = "Direct Hit",
			CritChance = 0.17,
			CritMultiplier = 1.9,
			Damage = {
				Impact = 200,
			},
			FireRate = 8.26,
			IsSilent = false,
			Multishot = 1,
			PunchThrough = 0,
			Range = 40,
			ShotType = "Projectile",
			StatusChance = 0.33,
		},
		Attack2 = {
			AttackName = "Explosion",
			CritChance = 0.17,
			CritMultiplier = 1.9,
			Damage = {
				Void = 2600,
			},
			Falloff = {
				EndRange = 1,
				Reduction = 0.3,
				StartRange = 0,
			},
			FireRate = 8.26,
			IsSilent = false,
			Multishot = 1,
			PunchThrough = 0,
			Range = 1,
			ShotType = "AoE",
			StatusChance = 0.33,
		},
		Class = "Amp",
		Conclave = false,
		Image = "ExardScaffold.png",
		Introduced = "24.2",
		Link = "Exard Scaffold",
		Magazine = 100,
		Mastery = 0,
		MaxAmmo = math.huge,
		Name = "Exard Scaffold (Gilded)",
		Polarities = {
		},
		Reload = 5.33,
		ReloadDelay = 2,
		ReloadRate = 30,
		ReloadStyle = "Regenerate",
		Slot = "Amp",
		Traits = {
			"Sentient",
		},
		Trigger = "Burst",
		_TooltipAttackDisplay = "Attack2",
	},
	["Exard Scaffold"] = {
		Accuracy = 10,
		AmmoType = "Energy",
		Attack1 = {
			AmmoCost = 20,
			AttackName = "Direct Hit",
			CritChance = 0,
			CritMultiplier = 0,
			Damage = {
				Impact = 200,
			},
			FireRate = 8.26,
			IsSilent = false,
			Multishot = 1,
			PunchThrough = 0,
			Range = 40,
			ShotType = "Projectile",
			StatusChance = 0.28,
		},
		Attack2 = {
			AttackName = "Explosion",
			CritChance = 0,
			CritMultiplier = 0,
			Damage = {
				Void = 2600,
			},
			Falloff = {
				EndRange = 1,
				Reduction = 0.3,
				StartRange = 0,
			},
			FireRate = 8.26,
			IsSilent = false,
			Multishot = 1,
			PunchThrough = 0,
			Range = 1,
			ShotType = "AoE",
			StatusChance = 0.28,
		},
		Class = "Amp",
		Conclave = false,
		Image = "ExardScaffold.png",
		InternalName = "/Lotus/Weapons/Corpus/OperatorAmplifiers/Set1/Chassis/CorpAmpSet1ChassisPartA",
		Introduced = "24.2",
		Link = "Exard Scaffold",
		Magazine = 100,
		Mastery = 0,
		MaxAmmo = math.huge,
		Name = "Exard Scaffold",
		Polarities = {
		},
		Reload = 5.33,
		ReloadDelay = 2,
		ReloadRate = 30,
		ReloadStyle = "Regenerate",
		Slot = "Amp",
		Traits = {
			"Sentient",
		},
		Trigger = "Burst",
		_TooltipAttackDisplay = "Attack2",
	},
	["Granmu Prism (Gilded)"] = {
		Accuracy = 100,
		AmmoType = "Energy",
		Attack1 = {
			AmmoCost = 5,
			AttackName = "Direct Hit",
			BurstCount = 3,
			CritChance = 0.26,
			CritMultiplier = 2,
			Damage = {
				Void = 1000,
			},
			FireRate = 2.07,
			IsSilent = false,
			Multishot = 1,
			PunchThrough = 0,
			ShotType = "Projectile",
			StatusChance = 0.12,
		},
		Attack5 = {
			AttackName = "Explosion",
			CritChance = 0.26,
			CritMultiplier = 2,
			Damage = {
				Void = 1400,
			},
			Falloff = {
				EndRange = 3.5,
				Reduction = 0.3,
				StartRange = 0,
			},
			FireRate = 2.07,
			IsSilent = false,
			Multishot = 1,
			PunchThrough = 0,
			Range = 3.5,
			ShotType = "AoE",
			StatusChance = 0.12,
		},
		Class = "Amp",
		Conclave = false,
		Image = "SentAmpSet1BarrelC.png",
		Introduced = "22",
		Link = "Granmu Prism",
		Magazine = 100,
		Mastery = 0,
		MaxAmmo = math.huge,
		Name = "Granmu Prism (Gilded)",
		Polarities = {
		},
		Reload = 5.33,
		ReloadDelay = 2,
		ReloadRate = 30,
		ReloadStyle = "Regenerate",
		Slot = "Amp",
		Traits = {
			"Sentient",
		},
		Trigger = "Burst",
	},
	["Granmu Prism"] = {
		Accuracy = 100,
		AmmoType = "Energy",
		Attack1 = {
			AmmoCost = 5,
			AttackName = "Direct Hit",
			BurstCount = 3,
			CritChance = 0.16,
			CritMultiplier = 1.5,
			Damage = {
				Void = 1000,
			},
			FireRate = 2.07,
			IsSilent = false,
			Multishot = 1,
			PunchThrough = 0,
			ShotType = "Projectile",
			StatusChance = 0.02,
		},
		Attack5 = {
			AttackName = "Explosion",
			CritChance = 0.16,
			CritMultiplier = 1.5,
			Damage = {
				Void = 1400,
			},
			Falloff = {
				EndRange = 3.5,
				Reduction = 0.3,
				StartRange = 0,
			},
			FireRate = 2.07,
			IsSilent = false,
			Multishot = 1,
			PunchThrough = 0,
			Range = 3.5,
			ShotType = "AoE",
			StatusChance = 0.02,
		},
		Class = "Amp",
		Conclave = false,
		Image = "SentAmpSet1BarrelC.png",
		InternalName = "/Lotus/Weapons/Sentients/OperatorAmplifiers/Set1/Barrel/SentAmpSet1BarrelPartC",
		Introduced = "22",
		Link = "Granmu Prism",
		Magazine = 100,
		Mastery = 0,
		MaxAmmo = math.huge,
		Name = "Granmu Prism",
		Polarities = {
		},
		Reload = 5.33,
		ReloadDelay = 2,
		ReloadRate = 30,
		ReloadStyle = "Regenerate",
		Slot = "Amp",
		Traits = {
			"Sentient",
		},
		Trigger = "Burst",
	},
	["Klamora Prism (Gilded)"] = {
		Accuracy = 100,
		AmmoType = "Energy",
		Attack1 = {
			AmmoCost = 30,
			AttackName = "Normal Attack",
			CritChance = 0.38,
			CritMultiplier = 2.4,
			Damage = {
				Void = 600,
			},
			FireRate = 12,
			IsSilent = false,
			Multishot = 1,
			PunchThrough = 0,
			Range = 13,
			ShotType = "Discharge",
			StatusChance = 0.1,
		},
		Class = "Amp",
		Conclave = false,
		Image = "KlamoraPrism.png",
		Introduced = "24.2",
		Link = "Klamora Prism",
		Magazine = 100,
		Mastery = 0,
		MaxAmmo = math.huge,
		Name = "Klamora Prism (Gilded)",
		Polarities = {
		},
		Reload = 5.33,
		ReloadDelay = 2,
		ReloadRate = 30,
		ReloadStyle = "Regenerate",
		Slot = "Amp",
		Traits = {
			"Sentient",
		},
		Trigger = "Held",
	},
	["Klamora Prism"] = {
		Accuracy = 100,
		AmmoType = "Energy",
		Attack1 = {
			AmmoCost = 30,
			AttackName = "Normal Attack",
			CritChance = 0.23,
			CritMultiplier = 1.9,
			Damage = {
				Void = 600,
			},
			FireRate = 12,
			IsSilent = false,
			Multishot = 1,
			PunchThrough = 0,
			Range = 13,
			ShotType = "Discharge",
			StatusChance = 0.05,
		},
		Class = "Amp",
		Conclave = false,
		Image = "KlamoraPrism.png",
		InternalName = "/Lotus/Weapons/Corpus/OperatorAmplifiers/Set1/Barrel/CorpAmpSet1BarrelPartC",
		Introduced = "24.2",
		Link = "Klamora Prism",
		Magazine = 100,
		Mastery = 0,
		MaxAmmo = math.huge,
		Name = "Klamora Prism",
		Polarities = {
		},
		Reload = 5.33,
		ReloadDelay = 2,
		ReloadRate = 30,
		ReloadStyle = "Regenerate",
		Slot = "Amp",
		Traits = {
			"Sentient",
		},
		Trigger = "Held",
	},
	["Klebrik Scaffold (Gilded)"] = {
		Accuracy = 100,
		AmmoType = "Energy",
		Attack1 = {
			AmmoCost = 3,
			AttackName = "Normal Attack",
			CritChance = 0.16,
			CritMultiplier = 1.6,
			Damage = {
				Void = 320,
			},
			FireRate = 12,
			IsSilent = false,
			Multishot = 1,
			PunchThrough = 0,
			Range = 25,
			ShotType = "Discharge",
			StatusChance = 0.14,
		},
		Class = "Amp",
		Conclave = false,
		Image = "SentAmpSet1ChassisC.png",
		Introduced = "22",
		Link = "Klebrik Scaffold",
		Magazine = 100,
		Mastery = 0,
		MaxAmmo = math.huge,
		Name = "Klebrik Scaffold (Gilded)",
		Polarities = {
		},
		Reload = 5.33,
		ReloadDelay = 2,
		ReloadRate = 30,
		ReloadStyle = "Regenerate",
		Slot = "Amp",
		Traits = {
			"Sentient",
		},
		Trigger = "Held",
	},
	["Klebrik Scaffold"] = {
		Accuracy = 100,
		AmmoType = "Energy",
		Attack1 = {
			AmmoCost = 3,
			AttackName = "Normal Attack",
			CritChance = 0.06,
			CritMultiplier = 1.1,
			Damage = {
				Void = 320,
			},
			FireRate = 12,
			IsSilent = false,
			Multishot = 1,
			PunchThrough = 0,
			Range = 25,
			ShotType = "Discharge",
			StatusChance = 0.04,
		},
		Class = "Amp",
		Conclave = false,
		Image = "SentAmpSet1ChassisC.png",
		InternalName = "/Lotus/Weapons/Sentients/OperatorAmplifiers/Set1/Chassis/SentAmpSet1ChassisPartC",
		Introduced = "22",
		Link = "Klebrik Scaffold",
		Magazine = 100,
		Mastery = 0,
		MaxAmmo = math.huge,
		Name = "Klebrik Scaffold",
		Polarities = {
		},
		Reload = 5.33,
		ReloadDelay = 2,
		ReloadRate = 30,
		ReloadStyle = "Regenerate",
		Slot = "Amp",
		Traits = {
			"Sentient",
		},
		Trigger = "Held",
	},
	["Lega Prism (Gilded)"] = {
		Accuracy = 100,
		AmmoType = "Energy",
		Attack1 = {
			AmmoCost = 6,
			AttackName = "Normal Attack",
			CritChance = 0.08,
			CritMultiplier = 1.6,
			Damage = {
				Void = 600,
			},
			FireRate = 7.5,
			IsSilent = false,
			Multishot = 1,
			PunchThrough = 0,
			Range = 28,
			ShotType = "Discharge",
			StatusChance = 0.34,
		},
		Class = "Amp",
		Conclave = false,
		Image = "LegaPrism.png",
		Introduced = "24.2",
		Link = "Lega Prism",
		Magazine = 100,
		Mastery = 0,
		MaxAmmo = math.huge,
		Name = "Lega Prism (Gilded)",
		Polarities = {
		},
		Reload = 5.33,
		ReloadDelay = 2,
		ReloadRate = 30,
		ReloadStyle = "Regenerate",
		Slot = "Amp",
		Traits = {
			"Sentient",
		},
		Trigger = "Held",
	},
	["Lega Prism"] = {
		Accuracy = 100,
		AmmoType = "Energy",
		Attack1 = {
			AmmoCost = 6,
			AttackName = "Normal Attack",
			CritChance = 0.04,
			CritMultiplier = 1.1,
			Damage = {
				Void = 600,
			},
			FireRate = 7.5,
			IsSilent = false,
			Multishot = 1,
			PunchThrough = 0,
			Range = 28,
			ShotType = "Discharge",
			StatusChance = 0.17,
		},
		Class = "Amp",
		Conclave = false,
		Image = "LegaPrism.png",
		InternalName = "/Lotus/Weapons/Corpus/OperatorAmplifiers/Set1/Barrel/CorpAmpSet1BarrelPartB",
		Introduced = "24.2",
		Link = "Lega Prism",
		Magazine = 100,
		Mastery = 0,
		MaxAmmo = math.huge,
		Name = "Lega Prism",
		Polarities = {
		},
		Reload = 5.33,
		ReloadDelay = 2,
		ReloadRate = 30,
		ReloadStyle = "Regenerate",
		Slot = "Amp",
		Traits = {
			"Sentient",
		},
		Trigger = "Held",
	},
	["Mote Amp (Gilded)"] = {
		Accuracy = 100,
		AmmoType = "Energy",
		Attack1 = {
			AmmoCost = 6,
			AttackName = "Normal Attack",
			CritChance = 0.2,
			CritMultiplier = 1.5,
			Damage = {
				Void = 240,
			},
			FireRate = 12,
			IsSilent = false,
			Multishot = 1,
			PunchThrough = 0,
			Range = 30,
			ShotType = "Discharge",
			StatusChance = 0,
		},
		Class = "Amp",
		Conclave = false,
		Image = "TrainingOperatorAmp.png",
		Introduced = "22",
		Link = "Mote Amp",
		Magazine = 100,
		Mastery = 0,
		MaxAmmo = math.huge,
		Name = "Mote Amp (Gilded)",
		Polarities = {
		},
		Reload = 5.33,
		ReloadDelay = 2,
		ReloadRate = 30,
		ReloadStyle = "Regenerate",
		Slot = "Amp",
		Traits = {
			"Sentient",
		},
		Trigger = "Held",
	},
	["Mote Amp"] = {
		Accuracy = 100,
		AmmoType = "Energy",
		Attack1 = {
			AmmoCost = 6,
			AttackName = "Normal Attack",
			CritChance = 0.2,
			CritMultiplier = 1.5,
			Damage = {
				Void = 240,
			},
			FireRate = 12,
			IsSilent = false,
			Multishot = 1,
			PunchThrough = 0,
			Range = 20,
			ShotType = "Discharge",
			StatusChance = 0,
		},
		Class = "Amp",
		Conclave = false,
		Image = "TrainingOperatorAmp.png",
		InternalName = "/Lotus/Weapons/Sentients/OperatorAmplifiers/SentTrainingAmplifier/SentAmpTrainingBarrel",
		Introduced = "22",
		Link = "Mote Amp",
		Magazine = 100,
		Mastery = 0,
		MaxAmmo = math.huge,
		Name = "Mote Amp",
		Polarities = {
		},
		Reload = 5.33,
		ReloadDelay = 2,
		ReloadRate = 30,
		ReloadStyle = "Regenerate",
		Slot = "Amp",
		Traits = {
			"Sentient",
		},
		Trigger = "Held",
	},
	["Pencha Scaffold (Gilded)"] = {
		Accuracy = 100,
		AmmoType = "Energy",
		Attack1 = {
			AmmoCost = 10,
			AttackName = "Direct Hit",
			ChargeTime = 0.8,
			CritChance = 0.14,
			CritMultiplier = 1.6,
			Damage = {
				Void = 4500,
			},
			FireRate = 2,
			IsSilent = false,
			Multishot = 1,
			PunchThrough = 2,
			Range = 40,
			ShotType = "Hit-Scan",
			StatusChance = 0.18,
		},
		Attack2 = {
			AttackName = "Area of Effect",
			CritChance = 0.14,
			CritMultiplier = 1.6,
			Damage = {
				Void = 4500,
			},
			Falloff = {
				EndRange = 1,
				Reduction = 0,
				StartRange = 0,
			},
			FireRate = 2,
			IsSilent = false,
			Multishot = 1,
			PunchThrough = 0,
			Range = 1,
			StatusChance = 0.18,
		},
		Class = "Amp",
		Conclave = false,
		Image = "SentAmpSet1ChassisA.png",
		Introduced = "22",
		Link = "Pencha Scaffold",
		Magazine = 100,
		Mastery = 0,
		MaxAmmo = math.huge,
		Name = "Pencha Scaffold (Gilded)",
		Polarities = {
		},
		Reload = 5.33,
		ReloadDelay = 2,
		ReloadRate = 30,
		ReloadStyle = "Regenerate",
		Slot = "Amp",
		Traits = {
			"Sentient",
		},
		Trigger = "Charge",
	},
	["Pencha Scaffold"] = {
		Accuracy = 100,
		AmmoType = "Energy",
		Attack1 = {
			AmmoCost = 10,
			AttackName = "Direct Hit",
			ChargeTime = 0.8,
			CritChance = 0.04,
			CritMultiplier = 1.1,
			Damage = {
				Void = 4500,
			},
			FireRate = 2,
			IsSilent = false,
			Multishot = 1,
			PunchThrough = 2,
			Range = 40,
			ShotType = "Hit-Scan",
			StatusChance = 0.08,
		},
		Attack2 = {
			AttackName = "Area of Effect",
			CritChance = 0.04,
			CritMultiplier = 1.1,
			Damage = {
				Void = 4500,
			},
			Falloff = {
				EndRange = 1,
				Reduction = 0,
				StartRange = 0,
			},
			FireRate = 2,
			IsSilent = false,
			Multishot = 1,
			PunchThrough = 0,
			Range = 1,
			ShotType = "AoE",
			StatusChance = 0.08,
		},
		Class = "Amp",
		Conclave = false,
		Image = "SentAmpSet1ChassisA.png",
		InternalName = "/Lotus/Weapons/Sentients/OperatorAmplifiers/Set1/Chassis/SentAmpSet1ChassisPartA",
		Introduced = "22",
		Link = "Pencha Scaffold",
		Magazine = 100,
		Mastery = 0,
		MaxAmmo = math.huge,
		Name = "Pencha Scaffold",
		Polarities = {
		},
		Reload = 5.33,
		ReloadDelay = 2,
		ReloadRate = 30,
		ReloadStyle = "Regenerate",
		Slot = "Amp",
		Traits = {
			"Sentient",
		},
		Trigger = "Charge",
	},
	["Phahd Scaffold (Gilded)"] = {
		Accuracy = 9.1,
		AmmoType = "Energy",
		Attack1 = {
			AmmoCost = 20,
			AttackName = "Direct Hit",
			CritChance = 0.34,
			CritMultiplier = 2.6,
			Damage = {
				Void = 3000,
			},
			FireRate = 1.67,
			IsSilent = false,
			Multishot = 1,
			PunchThrough = 0,
			Range = 300,
			ShotType = "Projectile",
			StatusChance = 0.12,
		},
		Attack5 = {
			AttackName = "Explosion",
			CritChance = 0.34,
			CritMultiplier = 2.6,
			Damage = {
				Void = 1100,
			},
			Falloff = {
				EndRange = 5,
				Reduction = 0.3,
				StartRange = 0,
			},
			FireRate = 1.67,
			IsSilent = false,
			Multishot = 1,
			PunchThrough = 0,
			Range = 5,
			ShotType = "AoE",
			StatusChance = 0.12,
		},
		Class = "Amp",
		Conclave = false,
		Image = "SentAmpSet2ChassisA.png",
		Introduced = "23.4",
		Link = "Phahd Scaffold",
		Magazine = 100,
		Mastery = 0,
		MaxAmmo = math.huge,
		Name = "Phahd Scaffold (Gilded)",
		Polarities = {
		},
		Reload = 5.33,
		ReloadDelay = 2,
		ReloadRate = 30,
		ReloadStyle = "Regenerate",
		Slot = "Amp",
		Traits = {
			"Sentient",
		},
		Trigger = "Semi-Auto",
	},
	["Phahd Scaffold"] = {
		Accuracy = 9.1,
		AmmoType = "Energy",
		Attack1 = {
			AmmoCost = 20,
			AttackName = "Direct Hit",
			CritChance = 0.24,
			CritMultiplier = 2.1,
			Damage = {
				Void = 3000,
			},
			FireRate = 1.67,
			IsSilent = false,
			Multishot = 1,
			PunchThrough = 0,
			Range = 300,
			ShotType = "Projectile",
			StatusChance = 0.02,
		},
		Attack5 = {
			AttackName = "Explosion",
			CritChance = 0.24,
			CritMultiplier = 2.1,
			Damage = {
				Void = 1100,
			},
			Falloff = {
				EndRange = 5,
				Reduction = 0.3,
				StartRange = 0,
			},
			FireRate = 1.67,
			IsSilent = false,
			Multishot = 1,
			PunchThrough = 0,
			Range = 5,
			ShotType = "AoE",
			StatusChance = 0.02,
		},
		Class = "Amp",
		Conclave = false,
		Image = "SentAmpSet2ChassisA.png",
		InternalName = "/Lotus/Weapons/Sentients/OperatorAmplifiers/Set2/Chassis/SentAmpSet2ChassisPartA",
		Introduced = "23.4",
		Link = "Phahd Scaffold",
		Magazine = 100,
		Mastery = 0,
		MaxAmmo = math.huge,
		Name = "Phahd Scaffold",
		Polarities = {
		},
		Reload = 5.33,
		ReloadDelay = 2,
		ReloadRate = 30,
		ReloadStyle = "Regenerate",
		Slot = "Amp",
		Traits = {
			"Sentient",
		},
		Trigger = "Semi-Auto",
	},
	["Propa Scaffold (Gilded)"] = {
		Accuracy = 9.1,
		AmmoType = "Energy",
		Attack1 = {
			AmmoCost = 40,
			AttackName = "Explosion",
			CritChance = 0.3,
			CritMultiplier = 2,
			Damage = {
				Void = 9000,
			},
			Falloff = {
				EndRange = 14,
				Reduction = 0.7,
				StartRange = 0,
			},
			FireRate = 2,
			IsSilent = false,
			Multishot = 1,
			PunchThrough = 0,
			Range = 14,
			ShotType = "AoE",
			StatusChance = 0,
		},
		Class = "Amp",
		Conclave = false,
		Image = "PropaScaffold.png",
		Introduced = "24.2",
		Link = "Propa Scaffold",
		Magazine = 100,
		Mastery = 0,
		MaxAmmo = math.huge,
		Name = "Propa Scaffold (Gilded)",
		Polarities = {
		},
		Reload = 5.33,
		ReloadDelay = 2,
		ReloadRate = 30,
		ReloadStyle = "Regenerate",
		Slot = "Amp",
		Traits = {
			"Sentient",
		},
		Trigger = "Semi-Auto",
	},
	["Propa Scaffold"] = {
		Accuracy = 9.1,
		AmmoType = "Energy",
		Attack1 = {
			AmmoCost = 40,
			AttackName = "Explosion",
			CritChance = 0.15,
			CritMultiplier = 1.5,
			Damage = {
				Void = 9000,
			},
			Falloff = {
				EndRange = 14,
				Reduction = 0.7,
				StartRange = 0,
			},
			FireRate = 2,
			IsSilent = false,
			Multishot = 1,
			PunchThrough = 0,
			Range = 14,
			ShotType = "AoE",
			StatusChance = 0,
		},
		Class = "Amp",
		Conclave = false,
		Image = "PropaScaffold.png",
		InternalName = "/Lotus/Weapons/Corpus/OperatorAmplifiers/Set1/Chassis/CorpAmpSet1ChassisPartC",
		Introduced = "24.2",
		Link = "Propa Scaffold",
		Magazine = 100,
		Mastery = 0,
		MaxAmmo = math.huge,
		Name = "Propa Scaffold",
		Polarities = {
		},
		Reload = 5.33,
		ReloadDelay = 2,
		ReloadRate = 30,
		ReloadStyle = "Regenerate",
		Slot = "Amp",
		Traits = {
			"Sentient",
		},
		Trigger = "Semi-Auto",
	},
	["Rahn Prism (Gilded)"] = {
		Accuracy = 32,
		AmmoType = "Energy",
		Attack1 = {
			AmmoCost = 3,
			AttackName = "Normal Attack",
			CritChance = 0.3,
			CritMultiplier = 2,
			Damage = {
				Void = 1000,
			},
			FireRate = 5.67,
			IsSilent = false,
			Multishot = 1,
			PunchThrough = 0,
			ShotType = "Projectile",
			StatusChance = 0.04,
		},
		Class = "Amp",
		Conclave = false,
		Image = "SentAmpSet2BarrelA.png",
		Introduced = "22",
		Link = "Rahn Prism",
		Magazine = 100,
		Mastery = 0,
		MaxAmmo = math.huge,
		Name = "Rahn Prism (Gilded)",
		Polarities = {
		},
		Reload = 5.33,
		ReloadDelay = 2,
		ReloadRate = 30,
		ReloadStyle = "Regenerate",
		Slot = "Amp",
		Traits = {
			"Sentient",
		},
		Trigger = "Auto",
	},
	["Rahn Prism"] = {
		Accuracy = 32,
		AmmoType = "Energy",
		Attack1 = {
			AmmoCost = 3,
			AttackName = "Normal Attack",
			CritChance = 0.2,
			CritMultiplier = 1.5,
			Damage = {
				Void = 1000,
			},
			FireRate = 5.67,
			IsSilent = false,
			Multishot = 1,
			PunchThrough = 0,
			ShotType = "Projectile",
			StatusChance = 0,
		},
		Class = "Amp",
		Conclave = false,
		Image = "SentAmpSet2BarrelA.png",
		InternalName = "/Lotus/Weapons/Sentients/OperatorAmplifiers/Set2/Barrel/SentAmpSet2BarrelPartA",
		Introduced = "23.4",
		Link = "Rahn Prism",
		Magazine = 100,
		Mastery = 0,
		MaxAmmo = math.huge,
		Name = "Rahn Prism",
		Polarities = {
		},
		Reload = 5.33,
		ReloadDelay = 2,
		ReloadRate = 30,
		ReloadStyle = "Regenerate",
		Slot = "Amp",
		Traits = {
			"Sentient",
		},
		Trigger = "Auto",
	},
	["Raplak Prism (Gilded)"] = {
		Accuracy = 32,
		AmmoType = "Energy",
		Attack1 = {
			AmmoCost = 10,
			AttackName = "Normal Attack",
			CritChance = 0.38,
			CritMultiplier = 2.6,
			Damage = {
				Void = 3000,
			},
			FireRate = 2,
			IsSilent = false,
			Multishot = 1,
			PunchThrough = 0,
			Range = 300,
			ShotType = "Hit-Scan",
			StatusChance = 0.1,
		},
		Class = "Amp",
		Conclave = false,
		Image = "SentAmpSet1BarrelA.png",
		Introduced = "22",
		Link = "Raplak Prism",
		Magazine = 100,
		Mastery = 0,
		MaxAmmo = math.huge,
		Name = "Raplak Prism (Gilded)",
		Polarities = {
		},
		Reload = 5.33,
		ReloadDelay = 2,
		ReloadRate = 30,
		ReloadStyle = "Regenerate",
		Slot = "Amp",
		Traits = {
			"Sentient",
		},
		Trigger = "Semi-Auto",
	},
	["Raplak Prism"] = {
		Accuracy = 32,
		AmmoType = "Energy",
		Attack1 = {
			AmmoCost = 10,
			AttackName = "Normal Attack",
			CritChance = 0.28,
			CritMultiplier = 2.1,
			Damage = {
				Void = 3000,
			},
			FireRate = 2,
			IsSilent = false,
			Multishot = 1,
			PunchThrough = 0,
			Range = 300,
			ShotType = "Hit-Scan",
			StatusChance = 0,
		},
		Class = "Amp",
		Conclave = false,
		Image = "SentAmpSet1BarrelA.png",
		Introduced = "22",
		Link = "Raplak Prism",
		Magazine = 100,
		Mastery = 0,
		MaxAmmo = math.huge,
		Name = "Raplak Prism",
		Polarities = {
		},
		Reload = 5.33,
		ReloadDelay = 2,
		ReloadRate = 30,
		ReloadStyle = "Regenerate",
		Slot = "Amp",
		Traits = {
			"Sentient",
		},
		Trigger = "Semi-Auto",
	},
	["Shraksun Scaffold (Gilded)"] = {
		Accuracy = 9.1,
		AmmoType = "Energy",
		Attack1 = {
			AmmoCost = 10,
			AttackName = "Direct Hit",
			CritChance = 0.2,
			CritMultiplier = 2,
			Damage = {
				Void = 3000,
			},
			FireRate = 1.33,
			IsSilent = false,
			Multishot = 1,
			PunchThrough = 0,
			Range = 10,
			ShotType = "Projectile",
			StatusChance = 0.2,
		},
		Attack2 = {
			AttackName = "Explosion",
			CritChance = 0.2,
			CritMultiplier = 2,
			Damage = {
				Void = 4500,
			},
			Falloff = {
				EndRange = 7,
				Reduction = 0.4,
				StartRange = 0,
			},
			FireRate = 1.33,
			IsSilent = false,
			Multishot = 1,
			PunchThrough = 0,
			Range = 7,
			ShotType = "AoE",
			StatusChance = 0.2,
		},
		Class = "Amp",
		Conclave = false,
		Image = "SentAmpSet1ChassisB.png",
		Introduced = "22",
		Link = "Shraksun Scaffold",
		Magazine = 100,
		Mastery = 0,
		MaxAmmo = math.huge,
		Name = "Shraksun Scaffold (Gilded)",
		Polarities = {
		},
		Reload = 5.33,
		ReloadDelay = 2,
		ReloadRate = 30,
		ReloadStyle = "Regenerate",
		Slot = "Amp",
		Traits = {
			"Sentient",
		},
		Trigger = "Semi-Auto",
	},
	["Shraksun Scaffold"] = {
		Accuracy = 9.1,
		AmmoType = "Energy",
		Attack1 = {
			AmmoCost = 10,
			AttackName = "Direct Hit",
			CritChance = 0.1,
			CritMultiplier = 1.5,
			Damage = {
				Void = 3000,
			},
			FireRate = 1.33,
			IsSilent = false,
			Multishot = 1,
			PunchThrough = 0,
			Range = 10,
			ShotType = "Projectile",
			StatusChance = 0.1,
		},
		Attack2 = {
			AttackName = "Explosion",
			CritChance = 0.1,
			CritMultiplier = 1.5,
			Damage = {
				Void = 4500,
			},
			Falloff = {
				EndRange = 7,
				Reduction = 0.4,
				StartRange = 0,
			},
			FireRate = 1.33,
			IsSilent = false,
			Multishot = 1,
			PunchThrough = 0,
			Range = 7,
			ShotType = "AoE",
			StatusChance = 0.1,
		},
		Class = "Amp",
		Conclave = false,
		Image = "SentAmpSet1ChassisB.png",
		InternalName = "/Lotus/Weapons/Sentients/OperatorAmplifiers/Set1/Chassis/SentAmpSet1ChassisPartB",
		Introduced = "22",
		Link = "Shraksun Scaffold",
		Magazine = 100,
		Mastery = 0,
		MaxAmmo = math.huge,
		Name = "Shraksun Scaffold",
		Polarities = {
		},
		Reload = 5.33,
		ReloadDelay = 2,
		ReloadRate = 30,
		ReloadStyle = "Regenerate",
		Slot = "Amp",
		Traits = {
			"Sentient",
		},
		Trigger = "Semi-Auto",
	},
	["Shwaak Prism (Gilded)"] = {
		Accuracy = 9.1,
		AmmoType = "Energy",
		Attack1 = {
			AmmoCost = 10,
			AttackName = "Normal Attack",
			CritChance = 0.1,
			CritMultiplier = 1.6,
			Damage = {
				Void = 3500,
			},
			Falloff = {
				EndRange = 25,
				Reduction = 0.54,
				StartRange = 16,
			},
			FireRate = 1.33,
			IsSilent = false,
			Multishot = 1,
			PunchThrough = 0,
			Range = 32.5,
			ShotType = "Projectile",
			StatusChance = 0.2,
		},
		Class = "Amp",
		Conclave = false,
		Image = "SentAmpSet1BarrelB.png",
		Introduced = "22",
		Link = "Shwaak Prism",
		Magazine = 100,
		Mastery = 0,
		MaxAmmo = math.huge,
		Name = "Shwaak Prism (Gilded)",
		Polarities = {
		},
		Reload = 5.33,
		ReloadDelay = 2,
		ReloadRate = 30,
		ReloadStyle = "Regenerate",
		Slot = "Amp",
		Traits = {
			"Sentient",
		},
		Trigger = "Semi-Auto",
	},
	["Shwaak Prism"] = {
		Accuracy = 9.1,
		AmmoType = "Energy",
		Attack1 = {
			AmmoCost = 10,
			AttackName = "Normal Attack",
			CritChance = 0,
			CritMultiplier = 1.1,
			Damage = {
				Void = 3500,
			},
			Falloff = {
				EndRange = 25,
				Reduction = 0.54,
				StartRange = 16,
			},
			FireRate = 1.33,
			IsSilent = false,
			Multishot = 1,
			PunchThrough = 0,
			Range = 32.5,
			ShotType = "Projectile",
			StatusChance = 0.1,
		},
		Class = "Amp",
		Conclave = false,
		Image = "SentAmpSet1BarrelB.png",
		InternalName = "/Lotus/Weapons/Sentients/OperatorAmplifiers/Set1/Barrel/SentAmpSet1BarrelPartB",
		Introduced = "22",
		Link = "Shwaak Prism",
		Magazine = 100,
		Mastery = 0,
		MaxAmmo = math.huge,
		Name = "Shwaak Prism",
		Polarities = {
		},
		Reload = 5.33,
		ReloadDelay = 2,
		ReloadRate = 30,
		ReloadStyle = "Regenerate",
		Slot = "Amp",
		Traits = {
			"Sentient",
		},
		Trigger = "Semi-Auto",
	},
	Sirocco = {
		Accuracy = 16,
		Attack1 = {
			AttackName = "Normal Attack",
			CritChance = 0.4,
			CritMultiplier = 2,
			Damage = {
				Void = 2000,
			},
			FireRate = 3,
			IsSilent = true,
			Multishot = 1,
			PunchThrough = 0,
			Reload = 2,
			ShotType = "Projectile",
			StatusChance = 0.2,
		},
		Attack2 = {
			AttackName = "Overcharged Shot",
			CritChance = 0.8,
			CritMultiplier = 2,
			Damage = {
				Void = 3600,
			},
			FireRate = 0.833,
			IsSilent = true,
			Multishot = 1,
			PunchThrough = 0,
			Reload = 0.5,
			ShotType = "Projectile",
			StatusChance = 0.5,
		},
		Class = "Amp",
		Conclave = false,
		Image = "Sirocco.png",
		InternalName = "/Lotus/Weapons/Operator/Pistols/DrifterPistol",
		Introduced = "31",
		Link = "Sirocco",
		Magazine = 10,
		Mastery = 0,
		MaxAmmo = math.huge,
		Name = "Sirocco",
		Reload = 2,
		Slot = "Amp",
		Traits = {
			"Sentient",
		},
		Trigger = "Semi-Auto",
	},

------------------------------------Kitguns-------------------------------------
	Catchmoon = {
		Accuracy = 5.9,
		AmmoType = "Pistol",
		Attack1 = {
			AttackName = "Normal Attack",
			CritChance = 0,
			CritMultiplier = 0,
			Damage = {
				Heat = 0,
				Impact = 0,
			},
			ExtraHeadshotDmg = -2,
			Falloff = {
				EndRange = 16,
				Reduction = 0.9375,
				StartRange = 8,
			},
			FireRate = 0,
			ForcedProcs = {
				"Impact",
			},
			IsSilent = false,
			Multishot = 1,
			PunchThrough = 0,
			Range = 20,
			ShotSpeed = 100,
			ShotType = "Projectile",
			StatusChance = 0,
		},
		Class = "Kitgun Pistol",
		Conclave = false,
		Disposition = 0.5,
		ExilusPolarity = "Madurai",
		Image = "KitgunChamberCatchmoon.png",
		InternalName = "/Lotus/Weapons/SolarisUnited/Secondary/SUModularSecondarySet1/Barrel/SUModularSecondaryBarrelAPart",
		Introduced = "24",
		Link = "Catchmoon",
		Magazine = 0,
		MaxAmmo = 70,
		Name = "Catchmoon (Secondary)",
		Reload = 0,
		Slot = "Secondary",
		Trigger = "Semi-Auto",
	},
	Gaze = {
		Accuracy = 100,
		AmmoType = "Pistol",
		Attack1 = {
			AmmoCost = 0.5,
			AttackName = "Normal Attack",
			CritChance = 0,
			CritMultiplier = 0,
			Damage = {
				Puncture = 0,
				Radiation = 0,
			},
			FireRate = 0,
			IsSilent = false,
			Multishot = 1,
			PunchThrough = 0,
			Range = 0,
			ShotType = "Discharge",
			StatusChance = 0,
		},
		Class = "Kitgun Pistol",
		Conclave = false,
		Disposition = 0.9,
		ExilusPolarity = "Madurai",
		Image = "KitgunChamberGaze.png",
		InternalName = "/Lotus/Weapons/SolarisUnited/Secondary/SUModularSecondarySet1/Barrel/SUModularSecondaryBarrelDPart",
		Introduced = "24",
		Link = "Gaze",
		Magazine = 0,
		MaxAmmo = 400,
		Name = "Gaze (Secondary)",
		Reload = 0,
		Slot = "Secondary",
		Trigger = "Held",
	},
	Rattleguts = {
		Accuracy = 20,
		AmmoType = "Pistol",
		Attack1 = {
			AttackName = "Normal Attack",
			CritChance = 0,
			CritMultiplier = 0,
			Damage = {
				Puncture = 0,
				Radiation = 0,
				Slash = 0,
			},
			FireRate = 0,
			IsSilent = false,
			Multishot = 1,
			PunchThrough = 0,
			Range = 0,
			ShotType = "Hit-Scan",
			StatusChance = 0,
		},
		Class = "Kitgun Pistol",
		Conclave = false,
		Disposition = 0.75,
		ExilusPolarity = "Madurai",
		Image = "KitgunChamberRattleguts.png",
		InternalName = "/Lotus/Weapons/SolarisUnited/Secondary/SUModularSecondarySet1/Barrel/SUModularSecondaryBarrelCPart",
		Introduced = "24",
		Link = "Rattleguts",
		Magazine = 0,
		MaxAmmo = 700,
		Name = "Rattleguts (Secondary)",
		Reload = 0,
		Slot = "Secondary",
		Trigger = "Auto",
	},
	Sporelacer = {
		Accuracy = 5.9,
		AmmoType = "Pistol",
		Attack1 = {
			AttackName = "Normal Attack",
			CritChance = 0,
			CritMultiplier = 0,
			Damage = {
				Impact = 0,
			},
			Falloff = {
				EndRange = 26,
				Reduction = 0,
				StartRange = 13,
			},
			FireRate = 0,
			IsSilent = false,
			Multishot = 1,
			PunchThrough = 0,
			ShotSpeed = 57,
			ShotType = "Projectile",
			StatusChance = 0,
		},
		Attack2 = {
			AttackName = "Explosion",
			CritChance = 0,
			CritMultiplier = 0,
			Damage = {
				Toxin = 0,
			},
			Falloff = {
				EndRange = 4.7,
				Reduction = 0.5,
				StartRange = 0,
			},
			IsSilent = false,
			Multishot = 1,
			PunchThrough = 0,
			Range = 4.7,
			ShotType = "AoE",
			StatusChance = 0,
		},
		Attack3 = {
			AttackName = "Bomblet Impact",
			CritChance = 0,
			CritMultiplier = 0,
			Damage = {
				Toxin = 0,
			},
			IsSilent = false,
			Multishot = 1,
			PunchThrough = 0,
			ShotSpeed = 3,
			ShotType = "Projectile",
			StatusChance = 0,
		},
		Attack4 = {
			AttackName = "Bomblet Explosion",
			CritChance = 0,
			CritMultiplier = 0,
			Damage = {
				Toxin = 0,
			},
			Falloff = {
				EndRange = 2.1,
				Reduction = 0.8,
				StartRange = 0,
			},
			IsSilent = false,
			Multishot = 1,
			PunchThrough = 0,
			Range = 2.1,
			ShotType = "AoE",
			StatusChance = 0,
		},
		Class = "Kitgun Pistol",
		Conclave = false,
		Disposition = 0.55,
		ExilusPolarity = "Madurai",
		Image = "KitgunChamberSporelacer.png",
		InternalName = "/Lotus/Weapons/Infested/Pistols/InfKitGun/Barrels/InfBarrelEgg/InfModularBarrelEggPart",
		Introduced = "29.5",
		Link = "Sporelacer",
		Magazine = 0,
		MaxAmmo = 130,
		Name = "Sporelacer (Secondary)",
		Polarities = {
		},
		Reload = 0,
		Slot = "Secondary",
		Traits = {
			"Infested",
		},
		Trigger = "Semi-Auto",
	},
	Tombfinger = {
		Accuracy = 50,
		AmmoType = "Pistol",
		Attack1 = {
			AttackName = "Normal Attack",
			CritChance = 0,
			CritMultiplier = 0,
			Damage = {
				Impact = 0,
				Puncture = 0,
				Radiation = 0,
			},
			FireRate = 0,
			ForcedProcs = {
				"Impact",
			},
			IsSilent = false,
			Multishot = 1,
			PunchThrough = 0,
			ShotSpeed = 180,
			ShotType = "Projectile",
			StatusChance = 0,
		},
		Attack2 = {
			AttackName = "Explosion",
			CritChance = 0,
			CritMultiplier = 0,
			Damage = {
				Radiation = 0,
			},
			Falloff = {
				EndRange = 1.9,
				Reduction = 0.3,
				StartRange = 0,
			},
			IsSilent = false,
			Multishot = 1,
			PunchThrough = 0,
			Range = 1.9,
			ShotType = "AoE",
			StatusChance = 0,
		},
		Class = "Kitgun Pistol",
		Conclave = false,
		Disposition = 0.65,
		ExilusPolarity = "Madurai",
		Image = "KitgunChamberTombfinger.png",
		InternalName = "/Lotus/Weapons/SolarisUnited/Secondary/SUModularSecondarySet1/Barrel/SUModularSecondaryBarrelBPart",
		Introduced = "24",
		Link = "Tombfinger",
		Magazine = 0,
		MaxAmmo = 540,
		Name = "Tombfinger (Secondary)",
		Reload = 0,
		Slot = "Secondary",
		Trigger = "Semi-Auto",
	},
	Vermisplicer = {
		Accuracy = 5.4,
		AmmoType = "Pistol",
		Attack1 = {
			AmmoCost = 0.5,
			AttackName = "Normal Attack",
			CritChance = 0,
			CritMultiplier = 0,
			Damage = {
				Impact = 0,
				Puncture = 0,
				Slash = 0,
				Toxin = 0,
			},
			FireRate = 0,
			IsSilent = false,
			Multishot = 5,
			PunchThrough = 1,
			ShotType = "Discharge",
			StatusChance = 0,
		},
		Class = "Kitgun Pistol",
		Conclave = false,
		Disposition = 1,
		ExilusPolarity = "Madurai",
		Image = "KitgunChamberVermisplicer.png",
		InternalName = "/Lotus/Weapons/Infested/Pistols/InfKitGun/Barrels/InfBarrelBeam/InfModularBarrelBeamPart",
		Introduced = "29.5",
		Link = "Vermisplicer",
		Magazine = 0,
		MaxAmmo = 226,
		Name = "Vermisplicer (Secondary)",
		Reload = 0,
		Slot = "Secondary",
		Trigger = "Held",
	},
	["Catchmoon (Primary)"] = {
		Accuracy = 22.2,
		AmmoType = "Rifle",
		Attack1 = {
			AttackName = "Normal Attack",
			CritChance = 0,
			CritMultiplier = 0,
			Damage = {
				Heat = 0,
				Impact = 0,
			},
			ExtraHeadshotDmg = -2,
			Falloff = {
				EndRange = 40,
				Reduction = 0.9416,
				StartRange = 20,
			},
			FireRate = 0,
			ForcedProcs = {
				"Impact",
			},
			IsSilent = false,
			Multishot = 1,
			PunchThrough = 0,
			Range = 42,
			ShotSpeed = 100,
			ShotType = "Projectile",
			StatusChance = 0,
		},
		Class = "Kitgun Rifle",
		Conclave = false,
		Disposition = 1.05,
		ExilusPolarity = "Madurai",
		Image = "KitgunChamberCatchmoon.png",
		Introduced = "28",
		Link = "Catchmoon",
		Magazine = 0,
		MaxAmmo = 70,
		Name = "Catchmoon (Primary)",
		Reload = 0,
		Slot = "Primary",
		Trigger = "Auto",
	},
	["Gaze (Primary)"] = {
		Accuracy = 100,
		AmmoType = "Rifle",
		Attack1 = {
			AmmoCost = 0.5,
			AttackName = "Normal Attack",
			CritChance = 0,
			CritMultiplier = 0,
			Damage = {
				Radiation = 0,
			},
			FireRate = 0,
			IsSilent = false,
			Multishot = 1,
			PunchThrough = 0,
			Range = 0,
			ShotType = "Discharge",
			StatusChance = 0,
		},
		Attack5 = {
			AttackName = "Area of Effect",
			CritChance = 0,
			CritMultiplier = 0,
			Damage = {
				Radiation = 0,
			},
			Falloff = {
				EndRange = 3,
				Reduction = 0,
				StartRange = 0,
			},
			IsSilent = false,
			Multishot = 1,
			PunchThrough = 0,
			Range = 3,
			StatusChance = 0,
		},
		Class = "Kitgun Rifle",
		Conclave = false,
		Disposition = 1.05,
		ExilusPolarity = "Madurai",
		Image = "KitgunChamberGaze.png",
		Introduced = "28",
		Link = "Gaze",
		Magazine = 0,
		MaxAmmo = 400,
		Name = "Gaze (Primary)",
		Reload = 0,
		Slot = "Primary",
		Trigger = "Held",
	},
	["Rattleguts (Primary)"] = {
		Accuracy = 20,
		AmmoType = "Rifle",
		Attack1 = {
			AttackName = "Normal Attack",
			CritChance = 0,
			CritMultiplier = 0,
			Damage = {
				Impact = 0,
				Puncture = 0,
				Radiation = 0,
				Slash = 0,
			},
			FireRate = 0,
			IsSilent = false,
			Multishot = 1,
			PunchThrough = 0,
			Range = 0,
			ShotType = "Hit-Scan",
			StatusChance = 0,
		},
		Class = "Kitgun Rifle",
		Conclave = false,
		Disposition = 1,
		ExilusPolarity = "Madurai",
		Image = "KitgunChamberRattleguts.png",
		Introduced = "28",
		Link = "Rattleguts",
		Magazine = 0,
		MaxAmmo = 700,
		Name = "Rattleguts (Primary)",
		Reload = 0,
		Slot = "Primary",
		Trigger = "Auto",
	},
	["Sporelacer (Primary)"] = {
		Accuracy = 5.9,
		AmmoType = "Shotgun",
		Attack1 = {
			AttackName = "Normal Attack",
			CritChance = 0,
			CritMultiplier = 0,
			Damage = {
				Impact = 0,
				Puncture = 0,
				Slash = 0,
			},
			Falloff = {
				EndRange = 16,
				Reduction = 0,
				StartRange = 8,
			},
			FireRate = 0,
			IsSilent = false,
			Multishot = 1,
			PunchThrough = 0,
			ShotSpeed = 50,
			ShotType = "Projectile",
			StatusChance = 0,
		},
		Attack5 = {
			AttackName = "Explosion",
			CritChance = 0,
			CritMultiplier = 0,
			Damage = {
				Toxin = 0,
			},
			Falloff = {
				EndRange = 2.1,
				Reduction = 0.2,
				StartRange = 0,
			},
			IsSilent = false,
			Multishot = 1,
			PunchThrough = 0,
			Range = 2.1,
			ShotType = "AoE",
			StatusChance = 0,
		},
		Class = "Kitgun Shotgun",
		Conclave = false,
		Disposition = 1,
		ExilusPolarity = "Madurai",
		Image = "KitgunChamberSporelacer.png",
		Introduced = "29.5",
		Link = "Sporelacer",
		Magazine = 0,
		MaxAmmo = 130,
		Name = "Sporelacer (Primary)",
		Polarities = {
		},
		Reload = 0,
		Slot = "Primary",
		Traits = {
			"Infested",
		},
		Trigger = "Auto",
	},
	["Tombfinger (Primary)"] = {
		Accuracy = 50,
		AmmoType = "Rifle",
		Attack1 = {
			AttackName = "Normal Attack",
			CritChance = 0,
			CritMultiplier = 0,
			Damage = {
				Impact = 0,
				Radiation = 0,
			},
			FireRate = 0,
			ForcedProcs = {
				"Impact",
			},
			IsSilent = false,
			Multishot = 1,
			PunchThrough = 0,
			ShotSpeed = 90,
			ShotType = "Projectile",
			StatusChance = 0,
		},
		Attack2 = {
			AttackName = "Quick Shot Explosion",
			CritChance = 0,
			CritMultiplier = 0,
			Damage = {
				Radiation = 0,
			},
			Falloff = {
				EndRange = 1.7,
				Reduction = 0.25,
				StartRange = 0,
			},
			IsSilent = false,
			Multishot = 1,
			PunchThrough = 0,
			Range = 1.7,
			ShotType = "AoE",
			StatusChance = 0,
		},
		Attack3 = {
			AttackName = "Charged Shot Explosion",
			CritChance = 0,
			CritMultiplier = 0,
			Damage = {
				Radiation = 0,
			},
			Falloff = {
				EndRange = 6.2,
				Reduction = 0.7,
				StartRange = 0,
			},
			IsSilent = false,
			Multishot = 1,
			PunchThrough = 0,
			Range = 6.2,
			ShotType = "AoE",
			StatusChance = 0,
		},
		Class = "Kitgun Launcher",
		Conclave = false,
		Disposition = 0.9,
		ExilusPolarity = "Madurai",
		Image = "KitgunChamberTombfinger.png",
		Introduced = "28",
		Link = "Tombfinger",
		Magazine = 0,
		MaxAmmo = 540,
		Name = "Tombfinger (Primary)",
		Reload = 0,
		Slot = "Primary",
		Trigger = "Charge",
	},
	["Vermisplicer (Primary)"] = {
		Accuracy = 80,
		AmmoType = "Rifle",
		Attack1 = {
			AmmoCost = 0.5,
			AttackName = "Normal Attack",
			CritChance = 0,
			CritMultiplier = 0,
			Damage = {
				Impact = 0,
				Puncture = 0,
				Slash = 0,
				Toxin = 0,
			},
			FireRate = 0,
			IsSilent = false,
			Multishot = 1,
			PunchThrough = 0,
			ShotType = "Discharge",
			StatusChance = 0,
		},
		Attack2 = {
			AttackName = "Tendril",
			CritChance = 0,
			CritMultiplier = 0,
			Damage = {
				Impact = 0,
				Puncture = 0,
				Slash = 0,
				Toxin = 0,
			},
			FireRate = 0,
			IsSilent = false,
			Multishot = 1,
			PunchThrough = 0,
			Range = 6,
			ShotType = "Discharge",
			StatusChance = 0,
		},
		Class = "Kitgun Rifle",
		Conclave = false,
		Disposition = 0.85,
		ExilusPolarity = "Madurai",
		Image = "KitgunChamberVermisplicer.png",
		Introduced = "29.5",
		Link = "Vermisplicer",
		Magazine = 0,
		MaxAmmo = 226,
		Name = "Vermisplicer (Primary)",
		Reload = 0,
		Slot = "Primary",
		Trigger = "Held",
	},

---------------------------------Zaws-------------------------------------------
	["Plague Keewar"] = {
		Attack1 = {
			AttackName = "Plague Keewar Strike (Gilded)",
			CritChance = 0.18,
			CritMultiplier = 2,
			Damage = {
				Impact = 88,
				Puncture = 57,
				Slash = 91,
				Viral = 70,
			},
			FireRate = 0.88,
			IsSilent = true,
			StatusChance = 0.22,
		},
		Class = "Zaw Scythe / Staff",
		Conclave = false,
		Disposition = 0.75,
		Image = "PlagueKeewar.png",
		InternalName = "/Lotus/Weapons/Ostron/Melee/ModularMeleeInfested/Tips/InfestedTipTwo",
		Introduced = "22.3",
		Link = "Plague Keewar",
		MeleeRange = 1,
		Name = "Plague Keewar",
		Slot = "Melee",
	},
	["Plague Kripath"] = {
		Attack1 = {
			AttackName = "Plague Kripath Strike (Gilded)",
			CritChance = 0.22,
			CritMultiplier = 2.2,
			Damage = {
				Impact = 30,
				Puncture = 70,
				Slash = 49,
				Viral = 64,
			},
			FireRate = 0.95,
			IsSilent = true,
			StatusChance = 0.18,
		},
		Class = "Zaw Rapier / Polearm",
		Conclave = false,
		Disposition = 0.6,
		Image = "PlagueKripath.png",
		InternalName = "/Lotus/Weapons/Ostron/Melee/ModularMeleeInfested/Tips/InfestedTipOne",
		Introduced = "22.3",
		Link = "Plague Kripath",
		MeleeRange = 1,
		Name = "Plague Kripath",
		Slot = "Melee",
	},
	Balla = {
		Attack1 = {
			AttackName = "Balla Strike (Gilded)",
			CritChance = 0.18,
			CritMultiplier = 2,
			Damage = {
				Impact = 11.2,
				Puncture = 134.4,
				Slash = 78.4,
			},
			FireRate = 1,
			IsSilent = true,
			StatusChance = 0.18,
		},
		Class = "Zaw Dagger / Staff",
		Conclave = false,
		Disposition = 0.9,
		Image = "ZawStrikeBalla.png",
		InternalName = "/Lotus/Weapons/Ostron/Melee/ModularMelee01/Tip/TipOne",
		Introduced = "22",
		Link = "Balla",
		MeleeRange = 1,
		Name = "Balla",
		Slot = "Melee",
	},
	Cyath = {
		Attack1 = {
			AttackName = "Cyath Strike (Gilded)",
			CritChance = 0.18,
			CritMultiplier = 2,
			Damage = {
				Impact = 46,
				Puncture = 11.5,
				Slash = 172.5,
			},
			FireRate = 0.92,
			IsSilent = true,
			StatusChance = 0.18,
		},
		Class = "Zaw Machete / Polearm",
		Conclave = false,
		Disposition = 0.9,
		Image = "ZawStrikeCyath.png",
		InternalName = "/Lotus/Weapons/Ostron/Melee/ModularMelee01/Tip/TipFour",
		Introduced = "22",
		Link = "Cyath",
		MeleeRange = 1,
		Name = "Cyath",
		Slot = "Melee",
	},
	Dehtat = {
		Attack1 = {
			AttackName = "Dehtat Strike (Gilded)",
			CritChance = 0.18,
			CritMultiplier = 2,
			Damage = {
				Impact = 22.4,
				Puncture = 112,
				Slash = 89.6,
			},
			FireRate = 0.92,
			IsSilent = true,
			StatusChance = 0.18,
		},
		Class = "Zaw Rapier / Polearm",
		Conclave = false,
		Disposition = 1.2,
		Image = "ZawStrikeDehtat.png",
		InternalName = "/Lotus/Weapons/Ostron/Melee/ModularMelee01/Tip/TipFive",
		Introduced = "22",
		Link = "Dehtat",
		MeleeRange = 1,
		Name = "Dehtat",
		Slot = "Melee",
	},
	Dokrahm = {
		Attack1 = {
			AttackName = "Dokrahm Strike (Gilded)",
			CritChance = 0.18,
			CritMultiplier = 2,
			Damage = {
				Impact = 46.4,
				Puncture = 108.1,
				Slash = 154.5,
			},
			FireRate = 1,
			IsSilent = true,
			StatusChance = 0.18,
		},
		Class = "Zaw Scythe / Heavy Blade",
		Conclave = false,
		Disposition = 0.75,
		Image = "ZawStrikeDokrahm.png",
		InternalName = "/Lotus/Weapons/Ostron/Melee/ModularMelee02/Tip/TipEleven",
		Introduced = "22.18",
		Link = "Dokrahm",
		MeleeRange = 1,
		Name = "Dokrahm",
		Slot = "Melee",
	},
	Kronsh = {
		Attack1 = {
			AttackName = "Kronsh Strike (Gilded)",
			CritChance = 0.18,
			CritMultiplier = 2,
			Damage = {
				Impact = 163.8,
				Puncture = 70.2,
			},
			FireRate = 0.85,
			IsSilent = true,
			StatusChance = 0.18,
		},
		Class = "Zaw Machete / Polearm",
		Conclave = false,
		Disposition = 1.3,
		Image = "ZawStrikeKronsh.png",
		InternalName = "/Lotus/Weapons/Ostron/Melee/ModularMelee01/Tip/TipSix",
		Introduced = "22",
		Link = "Kronsh",
		MeleeRange = 1,
		Name = "Kronsh",
		Slot = "Melee",
	},
	Mewan = {
		Attack1 = {
			AttackName = "Mewan Strike (Gilded)",
			CritChance = 0.18,
			CritMultiplier = 2,
			Damage = {
				Impact = 56,
				Puncture = 78.4,
				Slash = 89.6,
			},
			FireRate = 0.85,
			IsSilent = true,
			StatusChance = 0.18,
		},
		Class = "Zaw Sword / Polearm",
		Conclave = false,
		Disposition = 1.1,
		Image = "ZawStrikeMewan.png",
		InternalName = "/Lotus/Weapons/Ostron/Melee/ModularMelee01/Tip/TipThree",
		Introduced = "22",
		Link = "Mewan",
		MeleeRange = 1,
		Name = "Mewan",
		Slot = "Melee",
	},
	Ooltha = {
		Attack1 = {
			AttackName = "Ooltha Strike (Gilded)",
			CritChance = 0.18,
			CritMultiplier = 2,
			Damage = {
				Impact = 22.4,
				Puncture = 89.6,
				Slash = 112,
			},
			FireRate = 0.92,
			IsSilent = true,
			StatusChance = 0.18,
		},
		Class = "Zaw Sword / Staff",
		Conclave = false,
		Disposition = 1.25,
		Image = "ZawStrikeOoltha.png",
		InternalName = "/Lotus/Weapons/Ostron/Melee/ModularMelee01/Tip/TipTwo",
		Introduced = "22",
		Link = "Ooltha",
		MeleeRange = 1,
		Name = "Ooltha",
		Slot = "Melee",
	},
	Rabvee = {
		Attack1 = {
			AttackName = "Rabvee Strike (Gilded)",
			CritChance = 0.18,
			CritMultiplier = 2,
			Damage = {
				Impact = 140.4,
				Puncture = 11.7,
				Slash = 81.9,
			},
			FireRate = 0.85,
			IsSilent = true,
			StatusChance = 0.18,
		},
		Class = "Zaw Machete / Hammer",
		Conclave = false,
		Disposition = 1.3,
		Image = "ZawStrikeRabvee.png",
		InternalName = "/Lotus/Weapons/Ostron/Melee/ModularMelee02/Tip/TipTen",
		Introduced = "22.18",
		Link = "Rabvee",
		MeleeRange = 1,
		Name = "Rabvee",
		Slot = "Melee",
	},
	Sepfahn = {
		Attack1 = {
			AttackName = "Sepfahn Strike (Gilded)",
			CritChance = 0.2,
			CritMultiplier = 2,
			Damage = {
				Impact = 22.6,
				Puncture = 56.5,
				Slash = 146.9,
			},
			FireRate = 0.92,
			IsSilent = true,
			StatusChance = 0.2,
		},
		Class = "Zaw Nikana / Staff",
		Conclave = false,
		Disposition = 0.7,
		Image = "ZawStrikeSepfahn.png",
		InternalName = "/Lotus/Weapons/Ostron/Melee/ModularMelee02/Tip/TipNine",
		Introduced = "22.18",
		Link = "Sepfahn",
		MeleeRange = 1,
		Name = "Sepfahn",
		Slot = "Melee",
	},
}
