--- Reference table for Docbunto reference links.
--  List of global functions and tables available in Scribunto.
--  @file               docbunto_references

--- Reference data map for types.
--  @property           {table} docbunto_references.types

--- Reference link map for global items.
--  @property           {table} docbunto_references.items

return {
    types = {
        -- Lua types available to Scribunto.
        ["nil"]         = { link = "Lua reference manual#nil", name = "nil" },
        ["bool"]        = { link = "Lua reference manual#boolean", name = "boolean" },
        ["boolean"]     = { link = "Lua reference manual#boolean", name = "boolean" },
        ["string"]      = { link = "Lua reference manual#string", name = "string" },
        ["int"]         = { link = "Lua reference manual#number", name = "number" },
        ["number"]      = { link = "Lua reference manual#number", name = "number" },
        ["tab"]         = { link = "Lua reference manual#table", name = "table" },
        ["table"]       = { link = "Lua reference manual#table", name = "table" },
        ["sequence"]    = { link = "Lua reference manual#sequence", name = "sequence" },
        ["func"]        = { link = "Lua reference manual#function", name = "function" },
        ["function"]    = { link = "Lua reference manual#function", name = "function" },
        -- Scribunto library objects.
        ["mw.loadData"] = { link = "Lua reference manual/Scribunto libraries#mw.loadData", name = "DataWrapper" },
        ["DataWrapper"] = { link = "Lua reference manual/Scribunto libraries#mw.loadData", name = "DataWrapper" },
        ["Frame"]       = { link = "Lua reference manual/Scribunto libraries#Frame object", name = "Frame" },
        ["mw.language"] = { link = "Lua reference manual/Scribunto libraries#Language object", name = "Lang" },
        ["Lang"]        = { link = "Lua reference manual/Scribunto libraries#Language object", name = "Lang" },
        ["mw.uri"]      = { link = "Lua reference manual/Scribunto libraries#URI object", name = "Uri" },
        ["Uri"]         = { link = "Lua reference manual/Scribunto libraries#URI object", name = "Uri" },
        ["mw.html"]     = { link = "Lua reference manual/Scribunto libraries#HTML object", name = "HTMLBuilder" },
        ["HTMLBuilder"] = { link = "Lua reference manual/Scribunto libraries#HTML object", name = "HTMLBuilder" },
        ["mw.title"]    = { link = "Lua reference manual/Scribunto libraries#Title objects", name = "Title" },
        ["Title"]       = { link = "Lua reference manual/Scribunto libraries#Title objects", name = "Title" },
        ["mw.message"]  = { link = "Lua reference manual/Scribunto libraries#Message object", name = "Msg" },
        ["Msg"]         = { link = "Lua reference manual/Scribunto libraries#Message object", name = "Msg" },
    },

    items = {
        -- Types and primitives.
        ["..."] = "Lua reference manual#varargs",
        ["nil"] = "Lua reference manual#nil",
        ["boolean"] = "Lua reference manual#boolean",
        ["number"] = "Lua reference manual#number",
        ["sequence"] = "Lua reference manual#sequence",
        ["function"] = "Lua reference manual#function",
        -- Global variables and functions.
        ["_G"] = "Lua reference manual/Standard libraries#_G",
        ["_VERSION"] = "Lua reference manual/Standard libraries#_VERSION",
        ["assert"] = "Lua reference manual/Standard libraries#assert",
        ["error"] = "Lua reference manual/Standard libraries#error",
        ["getmetatable"] = "Lua reference manual/Standard libraries#getmetatable",
        ["setmetatable"] = "Lua reference manual/Standard libraries#setmetatable",
        ["ipairs"] = "Lua reference manual/Standard libraries#ipairs",
        ["next"] = "Lua reference manual/Standard libraries#next",
        ["pairs"] = "Lua reference manual/Standard libraries#pairs",
        ["pcall"] = "Lua reference manual/Standard libraries#pcall",
        ["xpcall"] = "Lua reference manual/Standard libraries#xpcall",
        ["rawequal"] = "Lua reference manual/Standard libraries#rawequal",
        ["rawget"] = "Lua reference manual/Standard libraries#rawget",
        ["rawset"] = "Lua reference manual/Standard libraries#rawset",
        ["require"] = "Lua reference manual/Standard libraries#require",
        ["select"] = "Lua reference manual/Standard libraries#select",
        ["tonumber"] = "Lua reference manual/Standard libraries#tonumber",
        ["tostring"] = "Lua reference manual/Standard libraries#tostring",
        ["type"] = "Lua reference manual/Standard libraries#type",
        ["unpack"] = "Lua reference manual/Standard libraries#unpack",
        -- Lua debug library.
        ["debug"] = "Lua reference manual/Standard libraries#Debug library",
        ["debug.traceback"] = "Lua reference manual/Standard libraries#debug.traceback",
        -- Lua math library.
        ["math"] = "Lua reference manual/Standard libraries#Math library",
        ["math.abs"] = "Lua reference manual/Standard libraries#math.abs",
        ["math.acos"] = "Lua reference manual/Standard libraries#math.acos",
        ["math.asin"] = "Lua reference manual/Standard libraries#math.asin",
        ["math.atan"] = "Lua reference manual/Standard libraries#math.atan",
        ["math.atan2"] = "Lua reference manual/Standard libraries#math.atan2",
        ["math.ceil"] = "Lua reference manual/Standard libraries#math.ceil",
        ["math.cos"] = "Lua reference manual/Standard libraries#math.cos",
        ["math.cosh"] = "Lua reference manual/Standard libraries#math.cosh",
        ["math.deg"] = "Lua reference manual/Standard libraries#math.deg",
        ["math.exp"] = "Lua reference manual/Standard libraries#math.exp",
        ["math.floor"] = "Lua reference manual/Standard libraries#math.floor",
        ["math.fmod"] = "Lua reference manual/Standard libraries#math.fmod",
        ["math.frexp"] = "Lua reference manual/Standard libraries#math.frexp",
        ["math.huge"] = "Lua reference manual/Standard libraries#math.huge",
        ["math.ldexp"] = "Lua reference manual/Standard libraries#math.ldexp",
        ["math.log"] = "Lua reference manual/Standard libraries#math.log",
        ["math.log10"] = "Lua reference manual/Standard libraries#math.log10",
        ["math.max"] = "Lua reference manual/Standard libraries#math.max",
        ["math.min"] = "Lua reference manual/Standard libraries#math.min",
        ["math.modf"] = "Lua reference manual/Standard libraries#math.modf",
        ["math.pi"] = "Lua reference manual/Standard libraries#math.pi",
        ["math.pow"] = "Lua reference manual/Standard libraries#math.pow",
        ["math.rad"] = "Lua reference manual/Standard libraries#math.rad",
        ["math.random"] = "Lua reference manual/Standard libraries#math.random",
        ["math.randomseed"] = "Lua reference manual/Standard libraries#math.randomseed",
        ["math.sin"] = "Lua reference manual/Standard libraries#math.sin",
        ["math.sinh"] = "Lua reference manual/Standard libraries#math.sinh",
        ["math.sqrt"] = "Lua reference manual/Standard libraries#math.sqrt",
        ["math.tan"] = "Lua reference manual/Standard libraries#math.tan",
        ["math.tanh"] = "Lua reference manual/Standard libraries#math.tanh",
        -- Operating system library.
        ["os"] = "Lua reference manual/Standard libraries#Operating system library",
        ["os.clock"] = "Lua reference manual/Standard libraries#os.clock",
        ["os.date"] = "Lua reference manual/Standard libraries#os.date",
        ["os.difftime"] = "Lua reference manual/Standard libraries#os.difftime",
        ["os.time"] = "Lua reference manual/Standard libraries#os.time",
        -- Package library.
        ["package"] = "Lua reference manual/Standard libraries#Package library",
        ["package.loaded"] = "Lua reference manual/Standard libraries#package.loaded",
        ["package.loaders"] = "Lua reference manual/Standard libraries#package.loaders",
        ["package.preload"] = "Lua reference manual/Standard libraries#package.preload",
        ["package.seeall"] = "Lua reference manual/Standard libraries#package.seeall",
        -- Lua string library.
        ["string"] = "Lua reference manual/Standard libraries#String library",
        ["string.byte"] = "Lua reference manual/Standard libraries#string.byte",
        ["string.char"] = "Lua reference manual/Standard libraries#string.char",
        ["string.find"] = "Lua reference manual/Standard libraries#string.find",
        ["string.format"] = "Lua reference manual/Standard libraries#string.format",
        ["string.gmatch"] = "Lua reference manual/Standard libraries#string.gmatch",
        ["string.gsub"] = "Lua reference manual/Standard libraries#string.gsub",
        ["string.len"] = "Lua reference manual/Standard libraries#string.len",
        ["string.lower"] = "Lua reference manual/Standard libraries#string.lower",
        ["string.match"] = "Lua reference manual/Standard libraries#string.match",
        ["string.rep"] = "Lua reference manual/Standard libraries#string.rep",
        ["string.reverse"] = "Lua reference manual/Standard libraries#string.reverse",
        ["string.sub"] = "Lua reference manual/Standard libraries#string.sub",
        ["string.upper"] = "Lua reference manual/Standard libraries#string.upper",
        -- Lua table library.
        ["table"] = "Lua reference manual/Standard libraries#Table library",
        ["table.concat"] = "Lua reference manual/Standard libraries#table.concat",
        ["table.insert"] = "Lua reference manual/Standard libraries#table.insert",
        ["table.maxn"] = "Lua reference manual/Standard libraries#table.maxn",
        ["table.remove"] = "Lua reference manual/Standard libraries#table.remove",
        ["table.sort"] = "Lua reference manual/Standard libraries#table.sort",
        -- MediaWiki Scribunto library.
        ["mw"] = "Lua reference manual/Scribunto libraries",
        ["mw.allToString"] = "Lua reference manual/Scribunto libraries#mw.allToString",
        ["mw.clearLogBuffer"] = "Lua reference manual/Scribunto libraries#mw.clearLogBuffer",
        ["mw.clone"] = "Lua reference manual/Scribunto libraries#mw.clone",
        ["mw.executeFunction"] = "Lua reference manual/Scribunto libraries#mw.executeFunction",
        ["mw.executeModule"] = "Lua reference manual/Scribunto libraries#mw.executeModule",
        ["mw.getCurrentFrame"] = "Lua reference manual/Scribunto libraries#mw.getCurrentFrame",
        ["mw.getLogBuffer"] = "Lua reference manual/Scribunto libraries#mw.getLogBuffer",
        ["mw.incrementExpensiveFunctionCount"] = "Lua reference manual/Scribunto libraries#mw.incrementExpensiveFunctionCount",
        ["mw.loadData"] = "Lua reference manual/Scribunto libraries#mw.loadData",
        ["DataWrapper"] = "Lua reference manual/Scribunto libraries#mw.loadData",
        ["mw.log"] = "Lua reference manual/Scribunto libraries#mw.log",
        ["print"] = "Lua reference manual/Scribunto libraries#mw.log",
        -- Scribunto frame object.
        ["frame"] = "Lua reference manual/Scribunto libraries#Frame object",
        ["frame.args"] = "Lua reference manual/Scribunto libraries#frame.args",
        ["frame:getParent"] = "Lua reference manual/Scribunto libraries#frame:getParent",
        ["frame:expandTemplate"] = "Lua reference manual/Scribunto libraries#frame:expandTemplate",
        ["frame:preprocess"] = "Lua reference manual/Scribunto libraries#frame:preprocess",
        ["frame:getArgument"] = "Lua reference manual/Scribunto libraries#frame:getArgument",
        ["frame:newParserValue"] = "Lua reference manual/Scribunto libraries#frame:newParserValue",
        ["frame:newTemplateParserValue"] = "Lua reference manual/Scribunto libraries#frame:newTemplateParserValue",
        ["frame:argumentPairs"] = "Lua reference manual/Scribunto libraries#frame:argumentPairs",
        ["frame:getTitle"] = "Lua reference manual/Scribunto libraries#frame:getTitle",
        -- Scribunto frame object as `Frame` class.
        ["Frame"] = "Lua reference manual/Scribunto libraries#Frame object",
        ["Frame.args"] = "Lua reference manual/Scribunto libraries#frame.args",
        ["Frame:getParent"] = "Lua reference manual/Scribunto libraries#frame:getParent",
        ["Frame:expandTemplate"] = "Lua reference manual/Scribunto libraries#frame:expandTemplate",
        ["Frame:preprocess"] = "Lua reference manual/Scribunto libraries#frame:preprocess",
        ["Frame:getArgument"] = "Lua reference manual/Scribunto libraries#frame:getArgument",
        ["Frame:newParserValue"] = "Lua reference manual/Scribunto libraries#frame:newParserValue",
        ["Frame:newTemplateParserValue"] = "Lua reference manual/Scribunto libraries#frame:newTemplateParserValue",
        ["Frame:argumentPairs"] = "Lua reference manual/Scribunto libraries#frame:argumentPairs",
        ["Frame:getTitle"] = "Lua reference manual/Scribunto libraries#frame:getTitle",
        -- Scribunto language library.
        ["mw.language"] = "Lua reference manual/Scribunto libraries#Language library",
        ["mw.language.fetchLanguageName"] = "Lua reference manual/Scribunto libraries#mw.language.fetchLanguageName",
        ["mw.language.getContentLanguage"] = "Lua reference manual/Scribunto libraries#mw.language.getContentLanguage",
        ["mw.language.isValidBuiltInCode"] = "Lua reference manual/Scribunto libraries#mw.language.isValidBuiltInCode",
        ["mw.language.isValidCode"] = "Lua reference manual/Scribunto libraries#mw.language.isValidCode",
        ["mw.language.new"] = "Lua reference manual/Scribunto libraries#mw.language.new",
        -- Scribunto language object.
        ["lang"] = "Lua reference manual/Scribunto libraries#Language object",
        ["mw.language:getCode"] = "Lua reference manual/Scribunto libraries#mw.language:getCode",
        ["mw.language:isRTL"] = "Lua reference manual/Scribunto libraries#mw.language:isRTL",
        ["mw.language:lc"] = "Lua reference manual/Scribunto libraries#mw.language:lc",
        ["mw.language:lcfirst"] = "Lua reference manual/Scribunto libraries#mw.language:lcfirst",
        ["mw.language:uc"] = "Lua reference manual/Scribunto libraries#mw.language:uc",
        ["mw.language:ucfirst"] = "Lua reference manual/Scribunto libraries#mw.language:ucfirst",
        ["mw.language:caseFold"] = "Lua reference manual/Scribunto libraries#mw.language:caseFold",
        ["mw.language:formatNum"] = "Lua reference manual/Scribunto libraries#mw.language:formatNum",
        ["mw.language:formatDate"] = "Lua reference manual/Scribunto libraries#mw.language:formatDate",
        ["mw.language:parseFormattedNumber"] = "Lua reference manual/Scribunto libraries#mw.language:parseFormattedNumber",
        ["mw.language:convertPlural"] = "Lua reference manual/Scribunto libraries#mw.language:convertPlural",
        ["mw.language:convertGrammar"] = "Lua reference manual/Scribunto libraries#mw.language:convertGrammar",
        ["mw.language:gender"] = "Lua reference manual/Scribunto libraries#mw.language:gender",
        -- Scribunto language object as `Lang` class.
        ["Lang"] = "Lua reference manual/Scribunto libraries#Language object",
        ["Lang:getCode"] = "Lua reference manual/Scribunto libraries#mw.language:getCode",
        ["Lang:isRTL"] = "Lua reference manual/Scribunto libraries#mw.language:isRTL",
        ["Lang:lc"] = "Lua reference manual/Scribunto libraries#mw.language:lc",
        ["Lang:lcfirst"] = "Lua reference manual/Scribunto libraries#mw.language:lcfirst",
        ["Lang:uc"] = "Lua reference manual/Scribunto libraries#mw.language:uc",
        ["Lang:ucfirst"] = "Lua reference manual/Scribunto libraries#mw.language:ucfirst",
        ["Lang:caseFold"] = "Lua reference manual/Scribunto libraries#mw.language:caseFold",
        ["Lang:formatNum"] = "Lua reference manual/Scribunto libraries#mw.language:formatNum",
        ["Lang:formatDate"] = "Lua reference manual/Scribunto libraries#mw.language:formatDate",
        ["Lang:parseFormattedNumber"] = "Lua reference manual/Scribunto libraries#mw.language:parseFormattedNumber",
        ["Lang:convertPlural"] = "Lua reference manual/Scribunto libraries#mw.language:convertPlural",
        ["Lang:convertGrammar"] = "Lua reference manual/Scribunto libraries#mw.language:convertGrammar",
        ["Lang:gender"] = "Lua reference manual/Scribunto libraries#mw.language:gender",
        -- Scribunto site library.
        ["mw.site"] = "Lua reference manual/Scribunto libraries#Site library",
        ["mw.site.currentVersion"] = "Lua reference manual/Scribunto libraries#mw.site.currentVersion",
        ["mw.site.scriptPath"] = "Lua reference manual/Scribunto libraries#mw.site.scriptPath",
        ["mw.site.server"] = "Lua reference manual/Scribunto libraries#mw.site.server",
        ["mw.site.siteName"] = "Lua reference manual/Scribunto libraries#mw.site.siteName",
        ["mw.site.stylePath"] = "Lua reference manual/Scribunto libraries#mw.site.stylePath",
        ["mw.site.namespaces"] = "Lua reference manual/Scribunto libraries#mw.site.namespaces",
        ["mw.site.contentNamespaces"] = "Lua reference manual/Scribunto libraries#mw.site.contentNamespaces",
        ["mw.site.subjectNamespaces"] = "Lua reference manual/Scribunto libraries#mw.site.subjectNamespaces",
        ["mw.site.talkNamespaces"] = "Lua reference manual/Scribunto libraries#mw.site.talkNamespaces",
        ["mw.site.sassParams"] = "Lua reference manual/Scribunto libraries#mw.site.sassParams",
        ["mw.site.stats"] = "Lua reference manual/Scribunto libraries#mw.site.stats",
        ["mw.site.stats.pagesInCategory"] = "Lua reference manual/Scribunto libraries#mw.site.stats.pagesInCategory",
        ["mw.site.stats.pagesInNamespace"] = "Lua reference manual/Scribunto libraries#mw.site.stats.pagesInNamespace",
        ["mw.site.stats.usersInGroup"] = "Lua reference manual/Scribunto libraries#mw.site.stats.usersInGroup",
        -- Scribunto URI library.
        ["mw.uri"] = "Lua reference manual/Scribunto libraries#Uri library",
        ["mw.uri.encode"] = "Lua reference manual/Scribunto libraries#mw.uri.encode",
        ["mw.uri.decode"] = "Lua reference manual/Scribunto libraries#mw.uri.decode",
        ["mw.uri.anchorEncode"] = "Lua reference manual/Scribunto libraries#mw.uri.anchorEncode",
        ["mw.uri.buildQueryString"] = "Lua reference manual/Scribunto libraries#mw.uri.buildQueryString",
        ["mw.uri.parseQueryString"] = "Lua reference manual/Scribunto libraries#mw.uri.parseQueryString",
        ["mw.uri.canonicalUrl"] = "Lua reference manual/Scribunto libraries#mw.uri.canonicalUrl",
        ["mw.uri.fullUrl"] = "Lua reference manual/Scribunto libraries#mw.uri.fullUrl",
        ["mw.uri.localUrl"] = "Lua reference manual/Scribunto libraries#mw.uri.localUrl",
        ["mw.uri.new"] = "Lua reference manual/Scribunto libraries#mw.uri.new",
        ["mw.uri.validate"] = "Lua reference manual/Scribunto libraries#mw.uri.validate",
        -- Scribunto URI object.
        ["uri"] = "Lua reference manual/Scribunto libraries#URI object",
        ["mw.uri:parse"] = "Lua reference manual/Scribunto libraries#mw.uri:parse",
        ["mw.uri:clone"] = "Lua reference manual/Scribunto libraries#mw.uri:clone",
        ["mw.uri:extend"] = "Lua reference manual/Scribunto libraries#mw.uri:extend",
        -- Scribunto URI object as `Uri` class.
        ["Uri"] = "Lua reference manual/Scribunto libraries#URI object",
        ["Uri:parse"] = "Lua reference manual/Scribunto libraries#mw.uri:parse",
        ["Uri:parse"] = "Lua reference manual/Scribunto libraries#mw.uri:parse",
        ["Uri:clone"] = "Lua reference manual/Scribunto libraries#mw.uri:clone",
        ["Uri:extend"] = "Lua reference manual/Scribunto libraries#mw.uri:extend",
        -- Scribunto UTF8-safe string library.
        ["mw.ustring"] = "Lua reference manual/Scribunto libraries#Ustring library",
        ["mw.ustring.maxPatternLength"] = "Lua reference manual/Scribunto libraries#mw.ustring.maxPatternLength",
        ["mw.ustring.maxStringLength"] = "Lua reference manual/Scribunto libraries#mw.ustring.maxStringLength",
        ["mw.ustring.byte"] = "Lua reference manual/Scribunto libraries#mw.ustring.byte",
        ["mw.ustring.byteoffset"] = "Lua reference manual/Scribunto libraries#mw.ustring.byteoffset",
        ["mw.ustring.char"] = "Lua reference manual/Scribunto libraries#mw.ustring.char",
        ["mw.ustring.codepoint"] = "Lua reference manual/Scribunto libraries#mw.ustring.codepoint",
        ["mw.ustring.find"] = "Lua reference manual/Scribunto libraries#mw.ustring.find",
        ["mw.ustring.format"] = "Lua reference manual/Scribunto libraries#mw.ustring.format",
        ["mw.ustring.gcodepoint"] = "Lua reference manual/Scribunto libraries#mw.ustring.gcodepoint",
        ["mw.ustring.gmatch"] = "Lua reference manual/Scribunto libraries#mw.ustring.gmatch",
        ["mw.ustring.gsub"] = "Lua reference manual/Scribunto libraries#mw.ustring.gsub",
        ["mw.ustring.isutf8"] = "Lua reference manual/Scribunto libraries#mw.ustring.isutf8",
        ["mw.ustring.len"] = "Lua reference manual/Scribunto libraries#mw.ustring.len",
        ["mw.ustring.lower"] = "Lua reference manual/Scribunto libraries#mw.ustring.lower",
        ["mw.ustring.match"] = "Lua reference manual/Scribunto libraries#mw.ustring.match",
        ["mw.ustring.rep"] = "Lua reference manual/Scribunto libraries#mw.ustring.rep",
        ["mw.ustring.sub"] = "Lua reference manual/Scribunto libraries#mw.ustring.sub",
        ["mw.ustring.toNFC"] = "Lua reference manual/Scribunto libraries#mw.ustring.toNFC",
        ["mw.ustring.toNFD"] = "Lua reference manual/Scribunto libraries#mw.ustring.toNFD",
        ["mw.ustring.upper"] = "Lua reference manual/Scribunto libraries#mw.ustring.upper",
        -- Scribunto HTML library.
        ["mw.html"] = "Lua reference manual/Scribunto libraries#HTML library",
        ["mw.html.create"] = "Lua reference manual/Scribunto libraries#mw.html.create",
        -- Scribunto HTML object.
        ["html"] = "Lua reference manual/Scribunto libraries#HTML object",
        ["mw.html:node"] = "Lua reference manual/Scribunto libraries#mw.html:node",
        ["mw.html:wikitext"] = "Lua reference manual/Scribunto libraries#mw.html:wikitext",
        ["mw.html:newline"] = "Lua reference manual/Scribunto libraries#mw.html:newline",
        ["mw.html:tag"] = "Lua reference manual/Scribunto libraries#mw.html:tag",
        ["mw.html:attr"] = "Lua reference manual/Scribunto libraries#mw.html:attr",
        ["mw.html:getAttr"] = "Lua reference manual/Scribunto libraries#mw.html:getAttr",
        ["mw.html:addClass"] = "Lua reference manual/Scribunto libraries#mw.html:addClass",
        ["mw.html:css"] = "Lua reference manual/Scribunto libraries#mw.html:css",
        ["mw.html:cssText"] = "Lua reference manual/Scribunto libraries#mw.html:cssText",
        ["mw.html:done"] = "Lua reference manual/Scribunto libraries#mw.html:done",
        ["mw.html:allDone"] = "Lua reference manual/Scribunto libraries#mw.html:allDone",
        -- Scribunto HTML object as `HTMLBuilder` class.
        ["HTMLBuilder"] = "Lua reference manual/Scribunto libraries#HTML object",
        ["HTMLBuilder:node"] = "Lua reference manual/Scribunto libraries#mw.html:node",
        ["HTMLBuilder:wikitext"] = "Lua reference manual/Scribunto libraries#mw.html:wikitext",
        ["HTMLBuilder:newline"] = "Lua reference manual/Scribunto libraries#mw.html:newline",
        ["HTMLBuilder:tag"] = "Lua reference manual/Scribunto libraries#mw.html:tag",
        ["HTMLBuilder:attr"] = "Lua reference manual/Scribunto libraries#mw.html:attr",
        ["HTMLBuilder:getAttr"] = "Lua reference manual/Scribunto libraries#mw.html:getAttr",
        ["HTMLBuilder:addClass"] = "Lua reference manual/Scribunto libraries#mw.html:addClass",
        ["HTMLBuilder:css"] = "Lua reference manual/Scribunto libraries#mw.html:css",
        ["HTMLBuilder:cssText"] = "Lua reference manual/Scribunto libraries#mw.html:cssText",
        ["HTMLBuilder:done"] = "Lua reference manual/Scribunto libraries#mw.html:done",
        ["HTMLBuilder:allDone"] = "Lua reference manual/Scribunto libraries#mw.html:allDone",
        -- Scribunto text library.
        ["mw.text"] = "Lua reference manual/Scribunto libraries#Text library",
        ["mw.text.decode"] = "Lua reference manual/Scribunto libraries#mw.text.decode",
        ["mw.text.encode"] = "Lua reference manual/Scribunto libraries#mw.text.encode",
        ["mw.text.listToText"] = "Lua reference manual/Scribunto libraries#mw.text.listToText",
        ["mw.text.nowiki"] = "Lua reference manual/Scribunto libraries#mw.text.nowiki",
        ["mw.text.split"] = "Lua reference manual/Scribunto libraries#mw.text.split",
        ["mw.text.gsplit"] = "Lua reference manual/Scribunto libraries#mw.text.gsplit",
        ["mw.text.tag"] = "Lua reference manual/Scribunto libraries#mw.text.tag",
        ["mw.text.trim"] = "Lua reference manual/Scribunto libraries#mw.text.trim",
        ["mw.text.truncate"] = "Lua reference manual/Scribunto libraries#mw.text.truncate",
        ["mw.text.unstrip"] = "Lua reference manual/Scribunto libraries#mw.text.unstrip",
        -- Scribunto title library.
        ["mw.title"] = "Lua reference manual/Scribunto libraries#Title library",
        ["mw.title.equals"] = "Lua reference manual/Scribunto libraries#mw.title.equals",
        ["mw.title.compare"] = "Lua reference manual/Scribunto libraries#mw.title.compare",
        ["mw.title.getCurrentTitle"] = "Lua reference manual/Scribunto libraries#mw.title.getCurrentTile",
        ["mw.title.new"] = "Lua reference manual/Scribunto libraries#mw.title.new",
        ["mw.title.makeTitle"] = "Lua reference manual/Scribunto libraries#mw.title.makeTitle",
        -- Scribunto title object.
        ["mw.title.id"] = "Lua reference manual/Scribunto libraries#Title objects",
        ["mw.title.interwiki"] = "Lua reference manual/Scribunto libraries#Title objects",
        ["mw.title.namespace"] = "Lua reference manual/Scribunto libraries#Title objects",
        ["mw.title.fragment"] = "Lua reference manual/Scribunto libraries#Title objects",
        ["mw.title.nsText"] = "Lua reference manual/Scribunto libraries#Title objects",
        ["mw.title.subjectNsText"] = "Lua reference manual/Scribunto libraries#Title objects",
        ["mw.title.text"] = "Lua reference manual/Scribunto libraries#Title objects",
        ["mw.title.prefixedText"] = "Lua reference manual/Scribunto libraries#Title objects",
        ["mw.title.fullText"] = "Lua reference manual/Scribunto libraries#Title objects",
        ["mw.title.rootText"] = "Lua reference manual/Scribunto libraries#Title objects",
        ["mw.title.baseText"] = "Lua reference manual/Scribunto libraries#Title objects",
        ["mw.title.subpageText"] = "Lua reference manual/Scribunto libraries#Title objects",
        ["mw.title.canTalk"] = "Lua reference manual/Scribunto libraries#Title objects",
        ["mw.title.exists"] = "Lua reference manual/Scribunto libraries#Title objects",
        ["mw.title.fileExists"] = "Lua reference manual/Scribunto libraries#Title objects",
        ["mw.title.isContentPage"] = "Lua reference manual/Scribunto libraries#Title objects",
        ["mw.title.isExternal"] = "Lua reference manual/Scribunto libraries#Title objects",
        ["mw.title.isLocal"] = "Lua reference manual/Scribunto libraries#Title objects",
        ["mw.title.isRedirect"] = "Lua reference manual/Scribunto libraries#Title objects",
        ["mw.title.isSpecialPage"] = "Lua reference manual/Scribunto libraries#Title objects",
        ["mw.title.isSubpage"] = "Lua reference manual/Scribunto libraries#Title objects",
        ["mw.title.isTalkPage"] = "Lua reference manual/Scribunto libraries#Title objects",
        ["mw.title:isSubpageOf"] = "Lua reference manual/Scribunto libraries#Title objects",
        ["mw.title:inNamespace"] = "Lua reference manual/Scribunto libraries#Title objects",
        ["mw.title:inNamespaces"] = "Lua reference manual/Scribunto libraries#Title objects",
        ["mw.title:hasSubjectNamespace"] = "Lua reference manual/Scribunto libraries#Title objects",
        ["mw.title.basePageTitle"] = "Lua reference manual/Scribunto libraries#Title objects",
        ["mw.title.rootPageTitle"] = "Lua reference manual/Scribunto libraries#Title objects",
        ["mw.title.talkPageTitle"] = "Lua reference manual/Scribunto libraries#Title objects",
        ["mw.title.subjectPageTitle"] = "Lua reference manual/Scribunto libraries#Title objects",
        ["mw.title.protectionLevels"] = "Lua reference manual/Scribunto libraries#Title objects",
        ["mw.title:subPageTitle"] = "Lua reference manual/Scribunto libraries#Title objects",
        ["mw.title:partialUrl"] = "Lua reference manual/Scribunto libraries#Title objects",
        ["mw.title:fullUrl"] = "Lua reference manual/Scribunto libraries#Title objects",
        ["mw.title:localUrl"] = "Lua reference manual/Scribunto libraries#Title objects",
        ["mw.title:canonicalUrl"] = "Lua reference manual/Scribunto libraries#Title objects",
        ["mw.title:getContent"] = "Lua reference manual/Scribunto libraries#Title objects",
        -- Scribunto title object as `Title` class.
        ["Title"] = "Lua reference manual/Scribunto libraries#Title objects",
        ["Title.id"] = "Lua reference manual/Scribunto libraries#Title objects",
        ["Title.interwiki"] = "Lua reference manual/Scribunto libraries#Title objects",
        ["Title.namespace"] = "Lua reference manual/Scribunto libraries#Title objects",
        ["Title.fragment"] = "Lua reference manual/Scribunto libraries#Title objects",
        ["Title.nsText"] = "Lua reference manual/Scribunto libraries#Title objects",
        ["Title.subjectNsText"] = "Lua reference manual/Scribunto libraries#Title objects",
        ["Title.text"] = "Lua reference manual/Scribunto libraries#Title objects",
        ["Title.prefixedText"] = "Lua reference manual/Scribunto libraries#Title objects",
        ["Title.fullText"] = "Lua reference manual/Scribunto libraries#Title objects",
        ["Title.rootText"] = "Lua reference manual/Scribunto libraries#Title objects",
        ["Title.baseText"] = "Lua reference manual/Scribunto libraries#Title objects",
        ["Title.subpageText"] = "Lua reference manual/Scribunto libraries#Title objects",
        ["Title.canTalk"] = "Lua reference manual/Scribunto libraries#Title objects",
        ["Title.exists"] = "Lua reference manual/Scribunto libraries#Title objects",
        ["Title.fileExists"] = "Lua reference manual/Scribunto libraries#Title objects",
        ["Title.isContentPage"] = "Lua reference manual/Scribunto libraries#Title objects",
        ["Title.isExternal"] = "Lua reference manual/Scribunto libraries#Title objects",
        ["Title.isLocal"] = "Lua reference manual/Scribunto libraries#Title objects",
        ["Title.isRedirect"] = "Lua reference manual/Scribunto libraries#Title objects",
        ["Title.isSpecialPage"] = "Lua reference manual/Scribunto libraries#Title objects",
        ["Title.isSubpage"] = "Lua reference manual/Scribunto libraries#Title objects",
        ["Title.isTalkPage"] = "Lua reference manual/Scribunto libraries#Title objects",
        ["Title:isSubpageOf"] = "Lua reference manual/Scribunto libraries#Title objects",
        ["Title:inNamespace"] = "Lua reference manual/Scribunto libraries#Title objects",
        ["Title:inNamespaces"] = "Lua reference manual/Scribunto libraries#Title objects",
        ["Title:hasSubjectNamespace"] = "Lua reference manual/Scribunto libraries#Title objects",
        ["Title.basePageTitle"] = "Lua reference manual/Scribunto libraries#Title objects",
        ["Title.rootPageTitle"] = "Lua reference manual/Scribunto libraries#Title objects",
        ["Title.talkPageTitle"] = "Lua reference manual/Scribunto libraries#Title objects",
        ["Title.subjectPageTitle"] = "Lua reference manual/Scribunto libraries#Title objects",
        ["Title.protectionLevels"] = "Lua reference manual/Scribunto libraries#Title objects",
        ["Title:subPageTitle"] = "Lua reference manual/Scribunto libraries#Title objects",
        ["Title:partialUrl"] = "Lua reference manual/Scribunto libraries#Title objects",
        ["Title:fullUrl"] = "Lua reference manual/Scribunto libraries#Title objects",
        ["Title:localUrl"] = "Lua reference manual/Scribunto libraries#Title objects",
        ["Title:canonicalUrl"] = "Lua reference manual/Scribunto libraries#Title objects",
        ["Title:getContent"] = "Lua reference manual/Scribunto libraries#Title objects",
        -- Scribunto message library.
        ["mw.message"] = "Lua reference manual/Scribunto libraries#Message library",
        ["mw.message.new"] = "Lua reference manual/Scribunto libraries#mw.message.new",
        ["mw.message.newFallbackSequence"] = "Lua reference manual/Scribunto libraries#mw.message.newFallbackSequence",
        ["mw.message.rawParam"] = "Lua reference manual/Scribunto libraries#mw.message.rawParam",
        ["mw.message.numParam"] = "Lua reference manual/Scribunto libraries#mw.message.numParam",
        ["mw.message.getDefaultLanguage"] = "Lua reference manual/Scribunto libraries#mw.message.getDefaultLanguage",
        -- Scribunto message object.
        ["msg"] = "Lua reference manual/Scribunto libraries#Message object",
        ["mw.message:params"] = "Lua reference manual/Scribunto libraries#mw.message:params",
        ["mw.message:rawParams"] = "Lua reference manual/Scribunto libraries#mw.message:rawParams",
        ["mw.message:numParams"] = "Lua reference manual/Scribunto libraries#mw.message:numParams",
        ["mw.message:inLanguage"] = "Lua reference manual/Scribunto libraries#mw.message:inLanguage",
        ["mw.message:useDatabase"] = "Lua reference manual/Scribunto libraries#mw.message:useDatabase",
        ["mw.message:plain"] = "Lua reference manual/Scribunto libraries#mw.message:plain",
        ["mw.message:exists"] = "Lua reference manual/Scribunto libraries#mw.message:exists",
        ["mw.message:isBlank"] = "Lua reference manual/Scribunto libraries#mw.message:isBlank",
        ["mw.message:isDisabled"] = "Lua reference manual/Scribunto libraries#mw.message:isDisabled",
        -- Scribunto message object as `Msg` class.
        ["Msg"] = "Lua reference manual/Scribunto libraries#Message object",
        ["Msg:params"] = "Lua reference manual/Scribunto libraries#mw.message:params",
        ["Msg:rawParams"] = "Lua reference manual/Scribunto libraries#mw.message:rawParams",
        ["Msg:numParams"] = "Lua reference manual/Scribunto libraries#mw.message:numParams",
        ["Msg:inLanguage"] = "Lua reference manual/Scribunto libraries#mw.message:inLanguage",
        ["Msg:useDatabase"] = "Lua reference manual/Scribunto libraries#mw.message:useDatabase",
        ["Msg:plain"] = "Lua reference manual/Scribunto libraries#mw.message:plain",
        ["Msg:exists"] = "Lua reference manual/Scribunto libraries#mw.message:exists",
        ["Msg:isBlank"] = "Lua reference manual/Scribunto libraries#mw.message:isBlank",
        ["Msg:isDisabled"] = "Lua reference manual/Scribunto libraries#mw.message:isDisabled",
        -- Fandom wikitext library
        ["mw.InfoboxBuilderHF"] = "Lua reference manual/Fandom libraries#Wikitext library",
        ["mw.InfoboxBuilderHF.explode"] = "Lua reference manual/Fandom libraries#mw.InfoboxBuilderHF.explode",
        ["mw.InfoboxBuilderHF.isempty"] = "Lua reference manual/Fandom libraries#mw.InfoboxBuilderHF.isempty",
        ["mw.InfoboxBuilderHF.firstToUpper"] = "Lua reference manual/Fandom libraries#mw.InfoboxBuilderHF.firstToUpper",
        ["mw.InfoboxBuilderHF.round"] = "Lua reference manual/Fandom libraries#mw.InfoboxBuilderHF.round",
        ["mw.InfoboxBuilderHF.trim"] = "Lua reference manual/Fandom libraries#mw.InfoboxBuilderHF.trim",
        ["mw.InfoboxBuilderHF.unique"] = "Lua reference manual/Fandom libraries#mw.InfoboxBuilderHF.unique",
        ["mw.InfoboxBuilderHF.Link"] = "Lua reference manual/Fandom libraries#mw.InfoboxBuilderHF.Link",
        ["mw.InfoboxBuilderHF.Link_safe"] = "Lua reference manual/Fandom libraries#mw.InfoboxBuilderHF.Link_safe",
        ["mw.InfoboxBuilderHF.ExternalLink"] = "Lua reference manual/Fandom libraries#mw.InfoboxBuilderHF.ExternalLink",
        ["mw.InfoboxBuilderHF.Category"] = "Lua reference manual/Fandom libraries#mw.InfoboxBuilderHF.Category",
        ["mw.InfoboxBuilderHF.LinkToCategory"] = "Lua reference manual/Fandom libraries#mw.InfoboxBuilderHF.LinkToCategory",
        ["mw.InfoboxBuilderHF.CategoryLink"] = "Lua reference manual/Fandom libraries#mw.InfoboxBuilderHF.CategoryLink",
        ["mw.InfoboxBuilderHF.LinkToCategory_safe"] = "Lua reference manual/Fandom libraries#mw.InfoboxBuilderHF.LinkToCategory_safe",
        ["mw.InfoboxBuilderHF.KillNewCategories"] = "Lua reference manual/Fandom libraries#mw.InfoboxBuilderHF.KillNewCategories",
    }
}
