--- Honorias data table for [[WARFRAME]] titles.
-- @module Honorias/data
-- 

local honoriaData = {
	["Disciple Founder"] = {
			Name = "Disciple Founder",
			Link = "Disciple Founder",
			Description = "",
			Position = "Prefix",
			Introduced = "",
			InternalName = "/Lotus/Types/Items/Titles/FounderLvl1Title",
			CodexSecret = true,
			ExcludeFromCodex = true,
	},
	["Hunter Founder"] = {
			Name = "Hunter Founder",
			Link = "Hunter Founder",
			Description = "",
			Position = "Prefix",
			Introduced = "",
			InternalName = "/Lotus/Types/Items/Titles/FounderLvl2Title",
			CodexSecret = true,
			ExcludeFromCodex = true,
	},
	["Master Founder"] = {
			Name = "Master Founder",
			Link = "Master Founder",
			Description = "",
			Position = "Prefix",
			Introduced = "",
			InternalName = "/Lotus/Types/Items/Titles/FounderLvl3Title",
			CodexSecret = true,
			ExcludeFromCodex = true,
	},
	["Grand Master Founder"] = {
			Name = "Grand Master Founder",
			Link = "Grand Master Founder",
			Description = "",
			Position = "Prefix",
			Introduced = "",
			InternalName = "/Lotus/Types/Items/Titles/FounderLvl4Title",
			CodexSecret = true,
			ExcludeFromCodex = true,
	},
	["90's Kid"] = {
			Name = "90's Kid",
			Link = "90's Kid",
			Description = "",
			Position = "Suffix",
			Introduced = "43.5",
			InternalName = "/Lotus/Types/Items/Titles/ShockwaveTitle",
			CodexSecret = true,
			ExcludeFromCodex = true,
			Tags = {"Amir", "Fables & Frontiers"},
	},
	["Abyssal Thorn"] = {
			Name = "Abyssal Thorn",
			Link = "Abyssal Thorn",
			Description = "",
			Position = "Suffix",
			Introduced = "41",
			InternalName = "/Lotus/Types/Items/Titles/RoatheTitles/TitleDagath",
			CodexSecret = true,
			ExcludeFromCodex = true,
			Tags = { "Roathe" },
	},
	["Ack-Ack"] = {
			Name = "Ack-Ack",
			Link = "Ack-Ack",
			Description = "",
			Position = "Prefix",
			Introduced = "",
			InternalName = "/Lotus/Types/Items/Titles/AirHunterTitle",
			CodexSecret = true,
			ExcludeFromCodex = true,
	},
	["Along Came"] = {
			Name = "Along Came",
			Link = "Along Came",
			Description = "",
			Position = "Prefix",
			Introduced = "41",
			InternalName = "/Lotus/Types/Items/Titles/RoatheTitles/TitleOraxia",
			CodexSecret = true,
			ExcludeFromCodex = true,
	},
	["Angel of Death"] = {
			Name = "Angel of Death",
			Link = "Angel of Death",
			Description = "",
			Position = "Suffix",
			Introduced = "43.5",
			InternalName = "/Lotus/Types/Items/Titles/Kills100Title",
			CodexSecret = true,
			ExcludeFromCodex = true,
	},
	["Arbiter of Ink"] = {
			Name = "Arbiter of Ink",
			Link = "Arbiter of Ink",
			Description = "",
			Position = "Prefix",
			Introduced = "",
			InternalName = "/Lotus/Types/Items/Titles/FollieHuntCompleteTitle",
			CodexSecret = true,
			ExcludeFromCodex = true,
	},
	["Arcane Researcher"] = {
			Name = "Arcane Researcher",
			Link = "Arcane Researcher",
			Description = "",
			Position = "Suffix",
			Introduced = "43",
			InternalName = "/Lotus/Types/Items/Titles/CompleteEDAMaxTitle",
			CodexSecret = true,
			ExcludeFromCodex = true,
	},
	["As One"] = {
			Name = "As One",
			Link = "As One",
			Description = "",
			Position = "Suffix",
			Introduced = "43",
			InternalName = "/Lotus/Types/Items/Titles/HunhowHonoria/TitleSiriusOrion",
			CodexSecret = true,
			ExcludeFromCodex = true,
	},
	["Awoken Tenno"] = {
			Name = "Awoken Tenno",
			Link = "Awoken Tenno",
			Description = "",
			Position = "Suffix",
			Introduced = "",
			InternalName = "/Lotus/Types/Items/Titles/SecondDreamTitle",
			CodexSecret = true,
			ExcludeFromCodex = true,
	},
	["Big Spender"] = {
			Name = "Big Spender",
			Link = "Big Spender",
			Description = "{{cc|100,000}}",
			Position = "Suffix",
			Introduced = "41",
			InternalName = "/Lotus/Types/Items/Titles/RoatheTitles/TitleCreditsBig",
			CodexSecret = true,
			ExcludeFromCodex = true,
	},
	["Bigger Spender"] = {
			Name = "Bigger Spender",
			Link = "Bigger Spender",
			Description = "{{cc|1,000,000}}",
			Position = "Suffix",
			Introduced = "41",
			InternalName = "/Lotus/Types/Items/Titles/RoatheTitles/TitleCreditsBigger",
			CodexSecret = true,
			ExcludeFromCodex = true,
	},
	["Biggest Spender"] = {
			Name = "Biggest Spender",
			Link = "Biggest Spender",
			Description = "{{cc|2,500,000}}",
			Position = "Suffix",
			Introduced = "",
			InternalName = "/Lotus/Types/Items/Titles/RoatheTitles/TitleCreditsBiggest",
			CodexSecret = true,
			ExcludeFromCodex = true,
	},
	["Blazing Revolutionary"] = {
			Name = "Blazing Revolutionary",
			Link = "Blazing Revolutionary",
			Description = "",
			Position = "Suffix",
			Introduced = "41",
			InternalName = "/Lotus/Types/Items/Titles/RoatheTitles/TitleTemple",
			CodexSecret = true,
			ExcludeFromCodex = true,
	},
	["Capit"] = {
			Name = "Capit",
			Link = "Capit",
			Description = "",
			Position = "Prefix",
			Introduced = "41.0.5",
			InternalName = "/Lotus/Types/Items/Titles/MedalRank13Title",
			CodexSecret = true,
			ExcludeFromCodex = true,
	},
	["Champion of the Lotus"] = {
			Name = "Champion of the Lotus",
			Link = "Champion of the Lotus",
			Description = "",
			Position = "Suffix",
			Introduced = "",
			InternalName = "/Lotus/Types/Items/Titles/LotusEatersTitle",
			CodexSecret = true,
			ExcludeFromCodex = true,
	},
	["Historian of Tau"] = {
			Name = "Historian of Tau",
			Link = "Historian of Tau",
			Description = "",
			Position = "Suffix",
			Introduced = "",
			InternalName = "/Lotus/Types/Items/Titles/OldPeaceTitle",
			CodexSecret = true,
			ExcludeFromCodex = true,
	},
	["Chosen of Margulis"] = {
			Name = "Chosen of Margulis",
			Link = "Chosen of Margulis",
			Description = "",
			Position = "Suffix",
			Introduced = "",
			InternalName = "/Lotus/Types/Items/Titles/OldPeaceTeaserTitle",
			CodexSecret = true,
			ExcludeFromCodex = true,
	},
	["Clem"] = {
			Name = "Clem",
			Link = "Clem",
			Description = "",
			Position = "Suffix",
			Introduced = "",
			InternalName = "/Lotus/Types/Items/Titles/ClemTitle",
			CodexSecret = true,
			ExcludeFromCodex = true,
	},
	["Cœur Enflammé"] = {
			Name = "Cœur Enflammé",
			Link = "Cœur Enflammé",
			Description = "",
			Position = "Suffix",
			Introduced = "",
			InternalName = "/Lotus/Types/Items/Titles/DateMarieTitle",
			CodexSecret = true,
			ExcludeFromCodex = true,
	},
	["Conscience Painter"] = {
			Name = "Conscience Painter",
			Link = "Conscience Painter",
			Description = "",
			Position = "Prefix",
			Introduced = "42",
			InternalName = "/Lotus/Types/Items/Titles/RoatheTitles/TitleFollie",
			CodexSecret = true,
			ExcludeFromCodex = true,
	},
	["Conscientious Objector"] = {
			Name = "Conscientious Objector",
			Link = "Conscientious Objector",
			Description = "",
			Position = "Suffix",
			Introduced = "43.5",
			InternalName = "/Lotus/Types/Items/Titles/RoatheTitles/BaruukTitle",
			CodexSecret = true,
			ExcludeFromCodex = true,
	},
	["Cryomancer"] = {
			Name = "Cryomancer",
			Link = "Cryomancer",
			Description = "",
			Position = "Suffix",
			Introduced = "43.5",
			InternalName = "/Lotus/Types/Items/Titles/RoatheTitles/FrostTitle",
			CodexSecret = true,
			ExcludeFromCodex = true,
	},
	["Death from Above"] = {
			Name = "Death from Above",
			Link = "Death from Above",
			Description = "",
			Position = "Suffix",
			Introduced = "43.5",
			InternalName = "/Lotus/Types/Items/Titles/FromOnHighTitle",
			CodexSecret = true,
			ExcludeFromCodex = true,
	},
	["Defender of the Earth"] = {
			Name = "Defender of the Earth",
			Link = "Defender of the Earth",
			Description = "",
			Position = "Prefix",
			Introduced = "42",
			InternalName = "/Lotus/Types/Items/Titles/NewLokaTitle",
			CodexSecret = true,
			ExcludeFromCodex = true,
	},
	["Demoness"] = {
			Name = "Demoness",
			Link = "Demoness",
			Description = "",
			Position = "Prefix",
			Introduced = "20",
			InternalName = "/Lotus/Types/Items/Titles/RoatheTitles/TitleMaphica",
			CodexSecret = true,
			ExcludeFromCodex = true,
	},
	["Devil's Own"] = {
			Name = "Devil's Own",
			Link = "Devil's Own",
			Description = "",
			Position = "Prefix",
			Introduced = "",
			InternalName = "/Lotus/Types/Items/Titles/DateRoatheTitle",
			CodexSecret = true,
			ExcludeFromCodex = true,
	},
	["Diplomatic Merchant"] = {
			Name = "Diplomatic Merchant",
			Link = "Diplomatic Merchant",
			Description = "",
			Position = "Prefix",
			Introduced = "42",
			InternalName = "/Lotus/Types/Items/Titles/PerrinSequenceTitle",
			CodexSecret = true,
			ExcludeFromCodex = true,
	},
	["Disciple"] = {
			Name = "Disciple",
			Link = "Disciple",
			Description = "",
			Position = "Prefix",
			Introduced = "",
			InternalName = "/Lotus/Types/Items/Titles/MR7Title",
			CodexSecret = true,
			ExcludeFromCodex = true,
	},
	["Divine Comedian"] = {
			Name = "Divine Comedian",
			Link = "Divine Comedian",
			Description = "",
			Position = "Suffix",
			Introduced = "",
			InternalName = "/Lotus/Types/Items/Titles/DanteDescendiaTitle",
			CodexSecret = true,
			ExcludeFromCodex = true,
	},
	["Doctor"] = {
			Name = "Doctor",
			Link = "Doctor",
			Description = "",
			Position = "Prefix",
			Introduced = "43.5",
			InternalName = "/Lotus/Types/Items/Titles/RoatheTitles/TrinityTitle",
			CodexSecret = true,
			ExcludeFromCodex = true,
	},
	["Doesn't Miss"] = {
			Name = "Doesn't Miss",
			Link = "Doesn't Miss",
			Description = "",
			Position = "Suffix",
			Introduced = "",
			InternalName = "/Lotus/Types/Items/Titles/SharpShooterTitle",
			CodexSecret = true,
			ExcludeFromCodex = true,
	},
	["Double Trouble"] = {
			Name = "Double Trouble",
			Link = "Double Trouble",
			Description = "",
			Position = "Suffix",
			Introduced = "",
			InternalName = "/Lotus/Types/Items/Titles/CompleteDescendiaUrielTitle",
			CodexSecret = true,
			ExcludeFromCodex = true,
	},
	["Dragon"] = {
			Name = "Dragon",
			Link = "Dragon",
			Description = "",
			Position = "Prefix",
			Introduced = "42",
			InternalName = "/Lotus/Types/Items/Titles/MR22Title",
			CodexSecret = true,
			ExcludeFromCodex = true,
	},
	["Dream Catcher"] = {
			Name = "Dream Catcher",
			Link = "Dream Catcher",
			Description = "",
			Position = "Suffix",
			Introduced = "43",
			InternalName = "/Lotus/Types/Items/Titles/ReferAFriendTitle",
			CodexSecret = true,
			ExcludeFromCodex = true,
	},
	["Drifter"] = {
			Name = "Drifter",
			Link = "Drifter",
			Description = "",
			Position = "Suffix",
			Introduced = "",
			InternalName = "/Lotus/Types/Items/Titles/TheNewWarTitle",
			CodexSecret = true,
			ExcludeFromCodex = true,
	},
	["Eagle"] = {
			Name = "Eagle",
			Link = "Eagle",
			Description = "",
			Position = "Prefix",
			Introduced = "42",
			InternalName = "/Lotus/Types/Items/Titles/MR16Title",
			CodexSecret = true,
			ExcludeFromCodex = true,
	},
	["Early Lunch for"] = {
			Name = "Early Lunch for",
			Link = "Early Lunch for",
			Description = "",
			Position = "Prefix",
			Introduced = "41",
			InternalName = "/Lotus/Types/Items/Titles/RoatheTitles/TitleKonzu",
			CodexSecret = true,
			ExcludeFromCodex = true,
	},
	["Eradicator of Corruption"] = {
			Name = "Eradicator of Corruption",
			Link = "Eradicator of Corruption",
			Description = "",
			Position = "Suffix",
			Introduced = "42",
			InternalName = "/Lotus/Types/Items/Titles/RedVeilTitle",
			CodexSecret = true,
			ExcludeFromCodex = true,
	},
	["Executive Overrider"] = {
			Name = "Executive Overrider",
			Link = "Executive Overrider",
			Description = "",
			Position = "Prefix",
			Introduced = "",
			InternalName = "/Lotus/Types/Items/Titles/SisterKillerTitle",
			CodexSecret = true,
			ExcludeFromCodex = true,
	},
	["Exorcist"] = {
			Name = "Exorcist",
			Link = "Exorcist",
			Description = "",
			Position = "Suffix",
			Introduced = "",
			InternalName = "/Lotus/Types/Items/Titles/UrielKillerTitle",
			CodexSecret = true,
			ExcludeFromCodex = true,
	},
	["Facilis Descensus Averno"] = {
			Name = "Facilis Descensus Averno",
			Link = "Facilis Descensus Averno",
			Description = "",
			Position = "Prefix",
			Introduced = "",
			InternalName = "/Lotus/Types/Items/Titles/CompleteDescendiaHardcoreTitle",
			CodexSecret = true,
			ExcludeFromCodex = true,
	},
	["Fatuous Nymph"] = {
			Name = "Fatuous Nymph",
			Link = "Fatuous Nymph",
			Description = "",
			Position = "Prefix",
			Introduced = "41",
			InternalName = "/Lotus/Types/Items/Titles/RoatheTitles/TitleYareli",
			CodexSecret = true,
			ExcludeFromCodex = true,
	},
	["Feelin' Lucky"] = {
			Name = "Feelin' Lucky",
			Link = "Feelin' Lucky",
			Description = "",
			Position = "Suffix",
			Introduced = "43",
			InternalName = "/Lotus/Types/Items/Titles/HunhowHonoria/TitleMesa",
			CodexSecret = true,
			ExcludeFromCodex = true,
	},
	["Fire and Brimstone"] = {
			Name = "Fire and Brimstone",
			Link = "Fire and Brimstone",
			Description = "",
			Position = "Suffix",
			Introduced = "41",
			InternalName = "/Lotus/Types/Items/Titles/RoatheTitles/TitleIgnia",
			CodexSecret = true,
			ExcludeFromCodex = true,
	},
	["Force of Nature"] = {
			Name = "Force of Nature",
			Link = "Force of Nature",
			Description = "",
			Position = "Suffix",
			Introduced = "43",
			InternalName = "/Lotus/Types/Items/Titles/HunhowHonoria/TitleMag",
			CodexSecret = true,
			ExcludeFromCodex = true,
	},
	["Forever"] = {
			Name = "Forever",
			Link = "Forever",
			Description = "",
			Position = "Suffix",
			Introduced = "41",
			InternalName = "/Lotus/Types/Items/Titles/RoatheTitles/TitleArgon",
			CodexSecret = true,
			ExcludeFromCodex = true,
	},
	["Fragmented"] = {
			Name = "Fragmented",
			Link = "Fragmented",
			Description = "",
			Position = "Prefix",
			Introduced = "",
			InternalName = "/Lotus/Types/Items/Titles/HardFragmentedTitle",
			CodexSecret = true,
			ExcludeFromCodex = true,
	},
	["Friend of Sentients"] = {
			Name = "Friend of Sentients",
			Link = "Friend of Sentients",
			Description = "",
			Position = "Suffix",
			Introduced = "",
			InternalName = "/Lotus/Types/Items/Titles/SentientFriendTitle",
			CodexSecret = true,
			ExcludeFromCodex = true,
	},
	["Giant Slayer"] = {
			Name = "Giant Slayer",
			Link = "Giant Slayer",
			Description = "",
			Position = "Suffix",
			Introduced = "43",
			InternalName = "/Lotus/Types/Items/Titles/EidolonHunterTitle",
			CodexSecret = true,
			ExcludeFromCodex = true,
	},
	["Grandis"] = {
			Name = "Grandis",
			Link = "Grandis",
			Description = "",
			Position = "Prefix",
			Introduced = "41.0.5",
			InternalName = "/Lotus/Types/Items/Titles/MedalRank17Title",
			CodexSecret = true,
			ExcludeFromCodex = true,
	},
	["Gyanbura"] = {
			Name = "Gyanbura",
			Link = "Gyanbura",
			Description = "",
			Position = "Suffix",
			Introduced = "41",
			InternalName = "/Lotus/Types/Items/Titles/RoatheTitles/TitleKoumei",
			CodexSecret = true,
			ExcludeFromCodex = true,
	},
	["Hai-Luk's Wholesaler"] = {
			Name = "Hai-Luk's Wholesaler",
			Link = "Hai-Luk's Wholesaler",
			Description = "",
			Position = "Suffix",
			Introduced = "",
			InternalName = "/Lotus/Types/Items/Titles/FisherTitle",
			CodexSecret = true,
			ExcludeFromCodex = true,
	},
	["Harrow's Shadow"] = {
			Name = "Harrow's Shadow",
			Link = "Harrow's Shadow",
			Description = "",
			Position = "Suffix",
			Introduced = "",
			InternalName = "/Lotus/Types/Items/Titles/CompleteDescendiaHarrowTitle",
			CodexSecret = true,
			ExcludeFromCodex = true,
	},
	["Head Cracker"] = {
			Name = "Head Cracker",
			Link = "Head Cracker",
			Description = "",
			Position = "Suffix",
			Introduced = "43.5",
			InternalName = "/Lotus/Types/Items/Titles/RoatheTitles/FrumentariusTitle",
			CodexSecret = true,
			ExcludeFromCodex = true,
	},
	["Heart of Concrete"] = {
			Name = "Heart of Concrete",
			Link = "Heart of Concrete",
			Description = "",
			Position = "Prefix",
			Introduced = "42",
			InternalName = "/Lotus/Types/Items/Titles/RoatheTitles/TitleQorvex",
			CodexSecret = true,
			ExcludeFromCodex = true,
	},
	["Heart of the Pack"] = {
			Name = "Heart of the Pack",
			Link = "Heart of the Pack",
			Description = "",
			Position = "Suffix",
			Introduced = "42.0.6",
			InternalName = "/Lotus/Types/Items/Titles/TitleVorunaPrime",
			CodexSecret = true,
			ExcludeFromCodex = true,
	},
	["Heart Shot"] = {
			Name = "Heart Shot",
			Link = "Heart Shot",
			Description = "",
			Position = "Suffix",
			Introduced = "",
			InternalName = "/Lotus/Types/Items/Titles/DateQuincyTitle",
			CodexSecret = true,
			ExcludeFromCodex = true,
	},
	["Hive-kin"] = {
			Name = "Hive-kin",
			Link = "Hive-kin",
			Description = "",
			Position = "Prefix",
			Introduced = "41",
			InternalName = "/Lotus/Types/Items/Titles/RoatheTitles/TitleAscarisPrime",
			CodexSecret = true,
			ExcludeFromCodex = true,
	},
	["Hoplite"] = {
			Name = "Hoplite",
			Link = "Hoplite",
			Description = "",
			Position = "Suffix",
			Introduced = "43",
			InternalName = "/Lotus/Types/Items/Titles/TitleStyanaxPrime",
			CodexSecret = true,
			ExcludeFromCodex = true,
	},
	["Hot Sludge"] = {
			Name = "Hot Sludge",
			Link = "Hot Sludge",
			Description = "",
			Position = "Suffix",
			Introduced = "41",
			InternalName = "/Lotus/Types/Items/Titles/RoatheTitles/TitleThermalSludge",
			CodexSecret = true,
			ExcludeFromCodex = true,
	},
	["Hotwired"] = {
			Name = "Hotwired",
			Link = "Hotwired",
			Description = "",
			Position = "Suffix",
			Introduced = "",
			InternalName = "/Lotus/Types/Items/Titles/HotwiredTitle",
			CodexSecret = true,
			ExcludeFromCodex = true,
	},
	["Hunter"] = {
			Name = "Hunter",
			Link = "Hunter",
			Description = "",
			Position = "Prefix",
			Introduced = "42",
			InternalName = "/Lotus/Types/Items/Titles/MR13Title",
			CodexSecret = true,
			ExcludeFromCodex = true,
	},
	["Initiate"] = {
			Name = "Initiate",
			Link = "Initiate",
			Description = "",
			Position = "Prefix",
			Introduced = "42",
			InternalName = "/Lotus/Types/Items/Titles/MR1Title",
			CodexSecret = true,
			ExcludeFromCodex = true,
	},
	["Insign"] = {
			Name = "Insign",
			Link = "Insign",
			Description = "",
			Position = "Prefix",
			Introduced = "41.0.5",
			InternalName = "/Lotus/Types/Items/Titles/MedalRank1Title",
			CodexSecret = true,
			ExcludeFromCodex = true,
	},
	["Ironclad"] = {
			Name = "Ironclad",
			Link = "Ironclad",
			Description = "",
			Position = "Suffix",
			Introduced = "41",
			InternalName = "/Lotus/Types/Items/Titles/RoatheTitles/TitleFerrite",
			CodexSecret = true,
			ExcludeFromCodex = true,
	},
	["It Will Kill"] = {
			Name = "It Will Kill",
			Link = "It Will Kill",
			Description = "",
			Position = "Suffix",
			Introduced = "43.5",
			InternalName = "/Lotus/Types/Items/Titles/ForgedInFireTitle",
			CodexSecret = true,
			ExcludeFromCodex = true,
	},
	["It's All Relative"] = {
			Name = "It's All Relative",
			Link = "It's All Relative",
			Description = "",
			Position = "Suffix",
			Introduced = "43.5",
			InternalName = "/Lotus/Types/Items/Titles/RoatheTitles/NovaTitle",
			CodexSecret = true,
			ExcludeFromCodex = true,
	},
	["Jade's Guardian"] = {
			Name = "Jade's Guardian",
			Link = "Jade's Guardian",
			Description = "",
			Position = "Suffix",
			Introduced = "41",
			InternalName = "/Lotus/Types/Items/Titles/RoatheTitles/TitleJade",
			CodexSecret = true,
			ExcludeFromCodex = true,
	},
	["Jammer"] = {
			Name = "Jammer",
			Link = "Jammer",
			Description = "",
			Position = "Prefix",
			Introduced = "",
			InternalName = "/Lotus/Types/Items/Titles/JammerTitle",
			CodexSecret = true,
			ExcludeFromCodex = true,
	},
	["Kaithe Tamer of Duviri"] = {
			Name = "Kaithe Tamer of Duviri",
			Link = "Kaithe Tamer of Duviri",
			Description = "",
			Position = "Prefix",
			Introduced = "41",
			InternalName = "/Lotus/Types/Items/Titles/RoatheTitles/TitleYaoShrub",
			CodexSecret = true,
			ExcludeFromCodex = true,
	},
	["Kalymos's Best Friend"] = {
			Name = "Kalymos's Best Friend",
			Link = "Kalymos's Best Friend",
			Description = "",
			Position = "Suffix",
			Introduced = "",
			InternalName = "/Lotus/Types/Items/Titles/KalymosTitle",
			CodexSecret = true,
			ExcludeFromCodex = true,
	},
	["Keeper of Secrets"] = {
			Name = "Keeper of Secrets",
			Link = "Keeper of Secrets",
			Description = "",
			Position = "Suffix",
			Introduced = "43",
			InternalName = "/Lotus/Types/Items/Titles/HunhowHonoria/TitleDanteDeluxe",
			CodexSecret = true,
			ExcludeFromCodex = true,
	},
	["King of Duviri"] = {
			Name = "King of Duviri",
			Link = "King of Duviri",
			Description = "",
			Position = "Suffix",
			Introduced = "",
			InternalName = "/Lotus/Types/Items/Titles/DuviriKingQuestTitle",
			CodexSecret = true,
			ExcludeFromCodex = true,
	},
	["l33t h4XX0r"] = {
			Name = "l33t h4XX0r",
			Link = "l33t h4XX0r",
			Description = "",
			Position = "Prefix",
			Introduced = "",
			InternalName = "/Lotus/Types/Items/Titles/DateAmirTitle",
			CodexSecret = true,
			ExcludeFromCodex = true,
	},
	["Lamenting One"] = {
			Name = "Lamenting One",
			Link = "Lamenting One",
			Description = "",
			Position = "Suffix",
			Introduced = "41",
			InternalName = "/Lotus/Types/Items/Titles/RoatheTitles/TitleLamentus",
			CodexSecret = true,
			ExcludeFromCodex = true,
	},
	["Leaves No Witnesses"] = {
			Name = "Leaves No Witnesses",
			Link = "Leaves No Witnesses",
			Description = "",
			Position = "Suffix",
			Introduced = "43.5",
			InternalName = "/Lotus/Types/Items/Titles/StealthKills100Title",
			CodexSecret = true,
			ExcludeFromCodex = true,
	},
	["Legendary Captain"] = {
			Name = "Legendary Captain",
			Link = "Legendary Captain",
			Description = "",
			Position = "Prefix",
			Introduced = "",
			InternalName = "/Lotus/Types/Items/Titles/MaxedRailjackTitle",
			CodexSecret = true,
			ExcludeFromCodex = true,
	},
	["Liberated Grineer"] = {
			Name = "Liberated Grineer",
			Link = "Liberated Grineer",
			Description = "",
			Position = "Suffix",
			Introduced = "42",
			InternalName = "/Lotus/Types/Items/Titles/SteelMeridianTitle",
			CodexSecret = true,
			ExcludeFromCodex = true,
	},
	["Like Father, Like Sons"] = {
			Name = "Like Father, Like Sons",
			Link = "Like Father, Like Sons",
			Description = "",
			Position = "Suffix",
			Introduced = "",
			InternalName = "/Lotus/Types/Items/Titles/JadeShadows2Title",
			CodexSecret = true,
			ExcludeFromCodex = true,
	},
	["Lyon's Savior"] = {
			Name = "Lyon's Savior",
			Link = "Lyon's Savior",
			Description = "",
			Position = "Suffix",
			Introduced = "",
			InternalName = "/Lotus/Types/Items/Titles/DefendLyonTitle",
			CodexSecret = true,
			ExcludeFromCodex = true,
	},
	["Madurai Vanguard"] = {
			Name = "Madurai Vanguard",
			Link = "Madurai Vanguard",
			Description = "",
			Position = "Prefix",
			Introduced = "41",
			InternalName = "/Lotus/Types/Items/Titles/MaduraiFocusHoarderTitle",
			CodexSecret = true,
			ExcludeFromCodex = true,
	},
	["Make Your Own Fate"] = {
			Name = "Make Your Own Fate",
			Link = "Make Your Own Fate",
			Description = "",
			Position = "Prefix",
			Introduced = "",
			InternalName = "/Lotus/Types/Items/Titles/GuardianTitle",
			CodexSecret = true,
			ExcludeFromCodex = true,
	},
	["Marauder of the Deep"] = {
			Name = "Marauder of the Deep",
			Link = "Marauder of the Deep",
			Description = "",
			Position = "Suffix",
			Introduced = "42",
			InternalName = "/Lotus/Types/Items/Titles/RoatheTitles/TitleHydroid",
			CodexSecret = true,
			ExcludeFromCodex = true,
	},
	["Marie's Champion"] = {
			Name = "Marie's Champion",
			Link = "Marie's Champion",
			Description = "",
			Position = "Suffix",
			Introduced = "",
			InternalName = "/Lotus/Types/Items/Titles/DefendMarieTitle",
			CodexSecret = true,
			ExcludeFromCodex = true,
	},
	["Marty <NAME> McFlea"] = {
			Name = "Marty <NAME> McFlea",
			Link = "Marty <NAME> McFlea",
			Description = "",
			Position = "Suffix & Prefix",
			Introduced = "43.5",
			InternalName = "/Lotus/Types/Items/Titles/TheHexCompleteTitle",
			CodexSecret = true,
			ExcludeFromCodex = true,
	},
	["Master"] = {
			Name = "Master",
			Link = "Master",
			Description = "",
			Position = "Prefix",
			Introduced = "42",
			InternalName = "/Lotus/Types/Items/Titles/MR28Title",
			CodexSecret = true,
			ExcludeFromCodex = true,
	},
	["Master of Minds"] = {
			Name = "Master of Minds",
			Link = "Master of Minds",
			Description = "",
			Position = "Suffix",
			Introduced = "43.5",
			InternalName = "/Lotus/Types/Items/Titles/RoatheTitles/NyxTitle",
			CodexSecret = true,
			ExcludeFromCodex = true,
	},
	["Matriarch"] = {
			Name = "Matriarch",
			Link = "Matriarch",
			Description = "",
			Position = "Prefix",
			Introduced = "41",
			InternalName = "/Lotus/Types/Items/Titles/RoatheTitles/TitleMotherTokens",
			CodexSecret = true,
			ExcludeFromCodex = true,
	},
	["Matron of Malaise"] = {
			Name = "Matron of Malaise",
			Link = "Matron of Malaise",
			Description = "",
			Position = "Prefix",
			Introduced = "42",
			InternalName = "/Lotus/Types/Items/Titles/RoatheTitles/TitleSaryn",
			CodexSecret = true,
			ExcludeFromCodex = true,
	},
	["Mayor of Corpus City"] = {
			Name = "Mayor of Corpus City",
			Link = "Mayor of Corpus City",
			Description = "",
			Position = "Suffix",
			Introduced = "41",
			InternalName = "/Lotus/Types/Items/Titles/RoatheTitles/TitleHexenon",
			CodexSecret = true,
			ExcludeFromCodex = true,
	},
	["Messenger of Long Forgotten Gods"] = {
			Name = "Messenger of Long Forgotten Gods",
			Link = "Messenger of Long Forgotten Gods",
			Description = "",
			Position = "Suffix",
			Introduced = "42",
			InternalName = "/Lotus/Types/Items/Titles/TitleGaussPrime",
			CodexSecret = true,
			ExcludeFromCodex = true,
	},
	["Minesweeper"] = {
			Name = "Minesweeper",
			Link = "Minesweeper",
			Description = "",
			Position = "Prefix",
			Introduced = "",
			InternalName = "/Lotus/Types/Items/Titles/MinesweeperTitle",
			CodexSecret = true,
			ExcludeFromCodex = true,
	},
	["Mountain Soul"] = {
			Name = "Mountain Soul",
			Link = "Mountain Soul",
			Description = "",
			Position = "Suffix",
			Introduced = "",
			InternalName = "/Lotus/Types/Items/Titles/UnairuHammerTitle",
			CodexSecret = true,
			ExcludeFromCodex = true,
	},
	["My Light Goes With You"] = {
			Name = "My Light Goes With You",
			Link = "My Light Goes With You",
			Description = "",
			Position = "Prefix",
			Introduced = "",
			InternalName = "/Lotus/Types/Items/Titles/PeritaHardModeTitle",
			CodexSecret = true,
			ExcludeFromCodex = true,
	},
	["Naramon Vanguard"] = {
			Name = "Naramon Vanguard",
			Link = "Naramon Vanguard",
			Description = "",
			Position = "Prefix",
			Introduced = "41",
			InternalName = "/Lotus/Types/Items/Titles/NaramonFocusHoarderTitle",
			CodexSecret = true,
			ExcludeFromCodex = true,
	},
	["Nemesis Of Eris"] = {
			Name = "Nemesis Of Eris",
			Link = "Nemesis Of Eris",
			Description = "",
			Position = "Suffix",
			Introduced = "",
			InternalName = "/Lotus/Types/Items/Titles/NemesisOfErisTitle",
			CodexSecret = true,
			ExcludeFromCodex = true,
	},
	["Night Gardener"] = {
			Name = "Night Gardener",
			Link = "Night Gardener",
			Description = "",
			Position = "Prefix",
			Introduced = "41",
			InternalName = "/Lotus/Types/Items/Titles/RoatheTitles/TitleNokko",
			CodexSecret = true,
			ExcludeFromCodex = true,
	},
	["Novice"] = {
			Name = "Novice",
			Link = "Novice",
			Description = "",
			Position = "Suffix",
			Introduced = "42",
			InternalName = "/Lotus/Types/Items/Titles/MR4Title",
			CodexSecret = true,
			ExcludeFromCodex = true,
	},
	["Oblivion's Kiss"] = {
			Name = "Oblivion's Kiss",
			Link = "Oblivion's Kiss",
			Description = "",
			Position = "Suffix",
			Introduced = "42",
			InternalName = "/Lotus/Types/Items/Titles/RoatheTitles/TitleCyteZeroNine",
			CodexSecret = true,
			ExcludeFromCodex = true,
	},
	["Of Golden Valor"] = {
			Name = "Of Golden Valor",
			Link = "Of Golden Valor",
			Description = "",
			Position = "Suffix",
			Introduced = "",
			InternalName = "/Lotus/Types/Items/Titles/ValorEventTitle",
			CodexSecret = true,
			ExcludeFromCodex = true,
	},
	["of the Old Blood"] = {
			Name = "of the Old Blood",
			Link = "of the Old Blood",
			Description = "",
			Position = "Suffix",
			Introduced = "",
			InternalName = "/Lotus/Types/Items/Titles/LichKillerTitle",
			CodexSecret = true,
			ExcludeFromCodex = true,
	},
	["Ollie's Biggest Fan"] = {
			Name = "Ollie's Biggest Fan",
			Link = "Ollie's Biggest Fan",
			Description = "",
			Position = "Suffix",
			Introduced = "",
			InternalName = "/Lotus/Types/Items/Titles/OllieRacerTitle",
			CodexSecret = true,
			ExcludeFromCodex = true,
	},
	["On That Far Shore Forlorn"] = {
			Name = "On That Far Shore Forlorn",
			Link = "On That Far Shore Forlorn",
			Description = "",
			Position = "Suffix",
			Introduced = "41",
			InternalName = "/Lotus/Types/Items/Titles/RoatheTitles/TitleLyoricBridge",
			CodexSecret = true,
			ExcludeFromCodex = true,
	},
	["On this Beach of an Earth"] = {
			Name = "On this Beach of an Earth",
			Link = "On this Beach of an Earth",
			Description = "",
			Position = "Prefix",
			Introduced = "",
			InternalName = "/Lotus/Types/Items/Titles/DogDaysTitle",
			CodexSecret = true,
			ExcludeFromCodex = true,
	},
	["On-lyne Fan"] = {
			Name = "On-lyne Fan",
			Link = "On-lyne Fan",
			Description = "",
			Position = "Prefix",
			Introduced = "",
			InternalName = "/Lotus/Types/Items/Titles/CodaKillerTitle",
			CodexSecret = true,
			ExcludeFromCodex = true,
	},
	["On-Lyne Superfan"] = {
			Name = "On-Lyne Superfan",
			Link = "On-Lyne Superfan",
			Description = "",
			Position = "Prefix",
			Introduced = "",
			InternalName = "/Lotus/Types/Items/Titles/CodaMasteryTitle",
			CodexSecret = true,
			ExcludeFromCodex = true,
	},
	["Once and Future"] = {
			Name = "Once and Future",
			Link = "Once and Future",
			Description = "",
			Position = "Prefix",
			Introduced = "",
			InternalName = "/Lotus/Types/Items/Titles/DateArthurTitle",
			CodexSecret = true,
			ExcludeFromCodex = true,
	},
	["Oraxia's Prey"] = {
			Name = "Oraxia's Prey",
			Link = "Oraxia's Prey",
			Description = "",
			Position = "Suffix",
			Introduced = "",
			InternalName = "/Lotus/Types/Items/Titles/OraxiaPreyTitle",
			CodexSecret = true,
			ExcludeFromCodex = true,
	},
	["Orb Liquidator"] = {
			Name = "Orb Liquidator",
			Link = "Orb Liquidator",
			Description = "",
			Position = "Prefix",
			Introduced = "",
			InternalName = "/Lotus/Types/Items/Titles/OrbHunterTitle",
			CodexSecret = true,
			ExcludeFromCodex = true,
	},
	["Orokin Cell Executor"] = {
			Name = "Orokin Cell Executor",
			Link = "Orokin Cell Executor",
			Description = "",
			Position = "Suffix",
			Introduced = "41",
			InternalName = "/Lotus/Types/Items/Titles/RoatheTitles/TitleOrokinCell",
			CodexSecret = true,
			ExcludeFromCodex = true,
	},
	["Painted Free"] = {
			Name = "Painted Free",
			Link = "Painted Free",
			Description = "",
			Position = "Suffix",
			Introduced = "",
			InternalName = "/Lotus/Types/Items/Titles/FollieHuntOneTitle",
			CodexSecret = true,
			ExcludeFromCodex = true,
	},
	["Paper Crane"] = {
			Name = "Paper Crane",
			Link = "Paper Crane",
			Description = "",
			Position = "Suffix",
			Introduced = "",
			InternalName = "/Lotus/Types/Items/Titles/DateAoiTitle",
			CodexSecret = true,
			ExcludeFromCodex = true,
	},
	["Parazon Runner"] = {
			Name = "Parazon Runner",
			Link = "Parazon Runner",
			Description = "",
			Position = "Suffix",
			Introduced = "43.5",
			InternalName = "/Lotus/Types/Items/Titles/SolveCipherUnder5Title",
			CodexSecret = true,
			ExcludeFromCodex = true,
	},
	["Pas de Deux"] = {
			Name = "Pas de Deux",
			Link = "Pas de Deux",
			Description = "",
			Position = "Prefix",
			Introduced = "",
			InternalName = "/Lotus/Types/Items/Titles/CompleteDescendiaWispTitle",
			CodexSecret = true,
			ExcludeFromCodex = true,
	},
	["Patriarch"] = {
			Name = "Patriarch",
			Link = "Patriarch",
			Description = "",
			Position = "Suffix",
			Introduced = "41",
			InternalName = "/Lotus/Types/Items/Titles/RoatheTitles/TitleFatherTokens",
			CodexSecret = true,
			ExcludeFromCodex = true,
	},
	["Payer of the Ferryman"] = {
			Name = "Payer of the Ferryman",
			Link = "Payer of the Ferryman",
			Description = "",
			Position = "Prefix",
			Introduced = "41",
			InternalName = "/Lotus/Types/Items/Titles/RoatheTitles/TitleEntratiObols",
			CodexSecret = true,
			ExcludeFromCodex = true,
	},
	["Perigone"] = {
			Name = "Perigone",
			Link = "Perigone",
			Description = "",
			Position = "Prefix",
			Introduced = "41.0.5",
			InternalName = "/Lotus/Types/Items/Titles/MedalRank20Title",
			CodexSecret = true,
			ExcludeFromCodex = true,
	},
	["Pizza Time for"] = {
			Name = "Pizza Time for",
			Link = "Pizza Time for",
			Description = "",
			Position = "Suffix",
			Introduced = "43.5",
			InternalName = "/Lotus/Types/Items/Titles/TheHexFinaleTitle",
			CodexSecret = true,
			ExcludeFromCodex = true,
	},
	["Plague Doctor"] = {
			Name = "Plague Doctor",
			Link = "Plague Doctor",
			Description = "",
			Position = "Suffix",
			Introduced = "43.5",
			InternalName = "/Lotus/Types/Items/Titles/KillPhoridTitle",
			CodexSecret = true,
			ExcludeFromCodex = true,
	},
	["Plague-bearer"] = {
			Name = "Plague-bearer",
			Link = "Plague-bearer",
			Description = "",
			Position = "Prefix",
			Introduced = "43",
			InternalName = "/Lotus/Types/Items/Titles/HunhowHonoria/TitleNidus",
			CodexSecret = true,
			ExcludeFromCodex = true,
	},
	["Pleasure and Pain"] = {
			Name = "Pleasure and Pain",
			Link = "Pleasure and Pain",
			Description = "",
			Position = "Suffix",
			Introduced = "",
			InternalName = "/Lotus/Types/Items/Titles/DateLettieTitle",
			CodexSecret = true,
			ExcludeFromCodex = true,
	},
	["Queen of Duviri"] = {
			Name = "Queen of Duviri",
			Link = "Queen of Duviri",
			Description = "",
			Position = "Prefix",
			Introduced = "",
			InternalName = "/Lotus/Types/Items/Titles/DuviriQueenQuestTitle",
			CodexSecret = true,
			ExcludeFromCodex = true,
	},
	["Restless"] = {
			Name = "Restless",
			Link = "Restless",
			Description = "",
			Position = "Suffix",
			Introduced = "43.5",
			InternalName = "/Lotus/Types/Items/Titles/PoENightTitle",
			CodexSecret = true,
			ExcludeFromCodex = true,
	},
	["Rusalka's Hope"] = {
			Name = "Rusalka's Hope",
			Link = "Rusalka's Hope",
			Description = "",
			Position = "Prefix",
			Introduced = "",
			InternalName = "/Lotus/Types/Items/Titles/MinVelTogetherTitle",
			CodexSecret = true,
			ExcludeFromCodex = true,
	},
	["Sage"] = {
			Name = "Sage",
			Link = "Sage",
			Description = "",
			Position = "Suffix",
			Introduced = "42",
			InternalName = "/Lotus/Types/Items/Titles/MR25Title",
			CodexSecret = true,
			ExcludeFromCodex = true,
	},
	["Saint of Altra"] = {
			Name = "Saint of Altra",
			Link = "Saint of Altra",
			Description = "",
			Position = "Suffix",
			Introduced = "42",
			InternalName = "/Lotus/Types/Items/Titles/RoatheTitles/TitleGauss",
			CodexSecret = true,
			ExcludeFromCodex = true,
	},
	["Savior of Perita"] = {
			Name = "Savior of Perita",
			Link = "Savior of Perita",
			Description = "",
			Position = "Suffix",
			Introduced = "",
			InternalName = "/Lotus/Types/Items/Titles/PeritaHardModeSoloTitle",
			CodexSecret = true,
			ExcludeFromCodex = true,
	},
	["Scholar of Secrets"] = {
			Name = "Scholar of Secrets",
			Link = "Scholar of Secrets",
			Description = "",
			Position = "Suffix",
			Introduced = "",
			InternalName = "/Lotus/Types/Items/Titles/ZenurikGrimoireTitle",
			CodexSecret = true,
			ExcludeFromCodex = true,
	},
	["Scoria's Saint"] = {
			Name = "Scoria's Saint",
			Link = "Scoria's Saint",
			Description = "",
			Position = "Suffix",
			Introduced = "43",
			InternalName = "/Lotus/Types/Items/Titles/HunhowHonoria/TitleAsh",
			CodexSecret = true,
			ExcludeFromCodex = true,
	},
	["Seeker"] = {
			Name = "Seeker",
			Link = "Seeker",
			Description = "",
			Position = "Prefix",
			Introduced = "42",
			InternalName = "/Lotus/Types/Items/Titles/MR10Title",
			CodexSecret = true,
			ExcludeFromCodex = true,
	},
	["Seeker of Truth"] = {
			Name = "Seeker of Truth",
			Link = "Seeker of Truth",
			Description = "",
			Position = "Prefix",
			Introduced = "42",
			InternalName = "/Lotus/Types/Items/Titles/ArbitersOfHexisTitle",
			CodexSecret = true,
			ExcludeFromCodex = true,
	},
	["Sentinel of Passion"] = {
			Name = "Sentinel of Passion",
			Link = "Sentinel of Passion",
			Description = "",
			Position = "Prefix",
			Introduced = "41",
			InternalName = "/Lotus/Types/Items/Titles/RoatheTitles/TitleCitrine",
			CodexSecret = true,
			ExcludeFromCodex = true,
	},
	["Servio"] = {
			Name = "Servio",
			Link = "Servio",
			Description = "",
			Position = "Prefix",
			Introduced = "41.0.5",
			InternalName = "/Lotus/Types/Items/Titles/MedalRank5Title",
			CodexSecret = true,
			ExcludeFromCodex = true,
	},
	["Shadow Conservator"] = {
			Name = "Shadow Conservator",
			Link = "Shadow Conservator",
			Description = "",
			Position = "Prefix",
			Introduced = "",
			InternalName = "/Lotus/Types/Items/Titles/ShadowgrapherEventVendorTitle",
			CodexSecret = true,
			ExcludeFromCodex = true,
	},
	["Shadowgrapher"] = {
			Name = "Shadowgrapher",
			Link = "Shadowgrapher",
			Description = "",
			Position = "Prefix",
			Introduced = "",
			InternalName = "/Lotus/Types/Items/Titles/FollieHuntTenTitle",
			CodexSecret = true,
			ExcludeFromCodex = true,
	},
	["Silver Tongue"] = {
			Name = "Silver Tongue",
			Link = "Silver Tongue",
			Description = "",
			Position = "Prefix",
			Introduced = "",
			InternalName = "/Lotus/Types/Items/Titles/DateEleanorTitle",
			CodexSecret = true,
			ExcludeFromCodex = true,
	},
	["Sleeping in the Cold Below"] = {
			Name = "Sleeping in the Cold Below",
			Link = "Sleeping in the Cold Below",
			Description = "",
			Position = "Suffix",
			Introduced = "",
			InternalName = "/Lotus/Types/Items/Titles/TenetMasteryTitle",
			CodexSecret = true,
			ExcludeFromCodex = true,
	},
	["Soulmate"] = {
			Name = "Soulmate",
			Link = "Soulmate",
			Description = "",
			Position = "Suffix",
			Introduced = "",
			InternalName = "/Lotus/Types/Items/Titles/DateLyonTitle",
			CodexSecret = true,
			ExcludeFromCodex = true,
	},
	["Spore Bearer"] = {
			Name = "Spore Bearer",
			Link = "Spore Bearer",
			Description = "",
			Position = "Prefix",
			Introduced = "41",
			InternalName = "/Lotus/Types/Items/Titles/RoatheTitles/TitleNanoSpores",
			CodexSecret = true,
			ExcludeFromCodex = true,
	},
	["Staffbearer"] = {
			Name = "Staffbearer",
			Link = "Staffbearer",
			Description = "",
			Position = "Suffix",
			Introduced = "",
			InternalName = "/Lotus/Types/Items/Titles/VazarinStaffTitle",
			CodexSecret = true,
			ExcludeFromCodex = true,
	},
	["Steel Soldier"] = {
			Name = "Steel Soldier",
			Link = "Steel Soldier",
			Description = "",
			Position = "Suffix",
			Introduced = "41",
			InternalName = "/Lotus/Types/Items/Titles/RoatheTitles/TitleSteelEssence",
			CodexSecret = true,
			ExcludeFromCodex = true,
	},
	["Sticker Master"] = {
			Name = "Sticker Master",
			Link = "Sticker Master",
			Description = "",
			Position = "Prefix",
			Introduced = "",
			InternalName = "/Lotus/Types/Items/Titles/StickerConquestTitle",
			CodexSecret = true,
			ExcludeFromCodex = true,
	},
	["Storm Archer"] = {
			Name = "Storm Archer",
			Link = "Storm Archer",
			Description = "",
			Position = "Prefix",
			Introduced = "",
			InternalName = "/Lotus/Types/Items/Titles/MaduraiBowTitle",
			CodexSecret = true,
			ExcludeFromCodex = true,
	},
	["Strikes Twice"] = {
			Name = "Strikes Twice",
			Link = "Strikes Twice",
			Description = "",
			Position = "Suffix",
			Introduced = "43",
			InternalName = "/Lotus/Types/Items/Titles/HunhowHonoria/TitleVolt",
			CodexSecret = true,
			ExcludeFromCodex = true,
	},
	["Supreme Operative"] = {
			Name = "Supreme Operative",
			Link = "Supreme Operative",
			Description = "",
			Position = "Suffix",
			Introduced = "",
			InternalName = "/Lotus/Types/Items/Titles/CaliburChicksHighScoreTitle",
			CodexSecret = true,
			ExcludeFromCodex = true,
	},
	["Swordmaster"] = {
			Name = "Swordmaster",
			Link = "Swordmaster",
			Description = "",
			Position = "Suffix",
			Introduced = "",
			InternalName = "/Lotus/Types/Items/Titles/NaramonBladeTitle",
			CodexSecret = true,
			ExcludeFromCodex = true,
	},
	["Sworn Sister"] = {
			Name = "Sworn Sister",
			Link = "Sworn Sister",
			Description = "",
			Position = "Suffix",
			Introduced = "41",
			InternalName = "/Lotus/Types/Items/Titles/RoatheTitles/TitleSpectralDebris",
			CodexSecret = true,
			ExcludeFromCodex = true,
	},
	["Temporal Investigator"] = {
			Name = "Temporal Investigator",
			Link = "Temporal Investigator",
			Description = "",
			Position = "Suffix",
			Introduced = "43",
			InternalName = "/Lotus/Types/Items/Titles/CompleteETAMaxTitle",
			CodexSecret = true,
			ExcludeFromCodex = true,
	},
	["Tenens"] = {
			Name = "Tenens",
			Link = "Tenens",
			Description = "",
			Position = "Suffix",
			Introduced = "41.0.5",
			InternalName = "/Lotus/Types/Items/Titles/MedalRank9Title",
			CodexSecret = true,
			ExcludeFromCodex = true,
	},
	["Tenno of a Thousand Days"] = {
			Name = "Tenno of a Thousand Days",
			Link = "Tenno of a Thousand Days",
			Description = "",
			Position = "Prefix",
			Introduced = "",
			InternalName = "/Lotus/Types/Items/Titles/ThousandDaysLoginRewardTitle",
			CodexSecret = true,
			ExcludeFromCodex = true,
	},
	["The Arcanist"] = {
			Name = "The Arcanist",
			Link = "The Arcanist",
			Description = "",
			Position = "Suffix",
			Introduced = "",
			InternalName = "/Lotus/Types/Items/Titles/ArcaneCollectorTitle",
			CodexSecret = true,
			ExcludeFromCodex = true,
	},
	["The Awoken Sword"] = {
			Name = "The Awoken Sword",
			Link = "The Awoken Sword",
			Description = "",
			Position = "Prefix",
			Introduced = "43",
			InternalName = "/Lotus/Types/Items/Titles/HunhowHonoria/TitleExcalibur",
			CodexSecret = true,
			ExcludeFromCodex = true,
	},
	["The Copper Kid"] = {
			Name = "The Copper Kid",
			Link = "The Copper Kid",
			Description = "",
			Position = "Suffix",
			Introduced = "41",
			InternalName = "/Lotus/Types/Items/Titles/RoatheTitles/TitleCoprun",
			CodexSecret = true,
			ExcludeFromCodex = true,
	},
	["The Demolitionist"] = {
			Name = "The Demolitionist",
			Link = "The Demolitionist",
			Description = "",
			Position = "Prefix",
			Introduced = "43.5",
			InternalName = "/Lotus/Types/Items/Titles/KaboomTitle",
			CodexSecret = true,
			ExcludeFromCodex = true,
	},
	["The Devil's Confessor"] = {
			Name = "The Devil's Confessor",
			Link = "The Devil's Confessor",
			Description = "",
			Position = "Prefix",
			Introduced = "",
			InternalName = "/Lotus/Types/Items/Titles/UrielConfessionTitle",
			CodexSecret = true,
			ExcludeFromCodex = true,
	},
	["The Gallant Gourmand"] = {
			Name = "The Gallant Gourmand",
			Link = "The Gallant Gourmand",
			Description = "",
			Position = "Suffix",
			Introduced = "42",
			InternalName = "/Lotus/Types/Items/Titles/TitleGrendelPrime",
			CodexSecret = true,
			ExcludeFromCodex = true,
	},
	["The God Above Knowledge"] = {
			Name = "The God Above Knowledge",
			Link = "The God Above Knowledge",
			Description = "",
			Position = "Prefix",
			Introduced = "41",
			InternalName = "/Lotus/Types/Items/Titles/RoatheTitles/TitleEchoVoca",
			CodexSecret = true,
			ExcludeFromCodex = true,
	},
	["The Great & Terrible"] = {
			Name = "The Great & Terrible",
			Link = "The Great & Terrible",
			Description = "",
			Position = "Suffix",
			Introduced = "",
			InternalName = "/Lotus/Types/Items/Titles/JadeShadowsTitle",
			CodexSecret = true,
			ExcludeFromCodex = true,
	},
	["The Heir of Two Kingdoms"] = {
			Name = "The Heir of Two Kingdoms",
			Link = "The Heir of Two Kingdoms",
			Description = "",
			Position = "Suffix",
			Introduced = "42",
			InternalName = "/Lotus/Types/Items/Titles/RoatheTitles/TitleCaliban",
			CodexSecret = true,
			ExcludeFromCodex = true,
	},
	["The Invincible"] = {
			Name = "The Invincible",
			Link = "The Invincible",
			Description = "",
			Position = "Prefix",
			Introduced = "41",
			InternalName = "/Lotus/Types/Items/Titles/RoatheTitles/TitleJuggernaut",
			CodexSecret = true,
			ExcludeFromCodex = true,
	},
	["The Learned"] = {
			Name = "The Learned",
			Link = "The Learned",
			Description = "",
			Position = "Suffix",
			Introduced = "41",
			InternalName = "/Lotus/Types/Items/Titles/RoatheTitles/TitleDante",
			CodexSecret = true,
			ExcludeFromCodex = true,
	},
	["The Lover"] = {
			Name = "The Lover",
			Link = "The Lover",
			Description = "",
			Position = "Prefix",
			Introduced = "",
			InternalName = "/Lotus/Types/Items/Titles/LoverTitle",
			CodexSecret = true,
			ExcludeFromCodex = true,
	},
	["The Mad King"] = {
			Name = "The Mad King",
			Link = "The Mad King",
			Description = "",
			Position = "Prefix",
			Introduced = "41",
			InternalName = "/Lotus/Types/Items/Titles/RoatheTitles/TitleThraxPlasm",
			CodexSecret = true,
			ExcludeFromCodex = true,
	},
	["The Maniac of Deimos"] = {
			Name = "The Maniac of Deimos",
			Link = "The Maniac of Deimos",
			Description = "",
			Position = "Prefix",
			Introduced = "41",
			InternalName = "/Lotus/Types/Items/Titles/RoatheTitles/TitleGanglion",
			CodexSecret = true,
			ExcludeFromCodex = true,
	},
	["The Mechanic"] = {
			Name = "The Mechanic",
			Link = "The Mechanic",
			Description = "",
			Position = "Suffix",
			Introduced = "",
			InternalName = "/Lotus/Types/Items/Titles/HardTankTitle",
			CodexSecret = true,
			ExcludeFromCodex = true,
	},
	["The Navigator"] = {
			Name = "The Navigator",
			Link = "The Navigator",
			Description = "",
			Position = "Suffix",
			Introduced = "41",
			InternalName = "/Lotus/Types/Items/Titles/RoatheTitles/TitleNavCoordinates",
			CodexSecret = true,
			ExcludeFromCodex = true,
	},
	["The Persecuted"] = {
			Name = "The Persecuted",
			Link = "The Persecuted",
			Description = "",
			Position = "Suffix",
			Introduced = "41",
			InternalName = "/Lotus/Types/Items/Titles/RoatheTitles/TitleKullervo",
			CodexSecret = true,
			ExcludeFromCodex = true,
	},
	["The Power of Harrow Compels Thee"] = {
			Name = "The Power of Harrow Compels Thee",
			Link = "The Power of Harrow Compels Thee",
			Description = "",
			Position = "Suffix",
			Introduced = "41",
			InternalName = "/Lotus/Types/Items/Titles/RoatheTitles/TitleHarrowChasisBlueprint",
			CodexSecret = true,
			ExcludeFromCodex = true,
	},
	["The Scarlet Queen"] = {
			Name = "The Scarlet Queen",
			Link = "The Scarlet Queen",
			Description = "",
			Position = "Prefix",
			Introduced = "42",
			InternalName = "/Lotus/Types/Items/Titles/RoatheTitles/TitleGaruda",
			CodexSecret = true,
			ExcludeFromCodex = true,
	},
	["The Scavenger"] = {
			Name = "The Scavenger",
			Link = "The Scavenger",
			Description = "",
			Position = "Suffix",
			Introduced = "41",
			InternalName = "/Lotus/Types/Items/Titles/RoatheTitles/TitleSalvage",
			CodexSecret = true,
			ExcludeFromCodex = true,
	},
	["The Sunderer"] = {
			Name = "The Sunderer",
			Link = "The Sunderer",
			Description = "",
			Position = "Prefix",
			Introduced = "41",
			InternalName = "/Lotus/Types/Items/Titles/RoatheTitles/TitleRivenSilvers",
			CodexSecret = true,
			ExcludeFromCodex = true,
	},
	["The Void Called to Me"] = {
			Name = "The Void Called to Me",
			Link = "The Void Called to Me",
			Description = "",
			Position = "Prefix",
			Introduced = "",
			InternalName = "/Lotus/Types/Items/Titles/VorHardModeTitle",
			CodexSecret = true,
			ExcludeFromCodex = true,
	},
	["The Warden of Alchemy"] = {
			Name = "The Warden of Alchemy",
			Link = "The Warden of Alchemy",
			Description = "",
			Position = "Suffix",
			Introduced = "42",
			InternalName = "/Lotus/Types/Items/Titles/RoatheTitles/TitleLavos",
			CodexSecret = true,
			ExcludeFromCodex = true,
	},
	["Thirst for Knowledge"] = {
			Name = "Thirst for Knowledge",
			Link = "Thirst for Knowledge",
			Description = "",
			Position = "Prefix",
			Introduced = "42",
			InternalName = "/Lotus/Types/Items/Titles/CephalonSudaTitle",
			CodexSecret = true,
			ExcludeFromCodex = true,
	},
	["Ticker's Angel"] = {
			Name = "Ticker's Angel",
			Link = "Ticker's Angel",
			Description = "",
			Position = "Suffix",
			Introduced = "41",
			InternalName = "/Lotus/Types/Items/Titles/RoatheTitles/TitleDebtBond",
			CodexSecret = true,
			ExcludeFromCodex = true,
	},
	["Tiger"] = {
			Name = "Tiger",
			Link = "Tiger",
			Description = "",
			Position = "Prefix",
			Introduced = "42",
			InternalName = "/Lotus/Types/Items/Titles/MR19Title",
			CodexSecret = true,
			ExcludeFromCodex = true,
	},
	["True Master"] = {
			Name = "True Master",
			Link = "True Master",
			Description = "",
			Position = "Prefix",
			Introduced = "42",
			InternalName = "/Lotus/Types/Items/Titles/MR30Title",
			CodexSecret = true,
			ExcludeFromCodex = true,
	},
	["Unairu Vanguard"] = {
			Name = "Unairu Vanguard",
			Link = "Unairu Vanguard",
			Description = "",
			Position = "Prefix",
			Introduced = "41",
			InternalName = "/Lotus/Types/Items/Titles/UnairuFocusHoarderTitle",
			CodexSecret = true,
			ExcludeFromCodex = true,
	},
	["Under Friendly Fire"] = {
			Name = "Under Friendly Fire",
			Link = "Under Friendly Fire",
			Description = "",
			Position = "Suffix",
			Introduced = "",
			InternalName = "/Lotus/Types/Items/Titles/HunhullsKillerTitle",
			CodexSecret = true,
			ExcludeFromCodex = true,
	},
	["Vazarin Vanguard"] = {
			Name = "Vazarin Vanguard",
			Link = "Vazarin Vanguard",
			Description = "",
			Position = "Prefix",
			Introduced = "41",
			InternalName = "/Lotus/Types/Items/Titles/VazarinFocusHoarderTitle",
			CodexSecret = true,
			ExcludeFromCodex = true,
	},
	["Volatile Mote"] = {
			Name = "Volatile Mote",
			Link = "Volatile Mote",
			Description = "",
			Position = "Prefix",
			Introduced = "",
			InternalName = "/Lotus/Types/Items/Titles/BOTBEventVendor3Title",
			CodexSecret = true,
			ExcludeFromCodex = true,
	},
	["Voyager"] = {
			Name = "Voyager",
			Link = "Voyager",
			Description = "",
			Position = "Suffix",
			Introduced = "41",
			InternalName = "/Lotus/Types/Items/Titles/RoatheTitles/TitleRailjack",
			CodexSecret = true,
			ExcludeFromCodex = true,
	},
	["Was Never Here"] = {
			Name = "Was Never Here",
			Link = "Was Never Here",
			Description = "",
			Position = "Suffix",
			Introduced = "43.5",
			InternalName = "/Lotus/Types/Items/Titles/TheCameraAdds100Title",
			CodexSecret = true,
			ExcludeFromCodex = true,
	},
	["Wave Rider"] = {
			Name = "Wave Rider",
			Link = "Wave Rider",
			Description = "",
			Position = "Suffix",
			Introduced = "",
			InternalName = "/Lotus/Types/Items/Titles/KRacerTitle",
			CodexSecret = true,
			ExcludeFromCodex = true,
	},
	["Who Devours All"] = {
			Name = "Who Devours All",
			Link = "Who Devours All",
			Description = "",
			Position = "Suffix",
			Introduced = "42",
			InternalName = "/Lotus/Types/Items/Titles/RoatheTitles/TitleGrendel",
			CodexSecret = true,
			ExcludeFromCodex = true,
	},
	["Will Do Anything For Money"] = {
			Name = "Will Do Anything For Money",
			Link = "Will Do Anything For Money",
			Description = "",
			Position = "Suffix",
			Introduced = "43.5",
			InternalName = "/Lotus/Types/Items/Titles/Mercenary5InvasionsTitle",
			CodexSecret = true,
			ExcludeFromCodex = true,
	},
	["Wolfmother"] = {
			Name = "Wolfmother",
			Link = "Wolfmother",
			Description = "",
			Position = "Suffix",
			Introduced = "41",
			InternalName = "/Lotus/Types/Items/Titles/RoatheTitles/TitleVoruna",
			CodexSecret = true,
			ExcludeFromCodex = true,
	},
	["Worm Queen"] = {
			Name = "Worm Queen",
			Link = "Worm Queen",
			Description = "",
			Position = "Prefix",
			Introduced = "",
			InternalName = "/Lotus/Types/Items/Titles/KuvaMasteryTitle",
			CodexSecret = true,
			ExcludeFromCodex = true,
	},
	["Yuvan Rising"] = {
			Name = "Yuvan Rising",
			Link = "Yuvan Rising",
			Description = "",
			Position = "Suffix",
			Introduced = "41",
			InternalName = "/Lotus/Types/Items/Titles/RoatheTitles/TitleKuva",
			CodexSecret = true,
			ExcludeFromCodex = true,
	},
	["Zenurik Vanguard"] = {
			Name = "Zenurik Vanguard",
			Link = "Zenurik Vanguard",
			Description = "",
			Position = "Prefix",
			Introduced = "41",
			InternalName = "/Lotus/Types/Items/Titles/ZenurikFocusHoarderTitle",
			CodexSecret = true,
			ExcludeFromCodex = true,
	},
	["Legally Distinct"] = {
			Name = "Legally Distinct",
			Link = "Legally Distinct",
			Description = "",
			Position = "Prefix",
			Introduced = "43.5",
			InternalName = "/Lotus/Types/Items/Titles/AmirCampaignAnnoyTitle",
			CodexSecret = true,
			ExcludeFromCodex = true,
	},
	["Busy Monologuing"] = {
			Name = "Busy Monologuing",
			Link = "Busy Monologuing",
			Description = "",
			Position = "Suffix",
			Introduced = "43.5",
			InternalName = "/Lotus/Types/Items/Titles/AmirCampaignLootTitle",
			CodexSecret = true,
			ExcludeFromCodex = true,
	},
	["Forever Fablemaster"] = {
			Name = "Forever Fablemaster",
			Link = "Forever Fablemaster",
			Description = "",
			Position = "Suffix",
			Introduced = "43.5",
			InternalName = "/Lotus/Types/Items/Titles/AmirCampaignCompleteTitle",
			CodexSecret = true,
			ExcludeFromCodex = true,
	},
	["Butterfingers"] = {
			Name = "Butterfingers",
			Link = "Butterfingers",
			Description = "",
			Position = "Suffix",
			Introduced = "43.5",
			InternalName = "/Lotus/Types/Items/Titles/AmirCampaignButterfingersTitle",
			CodexSecret = true,
			ExcludeFromCodex = true,
	},
}

return honoriaData
